### ISSUE TITLE
code style: fix indention

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1010]
At least in some file indention is pretty inconsistent and results in hard to read code. We should try to fix this.

**Comment by 0mp** [comment]
I'm reading the source files at the moment, fixing style and typos. Could you point a source file which perfectly follows the project coding style? 

I feel a little bit confused since, I've found [the codestyle repository][1] which suggests that rsyslog project's styleguide is similar to [the GNOME style][2]. On the other hand, I can see from [this issue][3] that you are trying to define the style guide.

Cheers

[1]: https://github.com/rsyslog/codestyle
[2]: https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en
[3]: https://github.com/rsyslog/codestyle/issues/1

**Comment by rgerhards** [comment]
should be 100% done by now
