### ISSUE TITLE
My log how content is written to statefile in?

### ISSUE THREAD

**Issue by elain** [rsyslog/rsyslog#1060]
My rsyslog version 8.16.0 8.19.0 exists

Phenomenon as follows:
```
#more /var/lib/rsyslog/imfile-state\:-home-work-logs-php-php-fpm.log.slow
<Obj:1:strm:1:
+iCurrFNum:2:1:1:
+pszFName:1:36:/home/work/logs/php/php-fpm.log.slow:
+iMaxFiles:2:1:0:
+bDeleteOnClose:2:1:0:
+sType:2:1:2:
+tOperationsMode:2:1:1:
+tOpenMode:2:3:384:
+iCurrOffs:2:7:4325003:
+inode:2:8:26476609:
+prevLineSegment:1:193928:[07-Jun-2016 12:32:07]  [pool work] pid 5826#012script_filename = /home/work/data/www/api.bbs.xxx.com/public/index.php#012[0x0000000001ba3938] query() /data/data/lib/mi_lib/Db/Mysql.php:202#012[0x0000000001ba3698]
query() /data/data/lib/mi_lib/Db/Mysql.php:272#012[0x0000000001ba3478] select() /data/data/lib/mi_lib/Db/Mysql.php:294#012[0x0000000001ba2a10] selectOne() /data/data/www/api.bbs.xxx.com/application/models/Data/Post.php:602#012[0x0000000001b
a0a70] getPageByPosition() /data/data/www/api.bbs.xxx.com/application/models/Logic/Post.php:33#012[0x0000000001ba06f0] getPostListByThreadId() /data/data/www/api.bbs.xxx.com/application/actions/post/List.php:34#012[0x0000000001ba0330] process
() /data/data/www/api.bbs.xxx.com/application/components/MiForumApi/Base/Action.php:40#012[0x00007fff5a425ae0] execute() unknown:0#012[0x0000000001b9ffb0] run() /data/data/www/api.bbs.xxx.com/public/index.php:7#012#012[07-Jun-2016 12:32:15]
```

My profile is as follows:
```
module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
#module(load"immark")  # provides --MARK-- message capability
module(load="imfile")    # if you want to tail files
module(load="omkafka")   # lets you send to Kafka

$WorkDirectory /var/lib/rsyslog
$PreserveFQDN on

# Use default timestamp format
#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#php slow log
input(type="imfile"
      File="/home/work/logs/php/php-fpm.log.slow"
      Tag="php_log_slow"
      PersistStateInterval="1000"
      reopenOnTruncate="on"
      addMetadata="on"
      ReadMode="1"
      escapeLF="on"
)

template( name="general_log" type="string" string="%hostname% %msg%")

#php slow log
if ($syslogtag == "php_log_slow") then {
    action(
        broker=["c3-b2c-b2cop-efk-kafka01.bj:9092","c3-b2c-b2cop-efk-kafka02.bj:9092","c3-b2c-b2cop-efk-kafka03.bj:9092","c3-b2c-b2cop-efk-kafka04.bj:9092"]
        type="omkafka"
        topic="php_log_slow"
        template="general_log"
        confParam=["compression.codec=gzip"]
        #errorFile="rsyslog_err.log"
        partitions.auto="on"
    )
    stop
}
```

**Comment by davidelang** [comment]
I don't understand what your question is.

If you are asking what writes the statefile, it's written by the imfile module to keep track of where it is in the file

**Comment by elain** [comment]
@davidelang 
I mean I use rsyslog collect my php slow log, I found that I wrote about the contents of the log of imfile-statefile, how is this going?

**Comment by davidelang** [comment]
are you saying that you don't understand what creates the statefile or why it has information about your PHP log file in it?

**Comment by elain** [comment]
@davidelang 
I mean statefile should only read files stored state do? why the contents of the my slowlog is written to statefile it?

**Comment by davidelang** [comment]
Rsyslog needs to keep track of where it is in a file across reboots, including detecting if the file has been replaced (so that it can go to the beginning of the new file)

So rsyslog writes various things into the statefile, including the last message that it read from the file. That way on the next restart it can figure out if it can pick up where it left off or if it needs to go to the start of the file.

This is normal operation by rsyslog when using imfile.

**Comment by rgerhards** [comment]
In detail, we store the previous line segment when we deal with a message that is not yet complete. Because it is already read from the file, but it could not yet be submitted to processing, since it is incomplete. We cannot simply set the read pointer back, because than we would re-read that same data ever and ever again. So we need the actual data (read but not yet processed) in order to finalize the message once we find the end of the message in the input data.
