### ISSUE TITLE
imrelp-manyconn.sh and manytcp.sh should be skipped if RLIMIT_NOFILE is to low

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#1108]
The _imrelp-manyconn.sh_ and _manytcp.sh_ test are failing when running as normal user which isn't allowed to raise _RLIMIT_NOFILE_:

```
[manytcp.sh]: test concurrent tcp connections
------------------------------------------------------------
Test: ./manytcp.sh
------------------------------------------------------------
rsyslogd: could not set process file limit to 2000: Operation not permitted [kernel max 2000] [v8.20.0 try http://www.rsyslog.com/e/2116 ]
rsyslogd started with pid  105760
setrlimit to increase file handles failed: Operation not permitted
could net set sufficiently large number of open files for required connection count!
error during tcpflood! see rsyslog.out.log.save for what was written
cp: cannot stat 'rsyslog.out.log': No such file or directory
FAIL manytcp.sh (exit status: 1)

FAIL: imrelp-manyconn.sh
========================

------------------------------------------------------------
Test: ./imrelp-manyconn.sh
------------------------------------------------------------
   PID TTY          TIME CMD
 56083 pts/4    00:00:00 rsyslogd
rsyslogd started with pid  56083
setrlimit to increase file handles failed: Operation not permitted
could net set sufficiently large number of open files for required connection count!
error during tcpflood! see rsyslog.out.log.save for what was written
cp: cannot stat 'rsyslog.out.log': No such file or directory
FAIL imrelp-manyconn.sh (exit status: 1)
```

Because the failure is expected in someway I wanted to change the test to be automatically skipped if we know we will fail it.

However a [comment in tcpflood.c](https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L9-L14) indicates that tcpflood should handle such situation:

``` C
* -c    number of connections (default 1), use negative number
*      to set a "soft limit": if tcpflood cannot open the 
*      requested number of connections, gracefully degrade to
*      whatever number could be opened. This is useful in environments
*      where system config constraints cannot be overriden (e.g.
*      vservers, non-admin users, ...)
```

This doesn't work due to https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L1143-L1157 I guess so now I am not sure if it makes sense to fix tcpflood (looks like the quoted code should only run if `softLimitConnections != 1`) or change the comment (then we should also remove _softLimitConnections_ workaround)?

**Comment by rgerhards** [comment]
This is needed functionality. The commit should also note break it, as it
goes to the number that could be opened - 20 (at least that was the intent
and worked in my testing).

Sent from phone, thus brief.

Am 01.08.2016 13:05 schrieb "Thomas Deutschmann" <notifications@github.com>:

The *imrelp-manyconn.sh* and *manytcp.sh* test are failing when running as
normal user which isn't allowed to raise *RLIMIT_NOFILE*:

[manytcp.sh]: test concurrent tcp connections
------------------------------------------------------------
Test: ./manytcp.sh
------------------------------------------------------------
rsyslogd: could not set process file limit to 2000: Operation not
permitted [kernel max 2000] [v8.20.0 try http://www.rsyslog.com/e/2116
]
rsyslogd started with pid  105760
setrlimit to increase file handles failed: Operation not permitted
could net set sufficiently large number of open files for required
connection count!
error during tcpflood! see rsyslog.out.log.save for what was written
cp: cannot stat 'rsyslog.out.log': No such file or directory
FAIL manytcp.sh (exit status: 1)

FAIL: imrelp-manyconn.sh
========================

------------------------------------------------------------
Test: ./imrelp-manyconn.sh
------------------------------------------------------------
   PID TTY          TIME CMD
 56083 pts/4    00:00:00 rsyslogd
rsyslogd started with pid  56083
setrlimit to increase file handles failed: Operation not permitted
could net set sufficiently large number of open files for required
connection count!
error during tcpflood! see rsyslog.out.log.save for what was written
cp: cannot stat 'rsyslog.out.log': No such file or directory
FAIL imrelp-manyconn.sh (exit status: 1)

Because the failure is expected in someway I wanted to change the test to
be automatically skipped if we know we will fail it.

However a comment in tcpflood.c
<https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L9-L14>
indicates that tcpflood should handle such situation:

* -c    number of connections (default 1), use negative number
*      to set a "soft limit": if tcpflood cannot open the
*      requested number of connections, gracefully degrade to
*      whatever number could be opened. This is useful in environments
*      where system config constraints cannot be overriden (e.g.
*      vservers, non-admin users, ...)

This doesn't work due to
https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L1143-L1157
I guess so now I am not sure if it makes sense to fix tcpflood (looks like
the quoted code should only run if softLimitConnections != 1) or change the
comment (then we should also remove *softLimitConnections* workaround)?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/1108>, or mute the thread

**Comment by Whissi** [comment]
Not sure if you get my point: The two tests are failing when running as normal user because limits for open files are set to 1024 in my case (soft and hard limit). Now the test calls *tcpflood* with "-c-2000". According [to the comment from tcpflood](https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L9-L14) due to the negative value this should be treated as a soft limit.

However the code block from https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L1143-L1157 tries to raise limits to 2000+20=2020 which will fail so that *tcpflood* ends with non-zero exit code which ends the test. In other words: It ignores the negative value and treats the parameter as hard value.

From current point of view the comment is just wrong. There's no differentiation between soft and hard value because every value you entered will be tried to set... if that call will fail tcpflood will immediately end so that the softLimitConnections workaround will never be reached. The softLimitConnections workaround (i.e. trying to lower the value) will actually never run because when we reach that code we already have successfully raised the limits to 2020 so it isn't needed anymore...

**Comment by rgerhards** [comment]
2016-08-01 13:59 GMT+02:00 Thomas Deutschmann <notifications@github.com>:

> Not sure if you get my point: The two tests are failing when running as
> normal user because limits for open files are set to 1024 in my case (soft
> and hard limit). Now the test calls *tcpflood* with "-c-2000". According to
> the comment from tcpflood
> <https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L9-L14>
> due to the negative value this should be treated as a soft limit.
>
> However the code block from
> https://github.com/rsyslog/rsyslog/blob/61056a63178b898496636f5e1a5d45d79c20bbe9/tests/tcpflood.c#L1143-L1157
> tries to raise limits to 2000+20=2020 which will fail so that *tcpflood*
> ends with non-zero exit code which ends the test. In other words: It
> ignores the negative value and treats the parameter as hard value.
>
> From current point of view the comment is just wrong. There's no
> differentiation between soft and hard value because every value you entered
> will be tried to set... if that call will fail tcpflood will immediately
> end so that the softLimitConnections workaround will never be reached. The
> softLimitConnections workaround (i.e. trying to lower the value) will
> actually never run because when we reach that code we already have
> successfully raised the limits to 2020 so it isn't needed anymore...
>

yes I get this point. I am just a bit puzzled, because the code you mention
was added to solve exactly that problem, and did so in my testing.
Obviously it's not correct, but I still wonder what happened (an undetected
merge issue possibly...). On the other hand, the buildbot farm contains
machines with a 1024 limit, so we should also see failures there.

In any case, the option in tcpflood is needed and needs to be fixed. I'll
investigate as soon as I have some time.

Rainer

**Comment by rgerhards** [comment]
OK, old issue, and something strange happened in the interim: connection count has been reduced. But I think I can reproduce the core issue.
