### ISSUE TITLE
omkafka not support kafka 0.10.0.1

### ISSUE THREAD

**Issue by jianchen2580** [rsyslog/rsyslog#1134]
Can't get message since upgrade kafka 0.10.0.1, and idea?

**Comment by rsommer** [comment]
Since we updated to kafka 0.10.0.1 we get the following error while sending our syslog to kafka:
``omkafka: Failed to produce to topic 'syslog' partition -1: Local: Unknown topic  [v8.16.0 try http://www.rsyslog.com/e/2424 ]
This happens on debian jessie using rsyslog-kafka 8.16.0-1 from debian backports.

**Comment by rgerhards** [comment]
Can you provide a debug log, maybe it has more detail on what exactly failed.

**Comment by jianchen2580** [comment]
Kafka config issue, closed.

**Comment by yubingzhe727** [comment]
@jianchen2580 Hi:
想问一下你这个问题是怎么解决的？我现在也遇到omkafka不支持最新版本（0.10）的kafka的问题。
