### ISSUE TITLE
Urgent requirements of sampling logs

### ISSUE THREAD

**Issue by zacharyzhao** [rsyslog/rsyslog#1135]
## Summary

We have an urgent requirement of sampling logs by specified rate.

In our case, rsyslog got a large scale of logging input and these logs are transmitted to kafka cluster.
We care more about the numerical information in logs, and for the limitted bandwidth, the best way to solve problems caused by bandwidth is sampling them by specified rate.
It looks like people do sampling in signal transmission.

So I'm going to add configuration item of sampling and functions related to it for rsyslog, but I'm not sure which is better to add it in queue's general configuration or omkafka only.

Hope for your viewpoint,
Thanks!

**Comment by davidelang** [comment]
are you talking about summarizing logs (combining the meaning of many logs 
into one) or sampling logs (only logging 1 out of every N messages)

This should probably be done as a capability in the rsyslog core rather than 
adding it in omkafka

We have the ability to track custom metrics that are output as part of the 
impstats reports, that would probably work well for summarizing log data.

If you want to sample the logs, the best bet is probably to either use global 
variables or to introduce a rainerscript function that either does strict 
counting and is true once every X times it's called, or that you pass a 
precentage parameter to and it grabs a random number and returns true if it's 
below the percentage passed.

David Lang
