### ISSUE TITLE
Enable variable expansion for action parameters (and possibly other strings)

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1149]
Hi

Consider the following event formatted as JSON:

> {'key':'foo','msg':'this is a message'}

It would be great to be able to use variable substitution for action parameters, like:

```
    action(
        mode="queue"
        serverport="6379"
        serverpassword="password"
        server="localhost"
        type="omhiredis"
        key="" + $!key + ""          <------------------HERE
    )
```

**Note I used key="" + $!key + "", which could be same as key=$!key, instead of "$!key" to prevent issues with variable naming**. eg: $!keyX should print variable $!keyX (undefined) instead of $!key +"X"

I have been looking for _variable expansion_ on code, trying to guess if that's a minor change, but I wasn't able to find it.

Regards

**Comment by rgerhards** [comment]
The key problem is: what shall the action do if a parameter changes? e.g. shut down existing connection and create a new one? If so, shall it really do this if parameters frequently change? 

IMHO to handle this decently, the plugin itself must handle these kinds of dynamic properties and act accordingly. So there is no generic solution possible.

**Comment by mostolog** [comment]
Hi

If I understood properly, your concern is, for example, if action's _type_ changes (that, of course, will be quite an issue!)
On the other hand, the example I'm talking about it's very simple and shouldn't cause any trouble, rather than changing _key_ value on LPUSH command, like _message_ does.

I agree with you this kind of things could be handled by each module, but perhaps many modules or even all could support "static and dynamic parameters". All depends on how they are initialized, called, and how efficient is dynamic parameter changing.

As you are aware of rsyslog internals I beg you help me understand if this is possible/easy enough to consider it.

After I have been looking [omhiredis.c](https://github.com/rsyslog/rsyslog/blob/master/contrib/omhiredis/omhiredis.c) this is what I understood (Please, correct me if I'm wrong):

Object omhiredis is initialized with parameters readed from conf (key is set using _eCmdHdlrGetWord_). On writing, it runs command LPUSH with key stored at _pWrkrData->pData->key_ and writes message received from rsyslog "dispatcher" as _uchar *message_.

Couldn't _writeHiredis(uchar *message, wrkrInstanceData_t *pWrkrData)_ function being modified to be something like _writeHiredis(omhiredis_dynamic_params_t *params, wrkrInstanceData_t *pWrkrData)_ ?
Couldn't many other modules share similar _dynamic_params_t_ structs where parameters defined at .conf file were populated on each call to module->write?

Will populating those dynamic parameters for each call seriously affect performance?

Could you give me a hint about in which file "variable expansion" is done on templates?

Regards

**Comment by bobthemighty** [comment]
@mostolog I get the feeling that this issue was a first suggestion for #1201 - is your use case adequately covered by that other issue, or are there more things you would like to template?

I agree with @rgerhards that the individual modules would need to handle this - how would omhiredis manage if the `server` or `serverport` were dynamic according to the incoming log line, for example?

**Comment by mostolog** [comment]
@bobthemighty It's not the same, although #1201 could be a workaround for that specific Redis use-case.

On rsyslog.conf, when using omhiredis (but I guess also happens on other modules), I can't use key="$!appname". **This issue was intended to allow "any action parameter" be populated on processing time, for example from a property value**.

Hope I was clear this time.

**Comment by davidelang** [comment]
The rsyslog core can't know what parameters it's safe to change on the fly and what ones would require significant support by the module to change.

There's also a performance thing here. If parameters can change on every call to the module, they have to be checked, which slows things down a bit. Remember Rsyslog handles very high traffic volumes, we don't want to build in inefficiencies for the general case.

We also don't want to put code inside what's effectively a function call, so your example is something that  we really don't want to do.

If a parameter is a variable, set that variable before the action() call, not in the action call.

I know that if you come from a interpreted/scripting background, being able to execute math and call functions as a parameter value is common. But Rsyslog is far more of a compiled environment (for performance reasons) and as such, you can't put code anywhere you want.

**Comment by rgerhards** [comment]
I will accept PRs if they are done decently, but will definitely not do this myself. I think  @mostolog does not yet understand the real implication of changing the hostname, for example. Unfortunately, I do not know how to explain better.

**Comment by mostolog** [comment]
> @davidelang 
> If a parameter is a variable, set that variable before the action() call, not in the action call.

Could you elaborate on this? AFAIK, I will need multiple action statements...

**Comment by davidelang** [comment]
the rsyslog config language is not a full programming language. The action() statement is a single statement. For the same reasons that you can't just throw a variable in for a parameter that is defined to be a fixed string, you can't put computational statements in place of a string, or even a variable.

when you say
set $.var = "bar";
action(foo="$.var")

rsyslog does not lookup $.var and replace it with "bar" and then execute the statement

action(foo="bar")

instead rsyslog executes the action, and inside the action it says "what variable to a lookup? oh, I look for the variable named '$.var')

so if you try to say

action(foo="_"+"$.var")

you don't end up doing action(foo="_bar"), you get either a syntax error, or best case a failed lookup because there is no variable named '_$.var' (and I would expect a syntax error)

so your example where you do 

action( ...         key="" + $!key + "" )

cannot possibly work because you are embedding math/function calls where key is supposed to be a variable or simple string.

**Comment by davidelang** [comment]
I'm sure that I mangled the details of why things work the way they do, but I hope I got the basic idea correct enough

**Comment by rgerhards** [comment]
Longer reply follows a bit later. I do not like this idea. It complicates
things, is a lot of work (at least a couple of days), and boils down to
that everyone but developers loses the ability to write module doc.

Rainer

Sent from phone, thus brief.

Am 30.11.2016 10:17 schrieb "davidelang" <notifications@github.com>:

**Comment by rgerhards** [comment]
Sorry, wrong thread. That was for the doc...

Sent from phone, thus brief.

Am 30.11.2016 10:22 schrieb "Rainer Gerhards" <rgerhards@hq.adiscon.com>:

**Comment by mostolog** [comment]
@davidelang your last reply just shows current behavior, but doesn't expose why it cannot be changed neither explain how _set_ would help (trying to answer _"If a parameter is a variable, set that variable before the action() call, not in the action call."_).
However, your previous reply states:
>  There's also a performance thing here...so your example is something that we really don't want to do.

It's clear enough this request won't have a long life, so I'm closing.

Actually, something like:
> action(dynamic="true" template="dynamic_template")

allows to have "dynamic" actions, however seems not standarized across actions, neither as flexible as it could be. Please, consider a future review to make thins simpler in order to have dynamic property fields, like described above. Anyway, further discussion can be done on list ;)

**Comment by davidelang** [comment]
parameters to an action() call can be strings, binary values, or variable names.

They can't be formulas.

formulas can only be used in two places

1. in tests (if statements)

2. in set statements

so you can't say
action(foo="$,bar" +1)

but you can say
set $.baz=$.bar +1;
action(foo="$baz")


you can't use a function call as part of an action() parameter, and math is a function call.

As I understand it, changing the rsyslog config engine to allow function calls as action() parameters is a pretty significant issue, especially to try and do it without hurting performance in the far more common cases where they aren't needed.

**Comment by rgerhards** [comment]
There is a single question that needs to be answered. I (and I think @bobthemighty ) have already comented on it, but otherwise this seems not to be appreciated:

Envision you could say
```
action(type="omfwd" target=$var)
```
How shall the engine handle this without help of the plugin? And if we assume the plugins handles it, would it really make sense to tear down the session each time target changes and start a new one? That's why omfile has ```dynafile``` vs. ```file``` and why dynafile has a cache.

The plain fact is that modules **must be different** to support this. It's easy to stuff a different value into the target each time, but it's far from easy to expect the plugin to handle that for all cases and do so with decent performance.

**Comment by rgerhards** [comment]
> but you can say
> set $.baz=$.bar +1;
> action(foo="$baz")

No, you cannot do this. Parameters need to be constant.

**Comment by davidelang** [comment]
@rgerhards 
I was not meaning in the general case, I was meaning in the cases where a variable is allowed.
