### ISSUE TITLE
Compile message 

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1179]
When building on ubuntu16.04 latest 8.22 source I'm getting a few messages like:

```
make[2]: Entering directory '/rsyslog/compat'
  CC       compat_la-getifaddrs.lo
  CC       compat_la-strndup.lo
  CCLD     compat.la
ar: `u' modifier ignored since `D' is the default (see `U')
...
```

Is there anything I could do to sanitize the building script to avoid those messages?
Regards

**Comment by rgerhards** [comment]
That's an autotools issues, see for example here: https://bugzilla.redhat.com/show_bug.cgi?id=1155273

If you find a way to fix it, I would appreciate a PR.

**Comment by mostolog** [comment]
As stated on https://bugzilla.redhat.com/show_bug.cgi?id=1155273#c13, perhaps setting ARFLAGS &
AR_FLAGS to 'cr' fixes the warning, but I don't know what consequences it may have.
Seem little or none, so I'm going to try a local build and let you know

**Comment by D3m0nKingx** [comment]
I did some digging into this, granted this issue is old. But the problem isn't with libtoolize, by default it recognizes the correct flags ('u' has been replaced by 'U'). The issue when executing `./autogen.sh` it reads the configure.ac file and sees that 'u' is the modifer being used, so by changing this to U, and re-running autogen.sh, the correct flag will be injected into the libtool script in the working directory. 

Hope this will be more clear for others that come across this in the future.

Furthermore AR is an archiving tool: https://sourceware.org/binutils/docs/binutils/ar-cmdline.html

From what I can tell, is that it uses the 'U' modifier to make sure it uses recently modified files (by timestamp) when creating the archives. using 'D' would disregard this and include any file (zero timestamp).

**Comment by mbiebl** [comment]
Shouldn't this be rather fixed in libtool itself? Having individual projects work around this sounds like the wrong way to address this

**Comment by D3m0nKingx** [comment]
Seems this is related more to automake: http://gnu-automake.7480.n7.nabble.com/bug-20082-new-warning-from-ar-on-rawhide-systems-td21769.html

**Comment by rgerhards** [comment]
That mail thread IMHO clearly says it is nothing that rsyslog has to fix.

Rainer
