### ISSUE TITLE
Sending issue? / Template not working as expected (parsing problem? curly braces? quotes?)

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1191]
Hi

**One host is sending syslog messages to a proxy rsyslog, which _format them as json_, and forwards to a central rsyslog using omrelp (which store it on redis using omhiredis).** \<breath>

```
<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message "a".

template(name="json" type="list" option.json="on") {
	constant(value="{")
	constant(value="\"time_forwarded\":\"")
	property(name="timegenerated" dateFormat="rfc3339")
	constant(value="\",\"msg\":\"")
	property(name="rawmsg")
	constant(value="\"}")
}
```

Using wireshark/tcpdump to debug I see:
```
{"time_forwarded": "2016-10-13T14:46:18.148838+02:00","msg":"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \"a\"."}
```

So far, so good...**but that " " after time_forwarded worries me...**

---

Without applying any templates, seems messages are received this way:
```
<167>2016-10-13T14:46:18.148828+02:00 proxy {\"time_forwarded\": \"2016-10-13T14:46:18.148838+02:00\",\"msg\":\"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \\\"a\\\".\"}
```

Notice quotes are being escaped (:question:). _Still have to figure it out why, but not a problem now._

But enabling **the following template doesn't work as expected**:
```
template(name="json" type="list") {
    constant(value="{")
    constant(value="\"time_received\":\"")
    property(name="timereported" dateFormat="rfc3339")
    constant(value="\",\"host_received\":\"")
    property(name="$myhostname")
    constant(value="\",")
    # starting on 2 (after left curly bracket), include all json data
    property(name="msg" position.from="2")
    #constant(value="\n")
}
```

**Expected result**
```
{\"time_received\":\"2016-10-13T14:46:18.148828+02:00\",\"host_received\":\"central\",\"time_forwarded\": \"2016-10-13T14:46:18.148838+02:00\",\"msg\":\"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \\\"a\\\".\"}
```

**Actual Result**
```
{\"time_received\":\"2016-10-13T14:46:18.148828+02:00\",\"host_received\":\"central\",\"2016-10-13T14:46:18.148838+02:00\",\"msg\":\"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \\\"a\\\".\"}
```
Notice the time_forwarded _json key_ has disappeared.
**Ẁhere did \"time_forwarded\": go?**

Am I missing/messing something?

**Comment by mostolog** [comment]
After more digging, I'm starting to think this could be an example of http://www.rsyslog.com/doc/syslog_parsing.html (It was hard to find, though)

Adding <SP>, hence having "  " before msg make it work properly.

Is there any way to make rsyslog add "-" tag field /comply with rfc5424 automatically for outgoing msg? ie: template defines message, but header!!!
(I keep looking for a solution in the meantime)

**Comment by mostolog** [comment]
After more reading:
As far as I know, an incoming syslog message should have the following format:
> <pri>timestamp host tag msg

According to what I described above, seems _syslogtag_ isn't being auto-completed on output, hence it's using BSD's RFC3164 as default and splitting at ":". In the other hand, "-" **is** a valid tag value(appname)

IMHO, if tag is not set "anywhere", then om**** should set it as "-", right?

templates shouldn't include TAG field, isn't it?

I'm trying to find where all this started to broke...

**Comment by rgerhards** [comment]
Template includes syslog header. Default templates do it all right, check
them. More later...

Rainer

Sent from phone, thus brief.

Am 14.10.2016 08:26 schrieb "mostolog" <notifications@github.com>:

**Comment by mostolog** [comment]
> Template includes syslog header.

I didn't know that, neither found a clear statement on this. Could you provide a link? May I update the docs?

Assuming template includes HEADER, why a complete message "my: message" is received like:
> <pr>timestamp hostname my: message (actually, my is parsed as TAG)

**I guess rsyslog input parser goes default RFC3164...but, as I'm not an expert it's just a guess**

I mean...pri, timestamp and hostname (and tag) are part of HEADER, but weren't set on my template.
I would understand getting:
> my message

even:
> <pr>timestamp hostname - my message (notice the - TAG)

but not an incomplete header, without TAG. **Could this be an issue like an old one to implement a message without timestamp/hostname/tag, which was fixed supporting "-"?**...I saw it on a list, but haven't been able to find it again.

> Default templates do it all right, check them.

 According to docs, templates can be found at syslogd.c prefixed "template_" but I haven't been able to find it. Could you provide a more updated link/hint?

I'll continue digging...

**Comment by rgerhards** [comment]
2016-10-14 9:24 GMT+02:00 mostolog <notifications@github.com>:

> Template includes syslog header.
>
> I didn't know that, neither found a clear statement on this. Could you
> provide a link? May I update the docs?
>

Maybe it's not written explicitely. Doc PR would be great (probably at
omfwd or template doc or both?)

> Assuming template includes HEADER, why a complete message "my: message" is
> received like:
>
> timestamp hostname my: message (actually, my is parsed as TAG)
>
> *I guess rsyslog input parser goes default RFC3164...but, as I'm not an
> expert it's just a guess*
>
> I mean...pri, timestamp and hostname (and tag) are part of HEADER, but
> weren't set on my template.
> I would understand getting:
>
> my message
>
> even:
>
> timestamp hostname - my message (notice the - TAG)
>
> but not an incomplete header, without TAG. *Could this be an issue like
> an old one to implement a message without timestamp/hostname/tag, which was
> fixed supporting "-"?*...I saw it on a list, but haven't been able to
> find it again.
>

Because the header is optional in RFC3164. Also, syslog messages are often
malformed and we use a heuristic to guess what each field may be.  More
info:

http://www.rsyslog.com/doc/syslog_parsing.html

Note that this is also one reason why the header is part of the template:
folks often need some weired header format to satisfy a receiver system,
and the heading being part of the template provides them this ability.

> Default templates do it all right, check them.
>
> According to docs, templates can be found at syslogd.c prefixed
> "template_" but I haven't been able to find it. Could you provide a more
> updated link/hint?
>

It has moved to rsconf.c:

https://github.com/rsyslog/rsyslog/blob/master/runtime/rsconf.c#L86

The default templates also are now stringgens, so you need to check their
code. Alternatively, you can look at a v5 version's code. The template
def's haven't changed. The 3164 template is given in the template doc:

http://www.rsyslog.com/doc/v8-stable/configuration/templates.html

HTH
Rainer

**Comment by mostolog** [comment]
> Maybe it's not written explicitly. Doc PR would be great (probably at omfwd or template doc or both?)

I'll do it as soon as I understand how/when HEADER was added to message (**outgoing**? incoming?). And, of course, why TAG wasn't added (or "-").

Definitively, a reference to http://www.rsyslog.com/doc/syslog_parsing.html shall be added on template doc. I'll add that also, once I understand how "formats pattern match" is done.
At https://github.com/rsyslog/rsyslog/blob/master/runtime/rsconf.c#L86 I don't see any format without TAG, so something weird may be happening...

> The default templates also are now stringgens

Those referenced as plugins in docs? I still don't fully understand what is that/how it works/if I can compile my templates->faster processing...

**Comment by rgerhards** [comment]
2016-10-14 10:06 GMT+02:00 mostolog <notifications@github.com>:

> Maybe it's not written explicitly. Doc PR would be great (probably at
> omfwd or template doc or both?)
>
> I'll do it as soon as I understand how/when HEADER was added to message (
> *outgoing*? incoming?). And, of course, why TAG wasn't added (or "-").
>
> Definitively, a reference to http://www.rsyslog.com/doc/
> syslog_parsing.html shall be added on template doc. I'll add that also,
> once I understand how "formats pattern match" is done.
> At https://github.com/rsyslog/rsyslog/blob/master/runtime/rsconf.c#L86 I
> don't see any format without TAG, so something weird may be happening...
>
> The default templates also are now stringgens
>
> Those referenced as plugins in docs? I still don't fully understand what
> is that/how it works/if I can compile my templates->faster processing...
>
>
I guess you think it is more complex than it is. This is how it works:

On INPUT, message is received and parsed by the defined parser modules
(Default: try rfc5424, if that fails try rfc3164, which will never fail as
everything is valid under 3164). This sets the properties.

Now you can use the properties any way you like,

On OUTPUT, the template is generated .. and it uses the properties (those
extracted by parser and those that you possibly have set).

So there is no magic header passing between INPUT and OUTPUT. It's all just
in the properties.

Rainer

**Comment by mostolog** [comment]
Ok about input parsing (and rfc3164 never failing)
Ok about output but...why:

> this:is a message

is transformed on output to:
> this: is a message (notice space after ":")

When using template "%msg%"?

**Comment by rgerhards** [comment]
Because the heuristic assumes "this:" is the tag field. This has proven to
be normally the best fit.

You need to add a header to get correct results.

Sent from phone, thus brief.

Am 14.10.2016 15:55 schrieb "mostolog" <notifications@github.com>:

**Comment by mostolog** [comment]
I guess you are referring to input heuristic, matching rfc3164 and doing its best, right?

**Comment by rgerhards** [comment]
Yes

Sent from phone, thus brief.

Am 14.10.2016 16:24 schrieb "mostolog" <notifications@github.com>:

**Comment by davidelang** [comment]
it's clear from the e-mail discussion that @mostolog is still confused on this issue. I'll leave it closed as it's not a rsyslog bug, but a communications issue (which may lead to documentation improvements)

the rfc-3184 over-the-wire format is:

<pri>Mmm DD HH:MM:SS hostname syslogtag message

unfortunately, there are a lot of systems that mangle this and send something else. As a result, the rsyslog rfc-3184 parser has lots of heiristics in it to attempt to provide useful data.

It's pretty easy to identify that there is no <pri> field and if the timestamp is missing

But one of the most common problems that we still have is that the rules for what a valid hostname and syslogtag can be are very loose, and systems that leave them out frequently result in text that the sender intended to be part of the message being parsed as a syslogtag or hostname

you can see this clearly if you log a message with the template RSYSLOG_DebugFormat

The RSYSLOG_TraditionalForwardFormat is
<%pri%>%timestamp% %hostname% %syslogtag%: %msg%
(ignoring the trickery to make sure that we aren't adding an extra space between the ':' and the message)

If the incoming message was malformed badly enough to be parsed incorrectly, the output will look strange because the variables have the wrong data in them. If at all possible this should be fixed on the sending side, but it is possible (with a lot of work, and custom templates) to fix it on the output from rsyslog.


When you create a template for rsyslog to use when delivering a message, that template replaces EVERYTHING that rsyslog would normally do in formatting the output. It's not just replacing the msg portion, it's replacing everything. This is needed so that you can output something sane if the sender is giving you garbage.

There are no heuristics on the output side, it's purely deterministic, it uses what is in the properties (including the variables if they are used in the template)

**Comment by mostolog** [comment]
Hi.

I don't know if I understood correctly, sorry for any misunderstanding.
As you can see above, my message:
> <167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message "a".

Is converted with the template help to:
> {"time_forwarded": "2016-10-13T14:46:18.148838+02:00","msg":"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \"a\"."}

To sum up: this message doesn't have priority, timestamp, host, syslogtag or ":" but **just a json body without any header**

According to @rgerhards and @davidelang comments, when this message arrives to input module, it tries to parse it to rfc-3184 (and others).

As depicted above, message is sent like:
> <167>2016-10-13T14:46:18.148828+02:00 proxy {\"time_forwarded\": \"2016-10-13T14:46:18.148838+02:00\",\"msg\":\"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \\\"a\\\".\"}

I'm concerned about that space after ":". which seems to be sppliting the message.

Of course, it makes sense once you read it, and can be solved adding time host and tag before json message...but shouldn't it be simpler if parsing modules were disabled and message is sent and received AS IS ?

This boils down to the question I made on lists: is rsyslog a vitamined syslog (handling syslog messages) or a shipper (which handles whatever, even lines without HEADER, MSG and so)?

**Comment by rgerhards** [comment]
Well, it is what you configure it to be. The inputs expect syslog messages, usually. If you don't like that, you can use rawmsg, or you can create a parser that mimics a proper header. If the latter is useful, I think we could add it in the 8.24 timeframe, it's trivial.

**Comment by davidelang** [comment]
you are mistaken. if the template says that it is:

{"time_forwarded": "2016-10-13T14:46:18.148838+02:00","msg":"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message "a"."}

than that is what goes out over the wire, not:

<167>2016-10-13T14:46:18.148828+02:00 proxy {"time_forwarded": "2016-10-13T14:46:18.148838+02:00","msg":"<167>2016-10-13T14:46:18.148828+02:00 host app[1234]: message \"a\"."}

what is happening here is that when the rfc-3184 parser tries to parse the message, it sees that there is no PRI tag, so it sets a default. It sees that there is no timestamp so it sets timestamp to the time the message was received by rsyslog, it then goes to set the hostname, but it knows that '{' is not a valid character in a hostname, so it sets hostname = fromhost (a name lookup of the IP that the packet originated from, it then looks at the next field to see if it is a valid tag, and I think '{"time_forwarded":' could be a legitimate tag, so it gets set to syslogtag

When

**Comment by rgerhards** [comment]
Small correction. It is rfc3164. Doesn't change anything said, but I
thought I point it  out. ;-)

Sent from phone, thus brief.

Am 23.11.2016 21:34 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
I think the cause of the confusion here is that rsyslog isn't just rejecting the message as invalid, it's doing _almost_ what he wants with it, and so he's assuming that the message is in an acceptable format and rsyslog is mishandling it.

**Comment by rgerhards** [comment]
I admit I have no idea how I could solve that... If we knew it were
invalid, we would detect that, but...

Sent from phone, thus brief.

Am 23.11.2016 21:51 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
I'm not sure there is a solution.

**Comment by mostolog** [comment]
Having an eye on https://tools.ietf.org/html/rfc3164#section-4.3.3:
```
   If the relay receives a syslog message without a PRI, or with an
   unidentifiable PRI, then it MUST insert a PRI with a Priority value
   of 13 as well as a TIMESTAMP as described in Section 4.3.2.  The
   relay SHOULD also insert a HOSTNAME as described in Section 4.3.2.
   The entire contents of the received packet will be treated as the
   CONTENT of the relayed MSG and appended.
```
so rawmsg -> CONTENT (not TAG!)

Also, as stated in https://tools.ietf.org/html/rfc3164#section-5.4 example 2:
```
   Example 2

   Use the BFG!

   While this is a valid message, it has extraordinarily little useful
   information.  This message does not have any discernable PRI part. It
   does not contain a timestamp or any indication of the source of the
   message.  If this message is stored on paper or disk, subsequent
   review of the message will not yield anything of value.

   This example is obviously an original message from a device.  A relay
   MUST make changes to the message as described in Section 4.3 before
   forwarding it.  The resulting relayed message is shown below.
        <13>Feb  5 17:32:18 10.0.0.99 Use the BFG!
   In this relayed message, the entire message has been treated as the
   CONTENT portion of the MSG part.  First, a valid PRI part has been
   added using the default priority value of 13.  Next, a TIMESTAMP has
   been added along with a HOSTNAME in the HEADER part.  Subsequent
   relays will not make any further changes to this message.  It should
   be noted in this example that the day of the month is less than 10.
   Since single digits in the date (5 in this case) are preceded by a
   space in the TIMESTAMP format, there are two spaces following the
   month in the TIMESTAMP before the day of the month.  Also, the relay
   appears to have no knowledge of the host name of the device sending
   the message so it has inserted the IPv4 address of the device into
   the HOSTNAME field.
```

again: rawmsg -> CONTENT (not TAG!)


Considering the above: have we found a parsing heuristic issue?

IMHO it makes sense to merge pm and mm into "task modules", which can work with rawmsg and set/define other properties which can be used by following tasks.

If I were able to disable parsers and able to use rawmsg property on modules, that could be a workaround

Finally: Lets suppose a "do nothing parser" is built: how would I specify that module to be used instead of bundled RFCs?

**Comment by rgerhards** [comment]
Note the difference between "MUST", "SHOULD" and nothing specified. The current heuristic is fully within RFC3164 rules, and it has proven to be very good at sorting out things. But a heuristic is obviously always a heuristic, so it never works perfectly for all intents (nor can it do).

We could merge PM and MM, and there is backing tech argument that this might be a good move. However, that would invalidate almost all existing configs and it would actually complicate writing new configs (because each user would now need to know about parsers). So this is something I am strongly opposed to. 

You can always use ```rawmsg```, no need to disable parsers. If you need it, that's where it is for.

This documents how parsers are specified: http://www.rsyslog.com/doc/master/configuration/parser.html

**Comment by rgerhards** [comment]
Side-note to help you understand the heuristic. Let's say you have MSG content "logger: test". How do you know if TAG="logger:", MSG =" test" or TAG="", MSG="logger: test"? That's the question that the heuristic needs to answer. Almost all syslog messages have a tag, so the heuristic uses the first interpretation.

**Comment by mostolog** [comment]
SHOULD means "good practice".

> So this is something I am strongly opposed to.
Reading the link, seems quite easy to disable parsers with an "set all properties to '' but rawmsg" parser. Do you think it may be useful as a rsyslog bundled parser?

**Comment by rgerhards** [comment]
"SHOULD" is precisely defined here: https://www.ietf.org/rfc/rfc2119.txt

I didn't ask what you, as a human, with additional knowledge would do in this regard. I asked how the heuristic would decide what to do.

I admit I also wonder why you insist so much in sending a malformed message and expecting that it is interpreted as you intend? This is not something we can do, as it breaks very many deployments and in almost all cases makes no sense at all.

The fix for your use case is simple, either
* use a correct header
* use rawmsg
Why do you object both of these solutions?

**Comment by rgerhards** [comment]
Ohhhhh... I think I finally caught your misunderstanding. Rsyslog *always* is a *relay*. Only in cases where it emits messages itself it is the *originator*.

**Comment by mostolog** [comment]
According to RFC3164 in the event of a malformed message there's a "recommended way" to handle it.
I would love rsyslog parser to do it that way although, as you quoted, it's not mandatory.

Please observe the message can be generated by third-parties, without having control over format, and taking heuristic assumptions has some risks (although, it's a contract for better understanding!)

The main issue with this (and remember this issue was closed a few days ago) it's:

- how/when parser works wasn't clear to me at that point. I'll try to improve documentation
- if parsers should process all messages. if I'm going to work with rawmsg...why wasting cpu cycles to parse other properties?
- if parsers could be disabled. As you linked above, a "dummy parser" could do the trick

Regards

**Comment by rgerhards** [comment]
>
> According to RFC3164 in the event of a malformed message there's a
> "recommended way" to handle it.
> I would love rsyslog parser to do it that way although, as you quoted,
> it's not mandatory.
>

couple of issues:
* RFC3164 has informational status, that means it is NO normative
documentm, see https://tools.ietf.org/html/rfc1796
  Most RFCs are actually not normative, but RFC with "proposed standard"
are typically taken as normative. For syslog format, RFC5424 is the only
normative ("proposed standard") RFC

* RFC3164 documents what has been seen in practice; however, practice is
very heterogenous; if we follow all 3164 recommendation, most messages will
be parsed in a way unexpected by the user

> Please observe the message can be generated by third-parties, without
having control over format, and taking heuristic assumptions has some risks
(although, it's a contract for better understanding!)

I am doing sylsog for 20+ years. Believe me that the current heuristics is
the best compromise we could find to suit as many use cases as possible. If
you like, you can also wade through the commit log to see whenever we made
changes to the heuristics due to support e.g. Cisco message. It's not
perfect, but works and people count on it working exactly the way it does.

I do not object to create a "strict" RFC3164 parser (even though strict and
3164 is a contradiction in itself ;-)), but this cannot be the default
parser for rsyslog to use.

Note that the full format issue is documented here:
http://www.rsyslog.com/doc/v8-stable/whitepapers/syslog_parsing.html

The main issue with this (and remember this issue was closed a few days
> ago) it's:
>
>    - how/when parser works wasn't clear to me at that point. I'll try to
>    improve documentation
>
>
It would definitely be welcome if you improve the existing doc so that the
problem becomes clearer for use cases like you describe.

>
>    - if parsers should process all messages. if I'm going to work with
>    rawmsg...why wasting cpu cycles to parse other properties?
>
> ack, thus I proposed the "dummy parser"

>
>    - if parsers could be disabled. As you linked above, a "dummy parser"
>    could do the trick
>
>
you cannot completely disable parsers, as then no message object is
generated and the message is thrown away.

Again, a parser that takes everything literally and populates the rest of
the necessary properties with proper defaults is easy to write and I agree
that it can solve some use cases. Just open a PR, I think we can get it
into 8.24.0.

Note that we still need to populate the standard properties, because the
rsyslog engine can filter on them, they are used in templates etc, etc.

This is what a simple lightweight shipper would not need, but the full
engine needs to have everything in place, as you cannot assume nobody will
use e.g. if $fromhost == "blabla", which would segfault if you do not set
the property.

Rainer

**Comment by rgerhards** [comment]
> Again, a parser that takes everything literally and populates the rest of
> the necessary properties with proper defaults is easy to write and I agree
> that it can solve some use cases. Just open a PR, I think we can get it
> into 8.24.0.

sorry, I meant open an "enhancement issue". No PR necessary.
