### ISSUE TITLE
how to write a c++ or python external plugin for message modification

### ISSUE THREAD

**Issue by Dark-Passenger** [rsyslog/rsyslog#1198]
Hi,

sorry for posting this here. but i have not found any documentation regarding the matter. Any help on how i can write a message modification plugin for rsyslog. I am okay with c++ or python.

**Comment by rgerhards** [comment]
Have a look here:

https://github.com/rsyslog/rsyslog/tree/master/plugins/external

It also contains a python skeleton (sample) that you can build on. If the info is still unclear, let me know. I think I have some presentations online on the topic. I close the issue for now, but no problem re-opening it if needed. :-)

**Comment by Dark-Passenger** [comment]
Hi @rgerhards I did look at that but it wasnt clear on any implementation specifics for modification plugins. also no data on how these would be integrated with the rsyslog flow.

PS: was wondering if the same is implemented in c++ would it be a regular c++ code or does it need to be a shared library ?

**Comment by Dark-Passenger** [comment]
Simply put wanted some help or documentation on integration.

**Comment by rgerhards** [comment]
There is a presentation available at http://www.rsyslog.com/writing-external-output-plugins-for-rsyslog/
If you write C++, I would recommend to use plain C, so that you can write a native plugin. We have some info on that available here

http://www.rsyslog.com/doc/v8-stable/development/dev_oplugins.html

The page is a bit aged and it primarily is on output plugins. But the best advise is to start from an existing message modification module. The internal plumbing is mostly handled by the interface definition macros.

**Comment by Dark-Passenger** [comment]
Hi while I have access to you... Are all elements modifiable ? I read that
program name is a static tag ... Hence wondering.

**Comment by Dark-Passenger** [comment]
Thanks clarified with the presentation.
