### ISSUE TITLE
omprog cant export messages as json data

### ISSUE THREAD

**Issue by Dark-Passenger** [rsyslog/rsyslog#1200]
Hi,

so external modules work awesome.but its all exported as a single string. no mesg parameters...

**Comment by rgerhards** [comment]
sorry, I don't understand what you mean. Do you have a sample?

**Comment by Dark-Passenger** [comment]
hi just to clarify wrote a simple output module that was triggered through a omprog action.
Now it read through stdin.

The problem is there is no easy way to take input as a json object.

Also there is a little confusion on slow message output. It seems to come in batches but there seems no switch to control this.

**Comment by davidelang** [comment]
On Tue, 18 Oct 2016, Dhruv Paranjape wrote:

> hi just to clarify wrote a simple output module that was triggered through a omprog action.
> Now it read through stdin.
>
> The problem is there is no easy way to take input as a json object.

Can't you just define a template that formats the data as JSON?

> Also there is a little confusion on slow message output. It seems to come in batches but there seems no switch to control this.

There is a batch size parameter, but setting it to single messages can 
significantly slow message processing.

David Lang

**Comment by Dark-Passenger** [comment]
Okay, the processing is fine. I was hoping for a default json template.

Though a non issue. Closing.

**Comment by davidelang** [comment]
I think it would be a good idea to have one (this would be a simple string 
module), but I'll point out that if you dump all the data out to your program, 
it needs to process all the data.

In most cases you don't actually need everything, so it may be a win to only 
send the part of the data that you need.

David Lang

**Comment by rgerhards** [comment]
A string module would not make much sense here - the dominating expensive
part would be json generation.

I can add a canned template if you like, it's a few minutes job...

Rainer

Sent from phone, thus brief.

Am 27.10.2016 23:05 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
On Thu, 27 Oct 2016, Rainer Gerhards wrote:

> A string module would not make much sense here - the dominating expensive
> part would be json generation.
>
> I can add a canned template if you like, it's a few minutes job...

I was assuming that a canned template would be a string module.

I strongly believe that we need a few new canned templates, especially as we are 
encouraging more JSON use (and interacting with things like logstash that are 
json based)

a raw json output (with newlines) would be extremely useful for many purposes 
(writing to files, sending to logstash, omprog and mmmodule to throw out a few)

a syslog compatible format with a message body would also be extremely useful

and then we have the very common question of how to modify some field in a 
message, we should have a variation of a couple formats that look for some 
user variables and if they exist override the default properties.

David Lang

**Comment by rgerhards** [comment]
A canned template is simply what you would otherwise write in rsyslog.conf,
it gets added internally via the same way. Very easy to add. I think they
are in rsconf.c, but I may be wrong.

The question is if it makes sense to create many of them.

Rainer

Sent from phone, thus brief.

Am 27.10.2016 23:55 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
On Thu, 27 Oct 2016, Rainer Gerhards wrote:

> A canned template is simply what you would otherwise write in rsyslog.conf,
> it gets added internally via the same way. Very easy to add. I think they
> are in rsconf.c, but I may be wrong.

Ok, I thought they were written in C

> The question is if it makes sense to create many of them.

I don't think we want to create a lot of them, but I do think we need a few more 
than we currently have.

Right now we don't have anything that outputs structured data (other than the 
debugformat), and as json is getting used more and more, we should make it 
easier to use it.

Yes people can define their own template, but that adds a barrier to entry for 
new users and leads to people doing things in slightly different ways.

so I think there are two or three json formats we should use.

1. simple json, with a newline after each message (suitable for writing to a 
file, sending to a mmexternal or omprog statment, or sending out to something 
like logstash that things JSON == GOOD, SYSLOG == BAD)

2. something for rsyslog to use when sending structured messages from one system 
to another. This could just be the RFC5424 format with a JSON body, or we could 
have two versions, on with RFC5424 and one with RFC3164. We could do this with 
the cee tag or without, but since cee is a dead project, I think we are better 
off doing just plain json.

Looking in rsconf.c, I see that adding formats exactly the same way a user would 
can be done, as well as referring to C optimized formats. I would guess that 
only the C optimized formats could do something like supporting variables 
overriding default properties.

I'll look at doing a simple pull request for these formats tonight.

David Lang
