### ISSUE TITLE
Allow mmpstructdata to place fields under specific json node

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1262]
Hi

Seems mmpstrucdata it's not working as expected and not exactly as explained in http://www.rsyslog.com/doc/v8-stable/configuration/modules/mmpstrucdata.html

https://github.com/rsyslog/rsyslog/blob/master/plugins/mmpstrucdata/mmpstrucdata.c#L129 shows _jsonRoot_ is initialized NULL, and _rfc5424-sd_ is always used as parent https://github.com/rsyslog/rsyslog/blob/master/plugins/mmpstrucdata/mmpstrucdata.c#L327

Review code to allow nesting structured-data fields under an specified node or as top level fields.

**Comment by mostolog** [comment]
For backward compatibility, default value should be _rfc5424-sd_ 
Set _jsonRoot="foo"_ will nest fields under _foo_ field
Set _jsonRoot=""_ will place fields at top level.

**Comment by mostolog** [comment]
Pending to confirm everything works as expected before updating https://github.com/rsyslog/rsyslog-doc/blob/master/source/configuration/modules/mmpstrucdata.rst

**Comment by davidelang** [comment]
On Wed, 16 Nov 2016, mostolog wrote:
> For backward compatibility, default value should be _rfc5424-sd_
> Set _jsonRoot="foo"_ will nest fields under _foo_ field
> Set _jsonRoot=""_ will place fields at top level.

Yes, that's what I was rying to say :-)

David Lang

**Comment by JPvRiel** [comment]
Just to nudge this along, when I try set `jsonRoot` to something and I fail to understand the nuances of how to set the value, I get this kind of error (v8.36):

```
rsyslogd: internal error:  getJSONRootAndMutex; invalid indicator char ...
```

E.g.
- `!$structured-data` is not permitted as a value. I get this error: "rsyslogd: internal error:  getJSONRootAndMutex; invalid indicator char $(24)"
- And `structured-data` is not permitted: "rsyslogd: internal error:  getJSONRootAndMutex; invalid indicator char s(73)"

So it must start with `!`?

What does work is `!structured-data`. However, instead of directly populating fields in $!structured-data, what it actually does is create `$!structured-data!rfc5424-sd` which for me isn't desired, since I prefer dynamically building into $! the exact field names I want and not needing to explicitly template out a lot of JSON...

Also `jsonRoot` is inconsistent with mmjsonparse's `container` option which in my view is better documented and works as expected.

**Comment by rgerhards** [comment]
I guess it is because you have mistyped the var type - it is ```$!``` instead of ```!$```. I'll have a look at the module ASAP.

**Comment by rgerhards** [comment]
to clarify a bit more ```$``` means it is a variable and ```!``` means it is a message-type variable (vs local...).

**Comment by rgerhards** [comment]
The root issue seems to have been solved via a doc change a while ago. Unfortunately the issue was not closed. I'll do so now, but the new PR will make ```jsonRoot``` behave like expected.

**Comment by JPvRiel** [comment]
> new PR will make jsonRoot behave like expected.

Thanks for the quick fix. When 8.37 get's released, I'll re-try something like `jsonRoot=$!foo` and see if it populates `$!foo!rfc5424-sd` with fields still deeply nested in a sub-element/container `rfc5424-sd` (something I observed before) or if it directly nests structured data fields into just `$!foo` (which is what I'd prefer).

**Comment by davidelang** [comment]
please test this before the release, once we make a release with the fields 
going one place, changing it would break existing configs, which we don't do.

**Comment by JPvRiel** [comment]
> please test this before the release

Okay, I see ubuntu has daily package builds to test with (not for RHEL/CentOS), so I'll need to switch to testing with Ubuntu.

Appreciate the need to retain old config compatibility. If adjusting `jsonRoot` breaks that, perhaps introducing the alternate config keyword `container` (like used in mmjsonparse) is a good workaround (and better overall product config consistanancy). Nonetheless, I'll first double check if `jsonRoot=$!foo` produces `$!foo!rfc5424-sd` or just `$!foo` (which is how I recall `container` worked for mmjsonparse).

**Comment by JPvRiel** [comment]
> I'll first double check if `jsonRoot=$!foo` produces `$!foo!rfc5424-sd` or just `$!foo` (which is how I recall `container` worked for mmjsonparse).

FYI, `jsonRoot=$!foo` does indeed produce `$!foo!rfc5424-sd` with SD elements, not just `$!foo` as I hoped.
