### ISSUE TITLE
lowercasing structured-data SD names

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1338]
Hi

As discussed in http://lists.adiscon.net/pipermail/rsyslog/2016-November/043449.html and after @portante ack on https://github.com/rsyslog/rsyslog/issues/481 I'm opening this to check what's 

According to https://tools.ietf.org/html/rfc5424#section-6.3.2 and 
https://tools.ietf.org/html/rfc5424#section-6.3.3 both are *case-sensitive*.

As stated in 
http://www.rsyslog.com/doc/v8-stable/configuration/modules/mmpstrucdata.html 
: "Note that the case of the RFC5424 parameter names has been converted 
to lower case."
*Why it's being lowercased? *
I can confirm that having a look at: 
https://github.com/rsyslog/rsyslog/blob/master/plugins/mmpstrucdata/mmpstrucdata.c#L219 

Perhaps this is somehow related to 
https://github.com/rsyslog/rsyslog/issues/1116

**Comment by rgerhards** [comment]
Well, this is hard to address. I don't think it is right to make the variable system case-sensitve again. Especially when thinking that everybody depends on the case-sensitivity while nobody is known to use structured data, and especially so with elements that only differ in case.

As an ugly but probably working solution, I think we should add an option that suffixes upper case characters with something that otherwise cannot appear, e.g. "=". So "MY_UPPER" would become "m=y=_u=p=p=e=r=". While ugly, it would preserve case and can reliably by converted back to upper case on output. I also suspect that nobody ever will use that option because the root problem will not occur in practice. And in the remote case it really happens, it can be worked around with the new option.

**Comment by mostolog** [comment]
Anyway, shouldn't we review this topic to diagnose https://github.com/rsyslog/rsyslog/issues/1116 ?

**Comment by rgerhards** [comment]
I don't think this helps. After all, structured data is being converted to lower case since long, so we cannot change this without breaking things. I don't see any other solution than the one I proposed. IMHO #1116 is a different beast (as I understand it, the case-insensitive comparison does not properly work).

**Comment by mostolog** [comment]
Ok. As I'm not using SD anymore, but mmjsonparse+mmnormalize, is up to you to close this ;)
Thanks!

**Comment by rgerhards** [comment]
Well, than I close this. If anyone is actually interested in that functionality, please reply to this thread. If we get sufficient votes, we will consider implementing the workaround.

**Comment by davidelang** [comment]
On Tue, 20 Dec 2016, Rainer Gerhards wrote:

> Well, than I close this. If anyone is actually interested in that functionality, please reply to this thread. If we get sufficient votes, we will consider implementing the workaround.

I think that the correct thing to do is to add an option to specify case 
insensitive operation, off by default since it would break existing configs.

David Lang

**Comment by rgerhards** [comment]
@davidelang: Probably I need to verify this in depth q1/17, but as of my understanding, SD names have **always** been converted to lower case. So what  @mostolog suggests is that we change existing behaviour. The reason is that the RFC specifies it differently, not that anyone ever had problems with the current implementation.

Please correct me if I understand wrong.

**Comment by mostolog** [comment]
You're right, but IMHO specs must be accomplished, and hence this may be a breaking change (ie: case-sesitive enabled by default)
