### ISSUE TITLE
[Regression] Privileges are dropped before reading certs

### ISSUE THREAD

**Issue by cu12** [rsyslog/rsyslog#1352]
We use rsyslog with TLS as a central logging system.

During upgrade from `7.4.4-1ubuntu2.6` to `8.23.0-0adiscon1trusty1`, I noticed that rsyslog starts up, although it's not being able to read the certificates.

```
2017-01-05T11:31:41.002622+00:00 rsyslogd: warning: ~ action is deprecated, consider using the 'stop' statement instead [v8.23.0 try http://www.rsyslog.com/e/2307 ]
2017-01-05T11:31:41.002661+00:00 rsyslogd: imfile: no files configured to be monitored - no input will be gathered [v8.23.0 try http://www.rsyslog.com/e/2212 ]
2017-01-05T11:31:41.002673+00:00 rsyslogd: rsyslogd's groupid changed to 104
2017-01-05T11:31:41.002684+00:00 rsyslogd: rsyslogd's userid changed to 101
2017-01-05T11:31:45.373010+00:00 rsyslogd: can not read file '/etc/ssl/blah.key' [v8.23.0 try http://www.rsyslog.com/e/2040 ]
 ```

```
 ls -la /etc/ssl/blah.key
-r-------- 1 root root 1708 Jul 13  2015 /etc/ssl/blah.key
```

This is working fine with the old version.

This seems to be a regression as rsyslog appears to drop privileges before reading the certificate/key. Any clue?

Configs:
```
$DefaultNetstreamDriver gtls
# certificate files
$DefaultNetstreamDriverCAFile /etc/ssl/blah.ca.pem
$DefaultNetstreamDriverCertFile /etc/ssl/blah.pem
$DefaultNetstreamDriverKeyFile /etc/ssl/blah.key

$ModLoad imtcp

$InputTCPServerStreamDriverAuthMode anon
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode
$InputTCPServerRun 42188 # start up listener at port 42188
```

```
...
$PrivDropToUser syslog
$PrivDropToGroup syslog
$WorkDirectory /var/spool/rsyslog
...
```

**Comment by Whissi** [comment]
Look like we need to move call to `dropPrivileges` in https://github.com/rsyslog/rsyslog/blob/master/runtime/rsconf.c#L863 to the end. Or maybe `gtlsLoadOurCertKey` and or `gtlsInitSession` should fire when we call `tellModulesActivateConfigPrePrivDrop`.

**Comment by davidelang** [comment]
On Fri, 6 Jan 2017, Thomas Deutschmann wrote:

> Look like we need to move call to `dropPrivileges` in 
> https://github.com/rsyslog/rsyslog/blob/master/runtime/rsconf.c#L863 to the 
> end. Or maybe `gtlsLoadOurCertKey` and or `gtlsInitSession` should fire when 
> we call `tellModulesActivateConfigPrePrivDrop`.

I think the problem is that the connection can be established at any time, 
including long after the privs are dropped. So unless rsyslog reads and caches 
all certs that are pointed to, it can run into problems.

I think the right answer is going to be to make a copy of the certs in a 
directory that rsyslog can read after the priv drop.

This isn't the first thing that ends up interacting badly with priv dropping, 
and it won't be the last.

David Lang

**Comment by Whissi** [comment]
I disagree. Isn't the idea of allowing only root to access the keys to ensure that even when rsyslogd gets compromised that the keys are still safe (in the assumption that the attack is unable to extract them from memory)? Well, that's probably the discussion between dropping privileges vs. running in a chroot environment... 

But yes, if the current module maybe initialize more or less on demand, this would require more adjustments.

**Comment by davidelang** [comment]
Inbound connections can happen at any time and you have to be able to validate 
the certs the other side uses (which could require any certs you have access to)

Outbound connections aren't initiated until the first log message is processed 
that needs them, and are re-initialized on HUP. In addition, network conditions 
or destination server issues could cause the connection to be closed.

The system you are connecting to could shutdown for a moment to change their 
cert and you would then potentially need access to any cert to validate the 
connection.

This can't all happen before dropping privs, so you would need to cache the 
certs.

As for the argument that this would prevent someone who compromises rsyslog from 
being able to access the certs, if rsyslog has access to the cert, then someone 
compromising rsyslog can get at them. For the reasons listed above, rsyslog 
cannot establish the connection and then no longer need the cert.

The good news is that almost all the certs required are the public side of the 
cert, which are not supposed to need to be secured, as all they can be used for 
is to validate connections. It's only one cert (the one used to identify the 
rsyslog box) that is of the type that is supposed to be kept secret.

David Lang

**Comment by rgerhards** [comment]
I think @Whissi is right here https://github.com/rsyslog/rsyslog/issues/1352#issuecomment-270933481. I would say we need to read the certs before dropping privileges and *hope* that GnuTLS will keep them in memory so that when a new connection request comes in, no access to the certificate files themselves is required (if GnuTULS requires it, we have lost in any case...).

@PascalWithopf is currently working on openssl support and needs to analyze the gtls subsystem anyways soon. Let's see what he comes up during this review. Maybe it's an easy fix by shuffling just some calls, maybe it requires interface design changes (I honestly do not know right now).

**Comment by rgerhards** [comment]
This should be reviewed as part of the openssl/tls improvement work -- thus moved milestone.
