### ISSUE TITLE
Packaging: RHEL 7 & clones. broken default config

### ISSUE THREAD

**Issue by schlitzered** [rsyslog/rsyslog#1367]
the rsyslog rpm package for RHEL 7 & clones includes a broken default config:

```
rsyslogd -N1
rsyslogd: version 8.23.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: command 'SystemLogSocketName' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.23.0 try http://www.rsyslog.com/e/2222 ]
```

for some wired reason rsyslog is working fine after rebooting, or restarting rsyslog. but it stops logging as soon as logrotate is doing its job.

removing /etc/rsyslog.d/listen.conf solves the issue.

so i suggest that this file is removed from the package for.

**Comment by friedl** [comment]
The listen.conf is not part of the RHEL packages provided by Adiscon. This is part of the originally delivered package that came with the OS.

If you have suggestions on how to remove the file the best way, please share that with us. Since the file is not delivered through the Adiscon package, this might not be an easy task.

**Comment by schlitzered** [comment]
Yes, you are right. my bad.

well, one could do a simple rm to the listen.conf in the post install script. but i think its more or less a problem of the original rsyslog package, that they are not removing the listen.conf

i close the issue

**Comment by guss77** [comment]
@schlitzered , I'd apperciate it if you can comment about how you solved that problem. When I simply remove or comment out the contents of `listen.conf`, rsyslog stops receiving messages from journalds.

My solution was to replace it with the following configuration:
```
input(type="imuxsock" Socket="/run/systemd/journal/syslog")
```
After which rsyslog creates the socket that journald expects and everything works fine.

I've tried to simply load the `imjournal` module, instead of the above, but that didn't do anything.

**Comment by deoren** [comment]
@guss77 If you want to use the imjournal module I believe there is additional configuration needed to specify the state file to use. I'm still new to the setup, so please double-check my feedback to be sure.

## RHEL 7

This is what we have for one of our RHEL 7 boxes (whose config has yet to be converted from the Legacy format):

```
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
```

...

```
# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state
```

If you want to use Rainerscript to configure rsyslog (which I prefer), Fedora has a default `rsyslog.conf` file you can use as a reference for using `imjournal`:

http://pkgs.fedoraproject.org/cgit/rpms/rsyslog.git/tree/rsyslog.conf

## CentOS 7

For CentOS 7, if you'd rather stay away from using the `imjournal` module it appears that you can comment out the entries in the `/etc/rsyslog.d/listen.conf` file and modify your imuxsock module load statement to look something like this:

```
module(
    load="imuxsock"
    ...
    sysSock.Name="/run/systemd/journal/syslog"
    ....
)
```

I don't yet know if `sysSock.Use="on"` is needed (I opened rsyslog/rsyslog-doc#397 to find out), but very light testing seems to indicate it is not.
