### ISSUE TITLE
Feature request: implement Kafka input module. AKA:imkafka

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1389]
[In the beginning](https://www.biblegateway.com/passage/?search=Genesis+1) we decided to deploy ELK, but as Rsyslog seemed to be much faster with a lower memory footprint we decided not to use filebeat/logstash as input for our stack.

When we tried to index into elasticsearch using [omelasticsearch](http://www.rsyslog.com/doc/v8-stable/configuration/modules/omelasticsearch.html) plugin, we discovered our elasticsearch deployment wasn't big enough to index at that speed, so we added kafka (and we'll check later if it's necessary or not).

Now, writing a lot of messages to kafka I was wondering if rsyslog could read from kafka and index into elastic, instead of using logstash, having a super-fast pipeline.

May this issue be a call for people interested in developing an imkafka plugin.

Regards

**Comment by davidelang** [comment]
On Fri, 3 Feb 2017, mostolog wrote:

> [In the beginning](https://www.biblegateway.com/passage/?search=Genesis+1) we 
> decided to deploy ELK, but as Rsyslog seemed to be much faster with a lower 
> memory footprint we decided not to use filebeat/logstash as input for our 
> stack.
>
> When we tried to index into elasticsearch using 
> [omelasticsearch](http://www.rsyslog.com/doc/v8-stable/configuration/modules/omelasticsearch.html) 
> plugin, we discovered our elasticsearch deployment wasn't big enough to index 
> at that speed, so we added kafka (and we'll check later if it's necessary or 
> not).

So you are looking at using kafka to act as a queue for messages going into ES.

Why not just use an action queue in rsyslog on the ES action?

If your ES instance isn't fast enough, going through kafka isn't going to make 
it any faster. Either way you will fall behind and messages will build up in the 
queue at peak times, and when the traffic slows, the queue will drain.

> Now, writing a lot of messages to kafka I was wondering if rsyslog could read 
> from kafka and index into elastic, instead of using logstash, having a 
> super-fast pipeline.

note: I see nothing wrong with having an imkafka, I think rsyslog should be able 
to read from every transport protocol that it can output to (storage protocols 
like ES, postgres, etc do not need to be read from, parly because it's not clear 
how and/or horribly inefficient to read just the new messages)

I just don't think it's the right answer for your situation.

David Lang

> May this issue be a call for people interested in developing an imkafka 
> plugin.
>
> Regards
>
>

**Comment by mostolog** [comment]
> Why not just use an action queue in rsyslog on the ES action?

Among other interesting features Kafka has "consumer groups offsets", which could provide a great system for CI deployment. eg: 
 - While indexer reads messages from channel "apache" I could create newIndexer which also reads messages from "apache" without having an impact on "production pipeline"

Consider the goal is not removing ES but LS.

Thanks for your words, as always ;)

**Comment by otisg** [comment]
Right, throwing in Kafka won't help with faster indexing to ES if ES is the bottleneck (and it can be if not set up well or if under-provisioned, or ...), but Kafka is handy because you can have multiple different consumers reading the same data and doing different things with them, for instance.

How about https://github.com/pyr/unklog to replace that Logstash between K and ES until somebody writes imkafka. 

And if one day you want to replace/outsource ES, you can use [Logsene](http://sematext.com/logsene) - same ES API that omelasticsearch can write to, but without the ES management hassle.

**Comment by rgerhards** [comment]
An initial version of imkafka has been implemented, I just merged it: https://github.com/rsyslog/rsyslog/pull/1558

It's part of 8.27.0. It is experimental and we plan to use the next release cycle to feature-enhance it. We actively look for feedback.
