### ISSUE TITLE
Missing dependencies for ./configure --enable-testbench 

### ISSUE THREAD

**Issue by plaes** [rsyslog/rsyslog#1426]
The `--enable-testbech` configure option has missing dependencies (8.24.0 tarball) as it fails with following build error:
```
make[2]: Entering directory `/root/rsyslog-8.24.0/tests'
  CC       ourtail.o
  CC       nettester.o
  CC       getline.o
  CC       tcpflood-tcpflood.o
  CC       chkseq.o
tcpflood.c:99:21: error: librelp.h: No such file or directory
```
Apparently `--enable-relp` needs to be added explicitly in order to successfully finish build.

**Comment by davidelang** [comment]
The testbench includes tests for a lot of modules, so those modules need to be 
compiled. IIRC there are ways to only compile some tests, but I think it's 
probably easier to just compile everything than go down that route.

**Comment by rgerhards** [comment]
No, it's a bug. Tcpflood does not properly check relp config.

Rainer


Sent from phone, thus brief.

Am 20.02.2017 11:55 schrieb "davidelang" <notifications@github.com>:

The testbench includes tests for a lot of modules, so those modules need to
be
compiled. IIRC there are ways to only compile some tests, but I think it's
probably easier to just compile everything than go down that route.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/1426#issuecomment-281048748>,
or mute
the thread
