### ISSUE TITLE
Rsyslog freezes the box when can't send logs over tcp

### ISSUE THREAD

**Issue by nbommu1** [rsyslog/rsyslog#1507]
Hi,

with ref #1454.

we have figured out when this issue was happening, when tcp logging is inactive for certain period of time rsyslog freezes, this is started happening on dev servers since all prod servers are busy every time. I put a cron job to send test message to loggly every min, things are working as expected, is this some kind bug in rsyslog 5.8.10.

UDP logging works fine but we can't switch to UDP due to some security reasons.

thanks
niranjan

**Comment by davidelang** [comment]
This is expected and desired behavior, If you tell rsyslog not to loose any 
messages, and it can't deliver the messages, all it can do is hang onto them 
until it fills up it's queues, at which point the syslog spec requires that it 
not accept any additional messages until it can deliver something.

you need to either configure the sending system to spill to disk if it can't 
deliver logs for too long, or to throw away logs at some point.

But you really need to track down what's going wrong on the server side that's 
keeping it from processing logs.

If the problem is when the tcp connection is idle for too long, it's probably a 
firewall in your network deciding to cut the connection. But the sending syslog 
server should eventually detect that the connection is dead and reopen it 
(loosing all messages in flight at the time)

the work-around for a broken firewall like this is to make sure you send 
messages frequently enough, the mark feature can do this in rsyslog, but I 
prefer to send something that's actually useful, so I do something like 'vmstat 
60 |logger -t vmstat' which will send one line per minute, containing all the 
vmstat data. Yes, monitoring systems gather some of this data, but almost none 
gather all of it.

David Lang

**Comment by rhessing** [comment]
"If you tell rsyslog not to loose any messages, and it can't deliver the messages, all it can do is hang onto them until it fills up it's queues"

I beg to differ. Basically what you are saying is that your software is more important then the soul reason why the server is being used in the first place. Wrong configuration should cause an application to crash not the entire system to go down or to become unusable. Then at least write some additional code that in the case of not being able to deliver the log messages that it will discard those messages and write a log entry that states something like: "Remote syslog server $server not available, discarding logs".

**Comment by davidelang** [comment]
You misunderstand me.

Rsyslog cannot make assumptions about what you really want, it can only do what 
you tell it to.

If you tell it you don't want to loose any messages, Rsyslog is not going to 
decide that you didn't really mean it and that it should throw away logs. 
Rsyslog is going to believe your instructions.

The syslog spec for writing to /dev/log has no feedback mechanism to tell the 
program that the log is being discarded, it specifies that the write will block 
until the syslog daemon processes it (it actually specifies that it blocks until 
the log is safe on disk, but no syslog daemon does this by default any longer)

So my statement stands.

If you tell rsyslog that you don't want to loose any messages, and it's ability 
to deliver/queue messages runs out, rsyslog will stop processing new messages 
and the services on the system will block

Rsyslog has mechanisms for you to tell it that you want to discard messages 
above a specific severity in this case, but if you don't tell it to do so, it 
will assume that you want to keep all the messages.

What I personally prefer to do is to have the instance of rsyslog on production 
systems deliver logs via UDP to a relay on the same subnet.

This means that if the rsyslog relay/server has a problem, the logs will get 
thrown away and the production systems will not block.

UDP on current switches is very reliable, it's only when you send UDP through 
bottleneck links (routers, firewalls, switch linking ports that are saturated) 
are you going to loose messages

David Lang
