### ISSUE TITLE
test dynstats_prevent_premature_eviction.sh fails on very slow machines

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1519]
This test fails fairly consistently on the very slow new solaris 10 sparc buildbot slave. However, it also fails occasionally on the other testbench machines as well. This looks like there is still some race condition in the test setup. I do **NOT** think that the code itself has a problem.

@janmejay if you have some time, it would be great if you could have a look at it.

I have worked around the really problematic Solaris issue by disabling make check on that slave. This is probably needed in any case, as the salve is so slow it would only permit us to run 10..15 CI tests per day. Once this issue here is solved we can re-think what we do with that slave.

**Comment by janmejay** [comment]
Looked at this one: http://build.rsyslog.com:8010/builders/rsyslog%20solaris10sparc%20rsyslog/builds/510/steps/shell_8/logs/test-suite.log

Basically, randomly hunted for solaris10 sparc failures and found it.

Here is the diagnosis:
This line appears in the post-assert-failure log-dump: 
`2017-04-18T11:56:13.556549+02:00 unstable10s.bo.opencsw.org rsyslogd-pstats: msg_stats: origin=dynstats.bucket foo=2 bar=1 baz=1`

Let us call this flush **k**

It was supposed to be more like:
`foo=1 bar=1`
and then 
`foo=2 baz=1`

Because we injected input_1 set before the flush _k-1_ and injected input_2 (containing one foo and one baz message) just before flush _k_, we expected bar to be evicted (input_1 was the only one that has bar), foo to be retained (since it was added by input_1 and incremented by input_2) and baz to be added (since input_2 had foo and baz).

I suspect the flush _k-1_ happened before input_1 could be processed completely (or may be before it was even injected).
And then input_1 and input_2 were both injected before flush _k_.

Solution is trivial, I just need to space out impstat reporting interval a little (make it 2s perhaps), which will give the test more tolerance.

Shall I do this?

**Comment by rgerhards** [comment]
yes, please do. Once I see the PR, I'll re-enable the slow Solaris slave for testing (it really is too slow to be always kept in the loop). Changing this still makes sense as I see the failure occasionally on the regular salves as well, so it would be good if we can fix this once and forever. Thanks again for your time!

**Comment by janmejay** [comment]
PR increases tolerance to 2 seconds. The valgrind test uses a coordination mechanism (because valgrind slowness was adding to chaos), but I didn't want to add it if unnecessary. Timing based coordination is more "realistic" test.

If it still doesn't stabilize, we can always fallback to what we do in the corresponding valgrind test (with 1 second interval).

**Comment by janmejay** [comment]
The CI failure seems like a env-issue. It wants this package `libqpid-proton3-dev` that it doesn't seem to find.

**Comment by rgerhards** [comment]
The PR looks like it is not based on the current master branch, thus the CI env failures. A rebase should solve those issues.

**Comment by janmejay** [comment]
My bad, fixing it. Didn't pull the correct remote before starting out.

**Comment by rgerhards** [comment]
fixed via https://github.com/rsyslog/rsyslog/pull/1524
