### ISSUE TITLE
rsyslog 8.4.1 keep crashing on CentOS 6.6 

### ISSUE THREAD

**Issue by winchul** [rsyslog/rsyslog#1539]
Hello,

I'd like to get a help on this.
rsyslog 8.4.1 keep crashing on CentOS. Reinstall the rpm didn't help.
When restarting the service, it's crashed within several minutes continuously. 

The user restarted rsyslog at Apr 24 21:10:08 as it was unresponsive for several minutes.

Apr 24 21:07:42 SRIN-HYBRID NwConcentrator[19998]: [SDK-Content] [audit] User admin (session 101206, 107.110.174.21:53647) has requested content for session 9369569544 (channel 117825): failOnCacheMiss=true session=9369569544 maxSize=0

Apr 24 21:10:08 SRIN-HYBRID rsyslogd: [origin software="rsyslogd" swVersion="8.4.1" x-pid="27783" x-info="http://www.rsyslog.com"] start

[rsyslogd -nd.txt](https://github.com/rsyslog/rsyslog/files/969910/rsyslogd.-nd.txt)

Thank you.

**Comment by rgerhards** [comment]
This is a very old version. I think an upgrade to the current one solves the issue. Please re-open if not.

**Comment by davidelang** [comment]
unfortunantly the current version is 8.26, so the codebase you are dealing with 
is several years old at this point.

For community support, you will need to upgrade to a current version. If you 
are unable to do so because of internal policies (usually voiced in terms of the 
'supportability' of versions), then you will need to work with RedHat to solve 
the problem.

David Lang

**Comment by winchul** [comment]
Thank you for the quick reply. I will ask my engineering to review the upgrade.
