### ISSUE TITLE
How does rsyslog parse the syslog coming from Logback(Log4j) ?

### ISSUE THREAD

**Issue by WillaLuo** [rsyslog/rsyslog#1568]
Hi guys,
I have a a Java service running at a server, rsyslog is used for collecting syslog,  but rsyslog can't parse the syslogtag property correctly (always be null).
The format of the syslog generated by Logback framework is here:

appender("SYSLOG", SyslogAppender) {
    syslogHost = "localhost"
    facility = "DAEMON"
    suffixPattern = " [tagname] [%thread]: [%-5level] %logger{36} %X{callId} - %msg%n"
}
syslog example here:
2017-05-17T19:33:43-07:00 0-10-e0-79-c1-5a  [tagname] [DefaultQuartzScheduler_Worker-1]: [INFO ] worker.Scheduler  - Scheduling jobs

Is there any possible that for me to set this property %syslogtag% by hand?
Thanks!!!

**Comment by davidelang** [comment]
On Wed, 17 May 2017, WillaLuo wrote:

> Hi guys,
> I have a a Jave service running at a server, rsyslog is used for collecting syslog,  but rsyslog can't parse the syslogtag property correctly (always be null).
> The format of the syslog generated by Logback framework is here:
>
> appender("SYSLOG", SyslogAppender) {
>    syslogHost = "localhost"
>    facility = "DAEMON"
>    suffixPattern = " [tagname] [%thread]: [%-5level] %logger{36} %X{callId} - %msg%n"
> }
> syslog example here:
> 2017-05-17T19:33:43-07:00 0-10-e0-79-c1-5a  [tagname] [DefaultQuartzScheduler_Worker-1]: [INFO ] worker.Scheduler  - Scheduling jobs

This is not a valid syslog formatted message, which is why this isn't being 
parsed.

a valid syslog message would be (rfc5424)

<165>1 2003-08-24T05:14:15.000003-07:00 192.0.2.1 myproc 8710 - - some message data

or using the older format (rfc3164)

<165>Aug 24 05:14:15 hostname myproc[8710]: some message data

> Is there any possible that for me to set this property %syslogtag% by hand?

you cannot set the syslogtag, but you can set your own variable (say $!syslogtag 
or $.syslogtag) and then use that variable in a template when writing or sending 
the message

remember that you can write a message out using the template RSYSLOG_DebugFormat 
to see exactly what is received and how it is parsed.

David Lang

**Comment by WillaLuo** [comment]
Hi, David 
Thanks for detailed explanation! I will adjust the log format.

Thanks again!
