### ISSUE TITLE
whats the recomended mechanism to rate limit duplicate messages

### ISSUE THREAD

**Issue by Dark-Passenger** [rsyslog/rsyslog#1586]
Hi,

This is just a question bug, I an using rsyslog for logging from iptables and for a certain host I want logs only once for an event not repeatedly for duplicate messages.

Is there any recomended mechanism other than $RepeatedMsgReduction switch.

also -e option wasn't documented anywhere but is supposed to do the same ?

**Comment by davidelang** [comment]
you either need to limit it at the source (can you put in a rule that filters it 
out without logging for that host? Is there some way to track if you've seen 
something that matches that 'recently'? can related/established help this?)

or you need to accept them all and filter them out in your reporting software.

**Comment by Dark-Passenger** [comment]
I am trying to logs with the same message body. Simply put if a rule is hit I want it to long only once (maybe per x seconds but that might be too much). Any way to do this. From what I could find #RepeatMsgReduction and -e are for this purpose exactly.

**Comment by davidelang** [comment]
repeated message reduction only works if there are no other logs in between the 
logs in question. In general we discourage the use of it, because log analysis 
gets confused and can't tell that how many times a message happened (the 
original feature was introduced in an era when people looked at logs manually, 
a couple of decades ago)

Other than #RepeatMsgReduction, rsyslog does not have a way to filter messages 
to only report them every X amount of time based on identical message content. 
given the multi-threaded nature of rsyslog, such a feature would be very failure 
prone (think two threads processing these logs at the same time)

**Comment by Dark-Passenger** [comment]
thanks so rate_limit is the only way to go It seems. Could you please clear up what -e option does. I couldn't find it for  the life of me.

**Comment by rgerhards** [comment]
> thanks so rate_limit is the only way to go It seems. Could you please clear up what -e option does. I couldn't find it for the life of me.

Where did you find info on it? I can't find it in the source code or man page, so it's probably long gone ... and does nothing.

**Comment by rgerhards** [comment]
> I am trying to logs with the same message body. Simply put if a rule is hit I want it to long only once (maybe per x seconds but that might be too much). Any way to do this

Assuming that you can filter on the message body, action.execonlyonce may be useful for you. It is most often used in the context of ommail, but it sounds it would make sense for your use case as well. Have a look at how it is used with ommail:

http://www.rsyslog.com/doc/v8-stable/configuration/modules/ommail.html
