### ISSUE TITLE
At least Centos7 RPM is not honoring SSL settings

### ISSUE THREAD

**Issue by daniel-lucio** [rsyslog/rsyslog#1596]
Using the Mysql output plugin I can not make an SSL conection to Mysql
here it is my setting
module(load="ommysql")

action(type="ommysql"
         server="HOST"
         serverport="3306"
         db="DBNAME"
         uid="DBUSER"
         pwd="DBPASS"
         mysqlconfig.file="/etc/my.cnf"
         mysqlconfig.section="client"
)

my.cnf
[client]
ssl=on
ssl-ca=/etc/pki/tls/cert.pem
ssl-cert=/etc/pki/rsyslog/rsyslog.pem
ssl-key=/etc/pki/rsyslog/rsyslog.key

Turning SSL off works. These settings are functional with the mysql command line command.

**Comment by rgerhards** [comment]
I would suspect that has to do with the distribution MySQL packages. The
code itself does nothing special, and I would assume that's also the case
for the packaging project.

Rainer

Sent from phone, thus brief.

Am 31.05.2017 19:02 schrieb "Luis Daniel Lucio Quiroz" <
notifications@github.com>:

Using the Mysql output plugin I can not make an SSL conection to Mysql
here it is my setting
module(load="ommysql")

action(type="ommysql"
server="HOST"
serverport="3306"
db="DBNAME"
uid="DBUSER"
pwd="DBPASS"
mysqlconfig.file="/etc/my.cnf"
mysqlconfig.section="client"
)

my.cnf
[client]
ssl=on
ssl-ca=/etc/pki/tls/cert.pem
ssl-cert=/etc/pki/rsyslog/rsyslog.pem
ssl-key=/etc/pki/rsyslog/rsyslog.key

Turning SSL off works. These settings are functional with the mysql command
line command.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/1596>, or mute the thread

**Comment by daniel-lucio** [comment]
Maybe, I have read the .c code. But if that is true, the mysql cli client wouldnt be working with SSL enforced, and it is.

**Comment by rgerhards** [comment]
Thanks for opening this issue. Unfortunately, I was hyper-busy with many other things for quite some month and not all issues were properly followed up. I am currently triaging everything.

If this is still of interest for you, can you please post a debug log so that I can see what is going on? Moving to a now-current version would definitely be helpful.
