### ISSUE TITLE
Add Global Setting $umask to RainerScript

### ISSUE THREAD

**Issue by Amorik** [rsyslog/rsyslog#1689]
The global setting '$umask' should be added to the global configuration object options in RainerScript.

**Comment by jay7x** [comment]
I'd like to have following params in global() as well:
- DirCreateMode
- FileCreateMode

**Comment by Amorik** [comment]
@jay7x Those are not global settings, they are file specific for the output module omfile. The omfile module is loaded by default. Its default settings can be "re-loaded" using the module name "builtin:omfile". 

Example:
```
module(
             load="builtin:omfile"
             dirCreateMode="0755"
             fileCreateMode="0640"
)
```
for additional options that can be used see the documentation for omfile.

**Comment by rgerhards** [comment]
Umask is actually global, it affects everything that rsyslog writes.

Rainer

Sent from phone, thus brief.

Am 28.07.2017 14:37 schrieb "Amorik" <notifications@github.com>:

@jay7x <https://github.com/jay7x> Those are not global settings, they are
file specific for the output module omfile. The omfile module is loaded by
default. Its default settings can be "re-loaded" using the module name
"builtin:omfile".

Example:

module(
             load="builtin:omfile"
             dirCreateMode="0755"
             fileCreateMode="0640"
)

for additional options that can be used see the documentation for omfile.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/1689#issuecomment-318640896>,
or mute
the thread

**Comment by rgerhards** [comment]
already present since 8.26.0.
