### ISSUE TITLE
Compilation of 8.29.0 fails in imptcp.c

### ISSUE THREAD

**Issue by Hoshpak** [rsyslog/rsyslog#1719]
While trying to cross-compile rsyslog 8.29.0 using gcc 6.3.0 on Void Linux for the aarch64 architecture, I encountered the following error in imptcp.c:

```
Making all in plugins/imptcp
make[2]: Entering directory '/builddir/rsyslog-8.29.0/plugins/imptcp'
  CC       imptcp_la-imptcp.lo
In file included from ../../runtime/prop.h:25:0,
                 from ../../runtime/glbl.h:38,
                 from ../../runtime/stream.h:73,
                 from ../../runtime/obj.h:48,
                 from ../../runtime/rsyslog.h:634,
                 from imptcp.c:61:
imptcp.c: In function 'AcceptConnReq':
imptcp.c:831:39: error: 'pThis' undeclared (first use in this function)
  STATSCOUNTER_INC(pLstn->ctrSessOpen, pThis->pLstn->mutCtrSessOpen);
                                       ^
../../runtime/atomic.h:206:22: note: in definition of macro 'ATOMIC_INC_uint64'
   pthread_mutex_lock(phlpmut); \
                      ^~~~~~~
imptcp.c:831:2: note: in expansion of macro 'STATSCOUNTER_INC'
  STATSCOUNTER_INC(pLstn->ctrSessOpen, pThis->pLstn->mutCtrSessOpen);
  ^~~~~~~~~~~~~~~~
imptcp.c:831:39: note: each undeclared identifier is reported only once for each function it appears in
  STATSCOUNTER_INC(pLstn->ctrSessOpen, pThis->pLstn->mutCtrSessOpen);
                                       ^
../../runtime/atomic.h:206:22: note: in definition of macro 'ATOMIC_INC_uint64'
   pthread_mutex_lock(phlpmut); \
                      ^~~~~~~
imptcp.c:831:2: note: in expansion of macro 'STATSCOUNTER_INC'
  STATSCOUNTER_INC(pLstn->ctrSessOpen, pThis->pLstn->mutCtrSessOpen);
  ^~~~~~~~~~~~~~~~
make[2]: *** [Makefile:527: imptcp_la-imptcp.lo] Error 1
make[2]: Leaving directory '/builddir/rsyslog-8.29.0/plugins/imptcp'
make[1]: *** [Makefile:815: all-recursive] Error 1
make[1]: Leaving directory '/builddir/rsyslog-8.29.0'
make: *** [Makefile:642: all] Error 2
```

An indeed I couldn't find any definition of pThis in this function. After looking at the structure definitions, I came to the conclusion that the intention could have been to use ```pLstn->mutCtrSessOpen``` instead of ```pThis->pLstn->mutCtrSessOpen``` (changing that at both places in the function at least makes it compile again) though I'm not familiar enough with the rsyslog codebase to judge if that is indeed the case or there should have been a definition of a separate pThis somewhere in the function instead.

**Comment by petiepooo** [comment]
statsobj.h defines STATSCOUNTER_INC at https://github.com/rsyslog/rsyslog/blob/3056a16c07ed14a68a137612f535d8a0e100fcc3/runtime/statsobj.h#L182 with a call to the macro ATOMIC_INC_uint64 at https://github.com/rsyslog/rsyslog/blob/3056a16c07ed14a68a137612f535d8a0e100fcc3/runtime/atomic.h#L205 (if HAVE_ATOMIC_BUILTINS64 is not defined).
Most common architectures, including x86_64 do have atomic builtins for uint64, in which case the second argument (the mutex) is not used and is compiled away (defined at https://github.com/rsyslog/rsyslog/blob/3056a16c07ed14a68a137612f535d8a0e100fcc3/runtime/atomic.h#L196).  However, since aarch64 hardware doesn't, ATOMIC_INC_uint64 resolves to a call that does use the mutex, and that's causing your compilation error.
IOW, I believe you're correct that it should just be pLstn->mutCtrSessOpen without the pThis-> predecessor.  This is likely a copy/paste error and would not be apparent on x86_64, since it does have an atomic uint64 built-ins.  A pull-request correcting lines 831 and 840 for https://github.com/rsyslog/rsyslog/blob/3056a16c07ed14a68a137612f535d8a0e100fcc3/plugins/imptcp/imptcp.c#L831 would be appropriate.

**Comment by zhangjiwang2006** [comment]
make[2]: 离开目录“/opt/rsyslog-src/plugins/imtcp”
Making all in plugins/imudp
make[2]: 进入目录“/opt/rsyslog-src/plugins/imudp”
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..  -I../.. -pthread -I../../runtime -I../.. -I../../grammar  -I/usr/include/libfastjson    -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration     -g -O2 -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -c -o imudp_la-imudp.lo `test -f 'imudp.c' || echo './'`imudp.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../.. -pthread -I../../runtime -I../.. -I../../grammar -I/usr/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -O2 -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -c imudp.c  -fPIC -DPIC -o .libs/imudp_la-imudp.o
imudp.c: In function 'wrkr':
imudp.c:1195:2: error: implicit declaration of function 'prctl' [-Werror=implicit-function-declaration]
  if(prctl(PR_SET_NAME, thrdName, 0, 0, 0) != 0) {
  ^
imudp.c:1188:9: warning: unused variable 'pszDbgHdr' [-Wunused-variable]
  uchar *pszDbgHdr;
         ^
cc1: some warnings being treated as errors
make[2]: *** [imudp_la-imudp.lo] 错误 1
make[2]: 离开目录“/opt/rsyslog-src/plugins/imudp”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/opt/rsyslog-src”
make: *** [all] 错误 2

**Comment by zhangjiwang2006** [comment]
Compilation of 8.34.0 fails in imupd.c

**Comment by zhangjiwang2006** [comment]
using gcc 4.8.5 on Centos7 for the aarch64 architecture

**Comment by rgerhards** [comment]
@zhangjiwang2006 Please do not post to old and resolved issues. 

In regard to your question: you use a pretty old version. Use the current one (8.1910.0) and the problems will go away.
