### ISSUE TITLE
rsyslog runs out of memory in special case

### ISSUE THREAD

**Issue by HangyuTian** [rsyslog/rsyslog#1863]
OOM has occured  on my virtual machine

steps to reproduce：
1.the configuration in /etc/rsyslog.conf: config a remote server 
$WorkDirectory /var/lib/rsyslog
$ActionQueueFileName fwdRule1 # unique name prefix for spool files
$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
$ActionQueueType LinkedList   # run asynchronously
$ActionResumeRetryCount -1    # infinite retries if host is down
*.* @@128.20.211.184:514
(other configuration...)

2.the mount point：
a independent partition is mounted on /var/log and the unused space of /var is less than /var/log

……
/dev/sda3      ext4      4.8G   20M  4.6G   1% /os2
/dev/sda1      ext4      987M   48M  873M   6% /boot
/dev/sda6      ext4      2.0G  6.0M  1.9G   1% /var2
/dev/sda9      ext4      4.8G  544M  4.0G  12% /home
/dev/sda5      ext4      2.0G  1.8G   40M  98% /var
/dev/sda8      ext4      3.9G   25M  3.7G   1% /var/log
……

3. excute the following script

#!/bin/sh

i=0
while :
do
 sleep 0.1
 logger "test-$i:XXXXXXXXXXXXXX......"
 ((i++))
done

4.make the remote server is inaccessible

5.when there are new files in /var/lib/rsyslog（make sure rsyslog is saving the data on disk）,and the total size of these files is less than 1g 
  make /var have no space
  eg: dd if=/dev/zero of=/var/test_file

6.watch the memory of rsyslogd（make sure that the script is still printing log）

Actual results: 
   memory of rsyslogd  increases for  long time （it can finally cause OOM）

the version of rsyslog ：7.4.7，
i have also used rsyslog 8.10 for a test,i saw the same phenomenon.

when the remote server is inaccessible ,on my virtual machine(the client) the data to be  sent to the remote server  is going to be saved in /var/lib/rsyslog/.
but in my machine /var/lib/rsyslog/ will not be written successfully because there is not space left in /var. 

when there is no space in /var , /var/log/ will still have enough space to receive more logs .
it  means that there will still be more and more data needing to be sent to the remote server , 
in this moment the disk space that rsyslog used  is less than 1g （$ActionQueueMaxDiskSpace 1g）.
it  means  that this data will still be saved in /var/lib/rsyslog/ when  the remote server is inaccessible.
however ,there is no space in /var/lib/rsyslog, the data cannot be saved in files.

I have read the source code of rsyslog,the reason of this phenomenon may be as follows：
  rsyslog receive large number of input data and failed to output. the data is still in  memory 

in qAdddisk(),when the return value of CHKiRet(strm.Flush(pThis->tVars.disk.pWrite))  is abnormal, msgDestruct() will not be called
i think this could lead to memory increase.

**Comment by davidelang** [comment]
operating as designed.

Rsyslog has a limit of howmany messages it will keep in memory, if that's larger 
than the memory you have in your system, that's your problem to adjust it.

either give the machine more ram, or configure rsyslog to have a smaller queue 
size.

Rsyslog has no way of knowing that it's about to run the system out of ram, so 
what would you expect it to do to prevent this problem from happening?

David Lang

**Comment by HangyuTian** [comment]
i cannot ensure that there is enough space on disk ,or the ram is enough for use all the time.
and on my machine，large number of logs are printing to the local log files.
so ,i would not like to limit the input of the logs. the logs are useful for me.

what i care about is as follow：
if the following operation is reasonable：
msgDestruct() is called when the return value of CHKiRet(strm.Flush(pThis->tVars.disk.pWrite)) is abnormal in qAdddisk()

if msgDestruct() is called in this situation to drop the data ,will this cause any serious problem ?

**Comment by davidelang** [comment]
On Thu, 19 Oct 2017, HangyuTian wrote:

> i cannot ensure that there is enough space on disk ,or the ram is enough for use all the time.
> and on my machine，large number of logs are printing to the local log files.
> so ,i would not like to limit the input of the logs. the logs are useful for me.

so if you aren't willing to have it throw away any logs (you set retry =-1 after 
all), then you need to shrink the size of the queue so that it doesn't try to 
keep as many logs in memory

> what i care about is as follow：
> if the following operation is reasonable：
> msgDestruct() is called when the return value of CHKiRet(strm.Flush(pThis->tVars.disk.pWrite)) is abnormal in qAdddisk()
>
> if msgDestruct() is called in this situation to drop the data ,will this cause any serious problem ?

it will cause logs to be lost, but you told rsyslog not to loose any logs. It 
would be doing something different than what you as the admin told it to do.

David Lang

**Comment by HangyuTian** [comment]
Because I want to save the logs as many as possible , if I limit the queue size ,will this lead to loose logs easily when the queue is full ?..(I have not test this case yet)
And I have saw the case that when queue is full  ,rayslog will discard messages by the severity of messages.

In another word
on my machine，logs should be printed to local files successfully (i mount a partition at /var/log)
But when the remote server is abnormal,and there is no space on disk ,maybe I can think about the following case:
1. Discard the messages that failed to be sent to remote server (in this case ，logs in local file isn't discarded according to my test results).
2. if there is an operation such as follows
   when disk queue mode is abnormal  ,can rsyslog switch another mode to avoid the failure of writing temporary files when remote server is abnormal. using another way to deal with the process of sending data might avoid the memory increase

**Comment by davidelang** [comment]
On Thu, 19 Oct 2017, HangyuTian wrote:
> Because I want to save the logs as many as possible , if I limit the queue 
> size ,will this lead to loose logs easily when the queue is full ?..(I have 
> not test this case yet)

when the queue is full, things trying to do reliable delivery to the queue will 
block (which can make your service that's logging stop), you can set rsyslog to 
start throwing away logs when the queue is full, and you can even set it to 
start throwing away less critical logs when the queue gets near full (as defined 
by you)

Rsyslog gives you a lot of control of what to do with logs under different 
conditions, changing things so that it always throws away logs under some 
conditions is not something we will do, because not all admins are going to want 
to throw logs away under those conditions :-)

> And I have saw the case that when queue is full  ,rayslog will discard messages by the severity of messages.
>
> In another word
> on my machine，logs should be printed to local files successfully (i mount a partition at /var/log)
> But when the remote server is abnormal,and there is no space on disk ,maybe I can think about the following case:
> 1. Discard the messages that failed to be sent to remote server (in this case ，logs in local file isn't discarded according to my test results).
> 2. if there is an operation such as follows
>   when disk queue mode is abnormal  ,can rsyslog switch another mode to avoid the failure of writing temporary files when remote server is abnormal. using another way to deal with the process of sending data might avoid the memory increase

there are (or can be) many different queues in use, you can set all sorts of 
different parameters to each queue.

you could make a queue for a ruleset that contains all the writes to a local 
disk, and configure that queue to be small, and when it fills up to throw away 
logs. That would let you write logs locally if there is space, but if it can't 
write the logs, it will only queue a small number of them and throw the rest 
away.

The queue for delivery of the logs to a remote system would be a different one, 
and on that one you would set it to do what you want to happen when the remote 
connection goes down.

One thing, when you are starting to do complex things with queues and rulesets, 
you _really_ want to use the new v6+ syntax instead of the legacy syntax.

David Lang
