### ISSUE TITLE
*** Error in `rsyslogd': malloc(): memory corruption: 0x00007f8f4a02a880 ***

### ISSUE THREAD

**Issue by cristifalcas** [rsyslog/rsyslog#194]
I'm getting the error from the title whenever I run rsyslog. Rsyslog doesn't work at all after that.

Debug log here:

http://pastebin.com/E7KSnpCz

Let me know how can I send you the configuration used.

**Comment by cristi1979** [comment]
The fix seems to be "unusual". We have 2 queues in the configuration. If we comment out queue.timeoutshutdown, the error doesn't appear anymore.

**Comment by cristi1979** [comment]
Also, the error doesn't happen under valgrind, so maybe it's a race issue

**Comment by cristi1979** [comment]
About the unusual fix: it doesn't work all the time it seems. Now I've commented queue.workerthreads also to make rsyslog start (on only 1 queue seems to be sufficient).

Other things that make rsyslog start:
## change 
 *.* {
  action( type="omfile" name="omfile_Messages"
   dynaFile="dyn_omfile_MessagesLog" sync="off" )
  stop
 }
## to (remove the condition)
  action( type="omfile" name="omfile_Messages"
   dynaFile="dyn_omfile_MessagesLog" sync="off" )
  stop

Does rsyslog saves some info (some cache) between restarts? Because I found that the errors are random, but after the first appearance I have to tweak the config file somehow to make it work again.

**Comment by cristi1979** [comment]
I have a new configuration now that throws a core dump each time.

Running under valgrind doesn't trigger the bug.

Debug log at http://pastebin.com/Kvqgdx2q
Strace output at http://pastebin.com/3mX4cC1x

**Comment by cristi1979** [comment]
I've uploaded the configurations I used and the corefile from the runs here:

http://www.mediafire.com/download/onj7s6fjlxg6d9a/conf1.zip
http://www.mediafire.com/download/wfmm6vgh32lebvw/conf2.zip

**Comment by cristi1979** [comment]
I had the debug symbols from an older rsyslog version (I don't know if it matters). Here are new corefiles generated with the correct rsyslog-debuginfo package:

http://www.mediafire.com/download/mx0e8uwf175zaif/conf1.zip
http://www.mediafire.com/download/wq8byqqc821ayay/conf2.zip

Core files where generated with info from this site:

http://www.cyberciti.biz/tips/linux-core-dumps.html

Also I've run this script on them and attached the output:

http://en.wikibooks.org/wiki/Linux_Applications_Debugging_Techniques/Core_files#analyze-cores

For the first case (malloc(): memory corruption) I generated the core dump with 

kill -SIGQUIT $(pidof rsyslogd)

**Comment by rgerhards** [comment]
sorry for the long silence. I believe this has been fixed in 8.16.0 (or upcoming 8.17.0), as we did a lot of work in this area. Could you confirm?

I understand that you may no longer be interested, thus I'll close this issue if I don't hear back for some time. Thanks!

**Comment by cristifalcas** [comment]
Since I can't test this anymore, you can close it.
