### ISSUE TITLE
Why the default umask of rsyslogd is decimal 63 ?

### ISSUE THREAD

**Issue by gotnix** [rsyslog/rsyslog#1961]
The [documents](http://www.rsyslog.com/doc/v8-stable/configuration/global/options/rsconf1_umask.html) said:

> The $umask directive allows to specify the rsyslogd processes’ umask. If not specified, the system-provided default is used.

On CentOS, the user root's umask is 0022, normal user's umask is 0002, but i get the rsyslogd's umask via gdb as follow:
```
gdb --batch -ex 'call umask(0)' -ex 'call umask($1)' /sbin/rsyslogd $(cat /var/run/syslogd.pid)
[New LWP 23056]
[New LWP 23050]
[New LWP 23049]
[New LWP 23048]
[Thread debugging using libthread_db enabled]
0x00007f343f49d623 in select () from /lib64/libc.so.6
$1 = 63
$2 = 0
```

My rsyslog.conf without `$umask` directive, why rsyslogd's umask is decimal 63 (octal 0077), and not 0022 or 0002 ?

**Comment by rgerhards** [comment]
This actually smells like a bug, thanks for reporting. I'll have a closer look.

**Comment by rgerhards** [comment]
I have now checked in more depth, but I do not see that the umask is set if not configured (initially thought so, but that was wrong).

In order to troubleshoot this further, I need a debug log from you. The startup phase is sufficient, so you can just start rsyslog, keep it running for a couple of seconds and shut it down again.

Instructions on how to generate the debug log are here: http://www.rsyslog.com/doc/v8-stable/troubleshooting/debug.html#enabling-debug-via-rsyslog-conf

**Comment by rgerhards** [comment]
@gotnix are you still interested in this topic?

**Comment by rgerhards** [comment]
seems to be wolved
