### ISSUE TITLE
rsyslog-kafka on Ubuntu Xenial

### ISSUE THREAD

**Issue by puneetlakhina** [rsyslog/rsyslog#2006]
Hello,

Im trying to install rsyslog and rsyslog-kafka on Ubuntu Xenial (16.04). But I get the following error:

```
The following packages have unmet dependencies:
 rsyslog-kafka : Depends: rsyslog (= 8.28.0~20170614100951-0adiscon1xenial) but 8.31.0~20171108150928-0adiscon1xenial is to be installed
```

It appears that a new version (8.31) of `rsyslog` is present in the ppa but the version of `rsyslog-kafka` is still old (8.28). Im happy to use rsyslog-kafka and rsyslog at version 8.28, but rsyslog 8.28 is not available in the ppa. Any clues on how I can resolve this issue?

Thanks!

**Comment by deoren** [comment]
Confirmed behavior using the v8-devel ppa, also on an Ubuntu 16.04 x64 VM. 

That said, I'm going to guess that you'll be told that your report belongs in the https://github.com/rsyslog/rsyslog-pkg-ubuntu project instead of this one.

Possibly related to rsyslog/rsyslog-pkg-ubuntu#53, rsyslog/rsyslog-pkg-ubuntu#62.

**Comment by puneetlakhina** [comment]
Just want to point out that `apt-get install rsyslog rsyslog-kafka` works fine on the stable ppa. 

On this note, what is the best way to consistently install a specific version of rsyslog, rsyslog-kafka. Im asking in order to make sure we can have reproducible builds. 
In the stable PPA, are the older versions purged periodically?

**Comment by friedl** [comment]
There is no omkafka module for current versions in the daily build branch. The reason is, that we have to statically link to librdkafka, which is currently not possible in the way the daily ppa is built. There actually shouldn't be a rsyslog-kafka version 8.28.0 be available online anymore in the daily ppa, since this was in an older version.

@puneetlakhina I think the best way is to stay on the stable ppa if possible. I understand, this is not possible sometimes. Old versions get purged by Launchpad once a new version is published.

**Comment by rgerhards** [comment]
As I have heard, this seems to be fixed. If not, please report to packaging project.
