### ISSUE TITLE
rsyslog eats 100% cpu if no omelasticsearch server is listening

### ISSUE THREAD

**Issue by julthomas** [rsyslog/rsyslog#2113]
Issue occurs on rsyslog master@289d4ce (friday nov 24), 8.30.0
Issue does not occur on rsyslog 8.29.0

How to reproduce:
* either start rsyslog with no elastic listening, start sending messages before or after rsyslog start
* or stop the elastic server while rsyslog is running and processing messages

Sample configuration with single elastic server and wrong elastic port (nothing listening here):
<pre>
global(net.enableDNS="off")
module(load="imudp")
module(load="omelasticsearch")
input(type="imudp" port="5514" name="net-bsd")

template (name="json" type="list") {
    constant(value="{")
    property(name="timegenerated" dateformat="rfc3339" outname="timegenerated" format="jsonf")
    constant(value=",")
    property(name="hostname" outname="host" format="jsonf")
    constant(value=",")
    property(name="msg" outname="msg" format="jsonf")
    constant(value="}\n")
}

action(
    type="omelasticsearch"
    server="127.0.0.1"
    serverport="9202"
    searchindex="idx"
    template="json"
    bulkmode="on"
    maxbytes="100m"
)

if (1 == 1) then {
    stop
}
</pre>

It is easy to reproduce, I can help testing if needed.

Regards,
Julien

**Comment by rgerhards** [comment]
Thanks for the bug report! I'll see that we craft a testbench test for that (if you are interested in doing that, let me know ;-). Right now, I work on the finishing touches for next Tuesday release, and I am also triaging the large backlog of issues we have. So please bear with me if I am silent the next couple of days.

**Comment by AndyDorman** [comment]
I am not sure this is related and I haven't figured out how to reproduce it reliably, but we may have a similar problem.
We have a cluster of 18 client servers running some heavy duty email security filtering processes that use rsyslog-imrelp to log to a couple of rsyslog hosts.  During periods of peak load (usually caused by disk IO which is our processing choke point) some (not all) of the client servers experience what is described in this ticket...ie, the CPU % rises to or above 100% and the remote logging stops indefinitely. A simple restart of rsyslog on the affected client fixes the problem, sometimes for days, and 4 clients that have much lower loads than the other 14 have never experienced this problem.

These are all debian servers. When this began (Nov 27, a little over 3 weeks ago) all our servers were running 8.29. We have since upgraded all to 8.31 with no change in the problem behavior. We did update all the server the day prior, but there were no rsyslog changes that day and I do not see anything else in the changes logs that could have caused this.

When the problem happens we have no log messages from rsyslog indicating a problem...the CPU % goes up and remote logging just stops.

Our client configs all look like this:
```
# Load our modules
module(load="imuxsock" # provides support for local system logging
       SysSock.RateLimit.Interval="0") # turn off rate limiting
module(load="imklog")   # provides kernel logging support
module(load="omrelp")

# Restrictive ownership on new files
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

# We can now have larger messages
$MaxMessageSize 64k

# Get the PID ourself
$InputUnixListenSocketUsePIDFromSystem on

# Set up our queueing
$WorkDirectory /var/log/queue
$MainMsgQueueType LinkedList
$MainMsgQueueFileName main

# Only include .conf files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

*.* :omrelp:xerxes.ironicdesign.com:20514;RSYSLOG_ForwardFormat
& :omrelp:ulysses.ironicdesign.com:20514;RSYSLOG_ForwardFormat
```

and this is in /etc/rsyslog.d/postfix.conf

```
# Create an additional socket in postfix's chroot in order not to break
# mail logging when rsyslog is restarted.  If the directory is missing,
# rsyslog will silently skip creating the socket.
$AddUnixListenSocket /var/spool/postfix/dev/log
```

So as I said, not sure if this behavior is related to this issue, but I wanted to report it in case it helps track down what is causing this.

**Comment by rgerhards** [comment]
I could confirm the behaviour. It seems to have to do with the suspension of the module, and action-obj support for modules which do not provide their own commit entry point.

**Comment by livelace** [comment]
Bug already is, just need to wait.

**Comment by jsiwrk** [comment]
Not sure this bug has been completely corrected... See [this comment](https://github.com/rsyslog/rsyslog/pull/1992#issuecomment-377002520).
