### ISSUE TITLE
rsyslogd: invalid or yet-unknown config file command 'klogLocalIPIF'

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#2276]
## Original report

Saw this report on the mailing list:

> I have put in
> $ModLoad imklog
> $klogLocalIPIF eth0
> 
> in my rsyslog.conf file (8.30.0) However,
> rsyslogd: invalid or yet-unknown config file command 'klogLocalIPIF' - have you forgotten to load a module? [v8.30.0 try http://www.rsyslog.com/e/3003 ]
> 
> appears when I start. Is there another module besides imklog and imuxsock that I need for this?

## Related documentation

Confirmed option in the [latest stable doc for that module](http://www.rsyslog.com/doc/v8-stable/configuration/modules/imklog.html):

> `$klogLocalIPIF [interface name]`
> If provided, the IP of the specified interface (e.g. “eth0”) shall be used as fromhost-ip for imklog-originating messages. If this directive is not given OR the interface cannot be found (or has no IP address), the default of “127.0.0.1” is used.

## Reproduced issue

I've replicated on:

- Ubuntu 14.04 box with rsyslog 8.31.0 (Adiscon repo)
- CentOS 7 box with rsyslog 8.24.0 (stock version for that box)

## Output from conf test

`root@ubuntu1404-virtual-machine:~# rsyslogd -N6`
```
rsyslogd: version 8.31.0, config validation run (level 6), master config /etc/rsyslog.conf
rsyslogd: invalid or yet-unknown config file command 'klogLocalIPIF' - have you forgotten to load a module? [v8.31.0 try http://www.rsyslog.com/e/3003 ]
```

## Sample conf file

`root@ubuntu1404-virtual-machine:~# cat /etc/rsyslog.conf`
```
$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
$klogLocalIPIF eth0

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction off

$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

$WorkDirectory /var/spool/rsyslog

$IncludeConfig /etc/rsyslog.d/*.conf
```

**Comment by rgerhards** [comment]
confirmed. minimal config:
```
$ModLoad imklog
$klogLocalIPIF eth0
```

**Comment by rgerhards** [comment]
mmmhhh... the module does not at all support such a parameter. I wonder why this is documented...

**Comment by rgerhards** [comment]
This seem to have been present in the past, but been unified, see https://github.com/rsyslog/rsyslog/commit/1d6d534df2368c906a2d80663634b2eef5535ef7

But I need to check if the current state of imklog is actually what it should be. It looks like it uses a hardcoded localhost IP instead of the unified one. Nevertheless, that command seems no longer to exist, so we need to fix doc once we know what exactly happened.

**Comment by rgerhards** [comment]
note to myself: also check imuxsock in this regard

**Comment by rgerhards** [comment]
This definitely looks like some merge or similar went bad in the past...

**Comment by JayTeli** [comment]
invalid or yet-unknown config file command 'InputFileFaility' - have you forgotten to load a module? [v8.24.0 try http://www.rsyslog.com/e/3003 ]

I am getting similar error. i tried to load 
$ModLoad imfile

**Comment by davidelang** [comment]
we would need to see your full config file to begin to guess at what's wrong. 
Please post it here.

David Lang

**Comment by JayTeli** [comment]
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

# Jay added this to write nginx logs to rsyslogs - https://petermolnar.net/log-nginx-to-rsyslog/
$ModLoad imfile


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

**Comment by JayTeli** [comment]
`# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

# Jay added this to write nginx logs to rsyslogs - https://petermolnar.net/log-nginx-to-rsyslog/
$ModLoad imfile


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###
`

**Comment by davidelang** [comment]
klogLocalPIF does not seem to appear in your rsyslog.conf file, is it in an 
included file?

I also see that you have

> $IMJournalStateFile imjournal.state

way down in the file, I don't remember the details of the obsolete config 
perfectly, but I'm pretty sure that you need that before you load the imjournal 
config.

If you are having to use multiple lines to set the config for a module, you 
really should switch to the new syntax so that it's clear what's happening.

David Lang
