### ISSUE TITLE
ppa:adiscon/v8-stable hasn't upgraded to rsyslog-8.32

### ISSUE THREAD

**Issue by Dieken** [rsyslog/rsyslog#2375]
https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable

I'm wondering whether some CI job break and didn't push new packages to launchpad.

**Comment by davidelang** [comment]
in the release announcement they linked to a ubuntu annoucement that there 
were launchpad problems, have those been fixed yet? It will probably take manual 
action to push things at that point.

**Comment by deoren** [comment]
Canonical's launchpad service is down for maintenance:

https://twitter.com/launchpadstatus/status/948688233029881856

From what I heard it is due to applying patches related to the Meltdown/Spectre vulnerabilities, but I do not know for sure. Until that platform is restored, the 8.32.0 builds will remain unavailable. Like you, I am also really looking forward to rolling the update out.

**Comment by Dieken** [comment]
Thank you for your information!

It has been a week after the launchpad status announcement,  so sad,  hope everything come back soon!

**Comment by rgerhards** [comment]
I looks like launchpad is working again - right now, the backlog at says https://launchpad.net/builders it's roughly 31 hours to go. Our builds are somewhere in that backlog ;-)

**Comment by rgerhards** [comment]
@friedl just told me I was somewhat wrong. In the backlog was a support library that we need. After that is through, @friedl needs to submit the actual rsyslog 8.32 packages. Should happen soon.

**Comment by friedl** [comment]
That is correct. Since the Launchpad build environment wasn't available, I could not push the packages for 8.32.0 to build, because I already had a dependency in the queue which needed to be built first. 

The Launchpad buildsystem was re-enabled yesterday, but it had to go through the entire build queue of a week and the dependency was just finished today.

Right now, the builds for 8.32.0 are in the queue and should be finished later today.

**Comment by deoren** [comment]
> @friedl: Right now, the builds for 8.32.0 are in the queue and should be finished later today.

👍

**Comment by deoren** [comment]
Note: Our boxes are offering the update now, so we'll be applying the update to our systems soon. Many thanks to the team for the new version!

**Comment by jendamozna** [comment]
Any idea why theres no rsyslog-mmutf8fix-8.32 in  http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/
?

**Comment by deoren** [comment]
> @jendamozna: Any idea why theres no rsyslog-mmutf8fix-8.32 in http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/

See http://www.rsyslog.com/rsyslog-8-32-0-v8-stable-released/:

> 
> We have also made some major changes to the RHEL/CentOS packages for rsyslog. We are now using a modified spec file from the CentOS base repository for building the EL7 release RPM. We decided to go this way out of several reasons. The major reason was a huge issue with the startup scripts that we used, which did not really work well on EL7 systems. More details are available here: http://www.rsyslog.com/major-centos7-rpm-changes/
> 
> Another reason is, that we wanted to make our own RPMs more similar to those in the base repository to avoid major conflicts in the future. **That also means, that some additional module packages are not available anymore, because they are now included in the base rsyslog package** (mmanon, mmutf8fix, ommail and pmaixforwardedfrom). All other additional sub-packages are still available.

**Comment by rgerhards** [comment]
@friedl I guess this is solved now? Please let us know, I can than close the tracker.

**Comment by friedl** [comment]
From my point of view, this is solved.

**Comment by Dieken** [comment]
It's solved, I have already picked up rsyslog-8.32 from ppa, thank you all!
