### ISSUE TITLE
[Improvement] Omkafka statistics

### ISSUE THREAD

**Issue by ltagliamonte** [rsyslog/rsyslog#2395]
Would be nice to add support for emitting omkafka statistics (json format or statsd) already available [here](https://github.com/edenhill/librdkafka/wiki/Statistics)

**Comment by rgerhards** [comment]
This looks very interesting...

**Comment by rgerhards** [comment]
Milestone is just tentatively

**Comment by davidelang** [comment]
can they be treated the same way as user defined stats in impstats?
k

**Comment by ltagliamonte** [comment]
I think that what is really needed is an interface to expose those metrics, in my use case, for example, I would love to get the lag per partition over statsd.

**Comment by davidelang** [comment]
We have the impstats module that already exposed a lot of internal statistics, 
it makes sense for that to also gather and report the kafka stats (otherwise you 
end up duplicating a lot of the reporting code)

**Comment by rgerhards** [comment]
@davidelang agree on impstats. I think we can probably integrate the librdkafka interface rather easily as it is json. So in the json case we could probably put it into a stats counter more or less unaltered. But I need to investigate, of course. Maybe I do a non-integrated tester first and if that proves to work OK, then go ahead and integrate it (the current milestone is more than full, most importantly because I have a lot of work to do on containers and packages, which is not easily seen from the rsyslog issue tracker alone).

**Comment by rgerhards** [comment]
implement via #2598
