### ISSUE TITLE
Memory leak in stream.c

### ISSUE THREAD

**Issue by covracer** [rsyslog/rsyslog#2421]
Originally observed in the 8.18 but looking like it's still an issue, we think that the malloc at https://github.com/rsyslog/rsyslog/blob/bb6b55a3adbe8e6d34f39d9c162982a5b05f3bd9/runtime/stream.c#L776 does not always have a corresponding free.

Our configuration file is https://github.com/facebook/openbmc/blob/helium/meta-facebook/recipes-extended/rsyslog/files/rsyslog.conf.

We are looking at a patch to address the issue, but it may take some time to re-base it against master, test, and submit a pull request, so I'm filing an issue now to start the discussion.

**Comment by rgerhards** [comment]
Did you try with the current version? Many patches happened since 8.18...

**Comment by wiwAmyChang** [comment]
Hello!
We tried with v8.32.0, too. There is still memory leak.
We use the rsyslog v8.18.0 in OpenBMC but found a critical issue as memory leak.
If we load imfile module, when there is many messages record into the output file via imfile, we found the rsyslog's process memory will increase.

And we found the root cause is rcCStrConstructFromCStr() it allocates a buffer to store listening character, but it did not release the memory after using. This results in BMC leaking memory and rebooting based on healthd remediation.
Provide our solution that first check the pointer of pThis->prevLineSegment is NULL or not before doing rcCStrConstructFromCStr(). If the pointer is not NULL, we will release the memory then continue to allocate a buffer to store listening character.
After our stress test, the memory of this process does not leak.

Could you help review this commit and add this solution in the next version?
https://github.com/facebook/openbmc/commit/46d92d59398ad6f860b36c1324ed2cf2bb2f1bdb
Or do you have any suggestion to fix the memory leak issue?
Thank you!

**Comment by wiwAmyChang** [comment]
Hello @rgerhards ,
Could you help review and reply our question?
Thank you!

**Comment by rgerhards** [comment]
@wiwAmyChang sorry for the delay, I am deep into refactoring imfile. Will check details and then let you know. Gut feeling is that this is a good solution ;-)

**Comment by rgerhards** [comment]
@wiwAmyChang can you describe how this could be reproduced? I would like to build a testbench test for the problem.

**Comment by rgerhards** [comment]
providing one answer to my question with current 8.34 master code: the leak should probably occur each time an incomplete line is read at end of polling. need to see if this is actually not covered with existing tests.

**Comment by rgerhards** [comment]
In at least 8.33 this seems to occur "only" in readmode 0 - the default ;-)

**Comment by rgerhards** [comment]
bug confirmed

**Comment by rgerhards** [comment]
@wiwAmyChang I think your patch will work, but I cannot test as the code base has pretty much diverged since 8.18. So the fix for the current version is different.

**Comment by wiwAmyChang** [comment]
Hi @rgerhards
Sorry for late feedback. About your question,
Q: How this could be reproduced?
A: We load the module "imfile" and set the input file to "mTerm.log," output file to "console.log."
     If there is many data from mTerm.log store into console.log, there is memory leak and cause rsyslog process memory will increase.
     We generate many data in mTerm.log by 'hexdump -C /dev/sda1'.

I saw you help fix and close this issue :) Thank you!
May I know when do you plan to release 8.34.0?

**Comment by rgerhards** [comment]
@wiwAmyChang Thanks for your reply. This matches what I have seen, so I am even more sure the fix will work for you. 8.34.0 is scheduled for 2018-04-03 (side-note: you'll find the next release dates on the top right on http://www.rsyslog.com).

**Comment by wiwAmyChang** [comment]
@rgerhards Got it. Thank you again :D 
We will try again if we get 8.34.0. Thanks :)

**Comment by wiwAmyChang** [comment]
Hello @rgerhards ,
Thank you to fix this memory leak issue.
When we update the rsyslog version to 8.34.0, the memory leak issue is gone :+1: 

But we found there was a situation that we could not receive full log from output file.
So we create another issue for that.
[rsyslog imfile fails to keep record full logs #2679](https://github.com/rsyslog/rsyslog/issues/2679)
Please help track this problem.
Thank you!!!
