### ISSUE TITLE
In the case of wildcard matching, freshStartTail set on will lose the first line of new file data

### ISSUE THREAD

**Issue by xiagujinqiao** [rsyslog/rsyslog#2464]
Hi, In the case of wildcard matching, freshStartTail set on will lose the first line of new file data.

rsyslog version: [8.32.0 ]
platform: [CentOS release 6.5 (Final)]

/etc/rsyslog.conf
```
module(load="imuxsock")
module(load="imklog")
module(load="imfile")
module(load="omkafka")
module(load="mmsequence")
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
*.info;mail.none;authpriv.none;cron.none,local5.none,local1.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
```

/etc/rsyslog.d/pro.conf
```
$MaxMessageSize 32k
$WorkDirectory /data/rsyslogstate
$MainMsgQueueType LinkedList
$MainMsgQueueType LinkedList
$MainMsgQueueFileName local5.info
$MainMsgQueueHighWatermark 24000
$MainMsgQueueLowWatermark 1000
$MainMsgQueueMaxDiskSpace 10g
$MainMsgQueueSize 40000
$MainMsgQueueSaveOnShutdown on
$MainMsgQueueDiscardSeverity 8
$MainMsgQueueDiscardMark 32000
$MainMsgQueueTimeoutEnqueue 300
$MainMsgQueueDequeueBatchSize 1000
$InputFilePersistStateInterval 10
template(name="pro" type="list") {
constant(value="{")
property(name="hostname" format="jsonf" outname="host")
constant(value=",")
property(name="syslogtag" format="jsonf" outname="syslogtag")
constant(value=",")
property(name="msg" position.from="2")
}
ruleset(name="pro") {
if $syslogtag == 'pro' then {
action (
queue.workerthreads="1"
type="omkafka"
topic="pro"
broker=["IP1:9092","IP2:9092","IP3:9092","IP4:9092","IP5:9092"]
template="pro"
partitions.auto="on"
confParam=["compression.codec=snappy","batch.num.messages=10000","queue.buffering.max.messages=10000","message.send.max.retries=1","topic.metadata.refresh.interval.ms=60000","socket.keepalive.enable=true"]
errorfile="/data/rsyslogstate/log_kafka_failures.log"
)
}
}
input(type="imfile" freshStartTail="on" Tag="pro" File="/data/fileCacheBaseDir/sendLogDir/*.send.log" Facility="local5" Severity="info" reopenOnTruncate="on" Ruleset="pro")
```
example:
1.a.send.log does not exist
2.write a row of data, example: echo '{ "id": "jinqiao1"}' >> a.send.log
3.the first line data lost;
4.write one more line, example: echo '{ "id": "jinqiao2"}' >> a.send.log
the "jinqiao2" data collection is successful.

I think, can first determine whether the file exists, if it exists, then use freshStartTail = on, if it is a new file, use freshStartTail = off

**Comment by rgerhards** [comment]
@PascalWithopf can you pls try to reproduce this via a testbench test?

**Comment by PascalWithopf** [comment]
@rgerhards I could reproduce this.

**Comment by PascalWithopf** [comment]
@xiagujinqiao FreshStartTail discards all messages that are already in the file when rsyslog starts. Following happens in your issue.
- rsyslog starts
- input file is created and message is written
- rsyslog finds file and processes it for the first time. It sees that there is already messages written and discards them because it doesn't know if these messages were written before or after the startup.
- messages that are written after this will be processed correctly because they are new from the view of rsyslog.

With https://github.com/rgerhards/rsyslog/commit/99d351d4aa030a9a16bf93ac945dd690730b2ada rsyslog now only applies freshStartTail to files that are already existing during the initial processing of the file monitors.
But the initial startup may take some time depending on the number of files and other factors. If at this time a file is created and messages are written to it, then rsyslog might detect this file and the data will be lost. This is inevitable.
As such it is NOT advised to use this parameter because of the data loss that may occur.

**Comment by xiagujinqiao** [comment]
Whether it is possible to obtain all the current file lists at the time of rsyslog startup, and files not in this list belong to new files? the new files use freshStartTail = off,thanks
