### ISSUE TITLE
relp windowsize between rsyslog 8.27 -> 8.32 non-optimal

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#2481]
### Expected behaviour
Sending from 8.27 instance to 8.32 instance should work as sending from 8.27 instance to 8.27 instance.
### Actual behaviour
Sending from 8.27 to 8.32 via relp seems to cause non-optimal window-size on the sending side.
Flow speed is reduced by magnitude of 6-8 times.
### Steps to reproduce the behaviour
upgrade receiving side to 8.32 from 8.27
### Environment
- rsyslog version: 8.27
- platform: Centos 7.4
- for configuration questions/issues, include rsyslog.conf:
window-size unconfigured on sending side omrelp action.
### Workaround
configuring 128 on sending side omrelp action seems to fix

**Comment by kortemik** [comment]
also note that maxDataSize="256k" or anything (>maxdatasize on the sending side) may be needed on the input in the receiving side even though 128k is on the sending side global. Perhaps there is an off-by-one error somewhere in the chain?

We got: rsp 26 500 error 10047 on connect without it.

**Comment by kortemik** [comment]
cause is propably the sending side maxMessageSize being equal to maxDataSize on receiving side which causes receiver to reject when message of that configured size or larger comes in.

We need to verify this further and then report an exact issue, therefore closing.

**Comment by rgerhards** [comment]
thx - please let us know if you find out more.

**Comment by deoren** [comment]
> @kortemik: cause is propably the sending side maxMessageSize being equal to maxDataSize on receiving side which causes receiver to reject when message of that configured size or larger comes in.
>
> We need to verify this further and then report an exact issue, therefore closing.

On the off-chance that you're running into the same issue that others using RELP for message delivery have encountered, see https://github.com/rsyslog/rsyslog/issues/1782#issuecomment-352027757 and https://github.com/rsyslog/rsyslog/issues/1782#issuecomment-352041870.

When I relied on imrelp to use the global maxMessageSize (by not explicitly configuring maxDataSize) I instead found that imrelp defaulted to 8096. This led to many weeks of frustration until 69661aac9082ce68daafdfe97715917f96b3c93e introduced changes to prove where my issue was originating (though not the root cause).

**Comment by kortemik** [comment]
yes, this was most likely the case!
