### ISSUE TITLE
mmkubernetes: missing configure check for liblognorm

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2595]
liblognorm is used, but not checked in configure.ac

see https://github.com/rsyslog/rsyslog/pull/2593#issuecomment-377277836

**Comment by rgerhards** [comment]
@richm which is the minimum libfastjson version that you need to make mmkubernates work? I'll see that I add a configure check, including the ability to automatically check if we can deliver full capabilities (>= 2.0.3).

**Comment by richm** [comment]
@rgerhards I've been mostly using liblognorm 2.0.2 (RHEL7) - to build with 2.0.2, you have to set -DNO_LOADSAMPLESFROMSTRING=1 in CFLAGS since ln_loadSamplesFromString is only available in 2.0.3 and later. I could not find another way to automatically detect the presence of this function, or the liblognorm version, at compile time. I suppose I should have added an AC_CHECK_FUNC or something like that.

as for libfastjson, I've been using libfastjson-0.99.4 (RHEL7)

**Comment by richm** [comment]
This was fixed as part of https://github.com/rsyslog/rsyslog/pull/2635
please close this issue
