### ISSUE TITLE
queue-persist.sh test sometimes fail

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#262]
The *queue-persist.sh* test randomly fail with
```
FAIL: queue-persist.sh
======================

[queue-persist.sh]:
testing memory queue persisting to disk, mode LinkedList
rsyslogd started with pid  105078
injecting 5000 messages
imdiag[13500]: 5000 messages injected
There must exist some files now:
total 2172
-rw------- 1 portage portage 1048581 Feb  8 16:35 mainq.00000001
-rw------- 1 portage portage 1048581 Feb  8 16:35 mainq.00000002
-rw------- 1 portage portage  111718 Feb  8 16:35 mainq.00000003
-rw------- 1 portage portage     485 Feb  8 16:35 mainq.qi
rsyslogd started with pid  105099
imdiag[13500]: mainqueue empty
read value 15, but expected value 14
sequence error detected
FAIL queue-persist.sh (exit status: 1)
```

Discussion on mailing list: http://thread.gmane.org/gmane.comp.sysutils.rsyslog/16401

**Comment by alorbach** [comment]
FYI: This seems to be a bug in queue processing on shutdown introduced in V8, V7 stable doesn't have this problem.

**Comment by rgerhards** [comment]
Not sure on the "small" label. May be a complex problem during queue shutdown. I have now tracked this issue on several testbench platforms. It may simply be related to testbench timing, but it may also point into a weired condition that can also fail in practice. We should investigate this further under this assumption.

I will also try to disable this test for now, so that we can see if it is the remaining one that causes instability of testbench results.

**Comment by rgerhards** [comment]
relates to: https://github.com/rsyslog/rsyslog/pull/604

**Comment by rgerhards** [comment]
I think I finally found a grip on what is going on here. The good thing is that I am now able to more or less consistenly reproduce within a couple of tries. The bad news is  that this is **not** related to testbench timing, but to queue shutdown, as Andre suggested. So it seems to showcase a real problem, which might cause the loss of exactly one message during queue shutdown when special timing happens. I am further investigating but thought I share the update.
