### ISSUE TITLE
librdkafka1 missing in v8-stable

### ISSUE THREAD

**Issue by hryamzik** [rsyslog/rsyslog#2682]
### Expected behavior

rsyslog-kafka installs fine

### Actual behavior

```
---> Package rsyslog-kafka.x86_64 0:8.26.0-1.el6 will be installed
--> Processing Dependency: librdkafka.so.1()(64bit) for package: rsyslog-kafka-8.26.0-1.el6.x86_64
--> Finished Dependency Resolution
Error: Package: rsyslog-kafka-8.26.0-1.el6.x86_64 (v8-stable)
           Requires: librdkafka.so.1()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

### Steps to reproduce the behavior

```
cd /etc/yum.repos.d/
tee rsyslog.repo<<EOF
[v8-stable]
name=Adiscon CentOS-6 - local packages for \$basearch
baseurl=http://rpms.adiscon.com/v8-stable/epel-6/\$basearch
enabled=1
gpgcheck=0
gpgkey=http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
protect=1
priority=1
EOF

yum install rsyslog-kafka-8.26.0-1.el6
```

### Environment
- platform: Amazon Linux AMI release 2018.03

**Comment by rgerhards** [comment]
The rsyslog version is too old. It has a requirement that no longer exists. As a side-note, kafka would not really work with 8.26, as it had some very serious bugs. So no point at all in trying to obtain an old librdkafka (which BTW had another set of very serious bugs).

**Comment by rgerhards** [comment]
@friedl maybe we should remove the too-old librdkafka packages that we still store?

**Comment by hryamzik** [comment]
Thanks man, we've spend huge amount of time selecting `rsyslog` and `rsyslog-kafka` versions that works with kafka in a stable way.

**Comment by rgerhards** [comment]
well, if you thin 8.26 was stable, happy message loss ;-) I know, because I made the design error that caused that message loss. A quick glimpse on kafka inside the ChangeLog also reveals many, often serious, problems that were fixed in later release.  So you "huge amount of time" was actually ill-spent.

**Comment by friedl** [comment]
The rsyslog-kafka packages for pre-8.28.0 versions are gone for good now. With 8.28.0 the refactored omkafka module was introduced, including static linking to librdkafka in the RPMs we provide. 

For using any of the Kafka modules, it is recommended to use the latest version of rsyslog (8.34.0) because it has all the fixes that are currently available and uses the most recent librdkafka library.
