### ISSUE TITLE
omprog: stdout/stderr of child process assigned unpredictably

### ISSUE THREAD

**Issue by lego12239** [rsyslog/rsyslog#2787]
Hi!

A strange behaviour with outputing to stderr from program started by omprog module.
A program code:
```
#include <syslog.h>
#include <stdio.h>
int
main(int argc, char **argv)
{
	fprintf(stderr, "String ERR1");
	syslog(LOG_ERR, "String ERR2");
	fprintf(stderr, "String ERR3");
	return 0;
}
```
### Expected behavior
See in log:
```
Jun 21 17:45:17 legohost prog: String ERR1
Jun 21 17:45:17 legohost prog: String ERR2
Jun 21 17:45:17 legohost prog: String ERR3
```
or
```
Jun 21 17:45:17 legohost prog: String ERR2
```

### Actual behavior
```
Jun 21 17:45:17 legohost prog: String ERR2
Jun 21 17:45:17 legohost ring ERR3
```

### Steps to reproduce the behavior
Compile specified earlier source code and place in rsyslogd conf something like this:
```
       if ($syslogfacility-text == "auth") then {
               action(type="omprog" binary="/home/user/work/prog/prog")
       }
```
and then execute:
```
logger  -p auth.info test
```

### Environment
- rsyslog version: 8.34.0
- platform: funtoo stable

**Comment by rgerhards** [comment]
I am not sure what you are trying to do. omprog is meant to receive messages and then process them. Actually, stderr should not go to the log at all. I see that you give this also as a correct scenario. Is rsyslog started via systemd? If so, systemd and the journal may play an important role here.

In any case, please use the ``output`` parameter and let's see how this changes things. Full doc at https://www.rsyslog.com/doc/v8-stable/configuration/modules/omprog.html

**Comment by lego12239** [comment]
> omprog is meant to receive messages and then process them. 

This is exactly what my program do :-). But i'm detect the strange behaviour of debug outputing and now just try to find the reason.

> Actually, stderr should not go to the log at all. I see that you give this also as a correct scenario. 

I'm not sure what is a correct scenario :-). I just try to find a logic in what i see :-). If you say that stderr should not go to the log at all, then the only possible correct scenario is:

```
Jun 21 17:45:17 legohost prog: String ERR2
```

But i see:

```
Jun 21 17:45:17 legohost prog: String ERR2
Jun 21 17:45:17 legohost ring ERR3
```

And this is break my mind. Because in addition to the fact that i mustn't see ERR3 message, the message i see is cut.

> Is rsyslog started via systemd?

Via openrc.

With output parameter i see in log just "String ERR2". And in output file:

```
String ERR1
String ERR3
```

So it seems that this is openrc issue.
When i use output parameter FDs are looks like (6157 - rsyslog, 7300 - my_prog):
```
 ~ # ls /proc/6157/fd/ -l
total 0
lrwx------ 1 root root 64 Jul  2 11:40 0 -> socket:[105437]
lrwx------ 1 root root 64 Jul  2 11:40 1 -> socket:[105448]
lr-x------ 1 root root 64 Jul  2 11:40 11 -> pipe:[108057]
l-wx------ 1 root root 64 Jul  2 11:40 2 -> /var/log/messages
lrwx------ 1 root root 64 Jul  2 11:40 3 -> socket:[105439]
lr-x------ 1 root root 64 Jul  2 11:40 4 -> /proc/kmsg
l-wx------ 1 root root 64 Jul  2 11:40 5 -> /var/log/auth.log
l-wx------ 1 root root 64 Jul  2 11:40 7 -> /var/log/user.log
l-wx------ 1 root root 64 Jul  2 11:40 8 -> pipe:[108055]
~ # ls /proc/7300/fd/ -l
total 0
lr-x------ 1 root root 64 Jul  2 11:40 0 -> pipe:[108055]
l-wx------ 1 root root 64 Jul  2 11:40 1 -> pipe:[108057]
l-wx------ 1 root root 64 Jul  2 11:40 2 -> pipe:[108057]
lrwx------ 1 root root 64 Jul  2 11:40 3 -> socket:[111693]
```

0, 1 and 2 FD are used for pipes and 3 FD for syslog - all ok.
Without output parameter(10288 - rsyslog, 10470 - my_prog):
```
 ~ # ls /proc/10288/fd/ -l
total 0
lrwx------ 1 root root 64 Jul  2 11:43 0 -> socket:[112020]
lrwx------ 1 root root 64 Jul  2 11:43 1 -> socket:[112026]
l-wx------ 1 root root 64 Jul  2 11:43 2 -> /var/log/messages
lrwx------ 1 root root 64 Jul  2 11:43 3 -> socket:[112022]
lr-x------ 1 root root 64 Jul  2 11:43 4 -> /proc/kmsg
l-wx------ 1 root root 64 Jul  2 11:43 5 -> /var/log/auth.log
l-wx------ 1 root root 64 Jul  2 11:43 6 -> pipe:[111154]
l-wx------ 1 root root 64 Jul  2 11:43 7 -> /var/log/user.log
l-wx------ 1 root root 64 Jul  2 11:43 8 -> /var/log/kern.log
 ~ # ls /proc/10470/fd/ -l
total 0
lr-x------ 1 root root 64 Jul  2 11:43 0 -> pipe:[111154]
lrwx------ 1 root root 64 Jul  2 11:43 1 -> socket:[112026]
lrwx------ 1 root root 64 Jul  2 11:43 2 -> socket:[113032]
```

**Comment by rgerhards** [comment]
@jsiwrk do you have an explanation?

**Comment by jsiwrk** [comment]
When the `output` parameter is NOT specified, omprog does not capture the stdout or stderr of the program. Also, it [does NOT close](https://github.com/rsyslog/rsyslog/blob/v8.34.0/plugins/omprog/omprog.c#L170) the stdout/stderr FDs, so these are inherited from the parent process (rsyslogd). Therefore, if the program prints to stdout/stderr, the data will be send to the destination these FDs are attached in rsyslogd. Being rsyslogd a daemon, I imagine these are unpredictable (?). So this seems something to be reviewed. Maybe omprog should redirect stdout/stderr to /dev/null when spawning the child...?

In this case, however, something else is going on: note that the stderr of the child is connected to a socket not inherited from rsyslogd. I believe this is the socket opened by the 'syslog' call inside the program. I imagine this can explain the message truncation: stderr is sending plain characters to the syslog socket, not conforming to the syslog protocol (?).

How could stderr have been redirected to the syslog socket? As mentioned, omprog does not close this FD, so it should have been inherited from rsyslogd (?!). But... what if rsyslogd didn't have stdout/stderr opened at the moment the child was forked? (something normal for a daemon). When omprog creates the pipe(s) to communicate with the child process, the pipe in/out FDs will be assigned to the lowest FD, which is stdout/stderr in this case. Then, after the fork, the child process will [close the pipe ends that it does not need](https://github.com/rsyslog/rsyslog/blob/v8.34.0/plugins/omprog/omprog.c#L162-L163), and this in turn will cause stdout and/or stderr to be closed. Later, when the program calls 'syslog', the opened socket is assigned again to the lowest FD available, which is stdout/stderr... And this is how the child can end up with stdout/stderr redirected to something it doesn't expect, as has apparently happened in this case.

(Note that, for this to happen, rsyslogd has to have stdout/stderr unassigned when omprog spawns the child. This, in turn, could depend on how rsyslogd has been started (systemd, openrc...), I suppose.)

In any case, it seems that something needs definitely to be reviewed about how omprog transmits stdout/stderr to the child when these streams aren't captured. Because the current behaviour is apparently unpredictable...

@rgerhards, what do you think?

**Comment by lego12239** [comment]
> Maybe omprog should redirect stdout/stderr to /dev/null when spawning the child...?

For my case and from my point of view this would be fine. Thus, stderr messages willn't go to syslog socket.

jsiwrk, thank you for the explanation!

**Comment by lego12239** [comment]
So, i should close the issue on openrc page.
