### ISSUE TITLE
Rsyslog not clearing drained queue files

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#2814]
### Expected behavior
Rsyslog deletes saved.to-disk queue files after draining them
### Actual behavior
Queue files are left on this until rsyslog restart
### Steps to reproduce the behavior
* Configure remote endpoint with DA queues and `queue.saveOnShutdown="on"`
* disable connection to remote, log data, shut down rsyslog
* verify queue files are there, make remote available, start rsyslog again
* verify that data got sent however queue files remain (and eat up space) until restart
### Environment
- rsyslog version:8.36.0 
- platform:Fedora 27
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
It's expected behavior if one file is kept open (plus  .qi file, depending on config): https://rainer.gerhards.net/2013/07/rsyslog-why-disk-assisted-queues-keep-a-file-open.html

If more than one file is kept open that sounds like queue inconsistencies. But these should not go away on shutdown and will possibly also be logged on startup (depending on circumstances).

**Comment by jvymazal** [comment]
Ok, that is solved then, will have to bookmark the blogpost. Many thanks for taking time to answer.
