### ISSUE TITLE
Log child process reaping if processes terminated abnormally or with non-zero exit code

### ISSUE THREAD

**Issue by gjmilne** [rsyslog/rsyslog#3281]
### Desired behavior
Informational logging of reaped child process should be supressed if the process exited normally with an exit code of zero.

### Actual behavior
All reaped child process exits are logged irrespective of whether the process died unexpectedly or exited with a non-zero error code.

### Steps to reproduce the behavior
Create a rotation script that is invoked once a log file reaches some arbitrary size (e.g. 10000 bytes). Create a logging rule to invoke the rotation script. Once the file is rotated, a "Child XXX has terminated, reaped by main-loop" will be shown in the new log file.

### Environment
```
rsyslogd 8.37.0, compiled with:
	PLATFORM:				arm-tait-linux-gnueabi
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	No
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				No
	systemd support:			No
	Number of Bits in RainerScript integers: 64
```
The platform is a custom OpenEmbedded platform.

## Suggested implementation
Modify the mainloop function to supply a pointer to a status variable in the call to waitpid()  and examine its value on return. Only log a message if:
* `WIFEXITED(status)` returns `false`, or
* `WEXITSTATUS(status)` returns a non-zero value.

**Comment by jsiwrk** [comment]
As far as I remember this log message was already there when I modified the related code. The proposal seems OK to me.

**Comment by janmejay** [comment]
My rational was that process death in a event processing pipeline is a
significant event. At high throughput deaths of child process can cause
serious degradation (even if replacement processes are launched).

The aim was to let the user (of ompipe or omprog) know that something
unusual has happened. But child can unfortunately be reaped by main thd
too, so while reaping we aren't sure if death is a significant event.

So we err on the side of caution and log it.

**Comment by gjmilne** [comment]
I raised this issue based on my use case:
> we rotate log files every 600,000 bytes. It's an embedded system. We find it annoying that we get one of these messages at the top of newest log file after the rotation script finishes. It isn't helpful to us, nor our users. We end up with around 50 of these log files in our rotation pool and every one of them, except for the very first, has one of these reaping messages as its first line.  When that first file is finally rotated away, all 50 log files have one of these messages at the top of the file.

It is _normal_ for a rotation script to end. My rotation script always exits normally with an exit code of 0. Why log what is expected to happen?

My conf around this looks as follows:
```
$outchannel rss_rotate,/var/log/tbc_all/rss.log, 600000,/usr/bin/rss_rotate.sh
```

I do not understand the internals of the rsyslog architecture so I don't know what causes the main loop to reap the child process as opposed to being reaped in the event pipeline. However, the reaping message is not very useful since it only tells me the pid of the process that just died. I would like to know the process name (and any args) in addition to the pid. In a real-world case, it might take a long time to pin down which command/script is the source of any problem.

However, I would prefer that normally exiting processes (i.e. WIFEXITED true, and WEXITSTATUS 0) did not log a "Child XXX has terminated" message.

**Comment by janmejay** [comment]
How about we make it conditional and have it logging as a default?

It'll catch attention and probably save someone a few hours of painful
debugging (one notices these things by chance right? So to be useful they
need to be enabled by default).

One can easily turn it off once convinced its calling out a false positive.

On 14-Nov-2018 4:03 AM, "Gordon Milne" <notifications@github.com> wrote:

I raised this issue based on my use case:

we rotate log files every 600,000 bytes. It's an embedded system. We find
it annoying that we get one of these messages at the top of newest log file
after the rotation script finishes. It isn't helpful to us, nor our users.
We end up with around 50 of these log files in our rotation pool and every
one of them, except for the very first, has one of these reaping messages
as its first line. When that first file is finally rotated away, all 50 log
files have one of these messages at the top of the file.

It is *normal* for a rotation script to end. My rotation script always
exits normally with an exit code of 0. Why log what is expected to happen?

My conf around this looks as follows:

$outchannel rss_rotate,/var/log/tbc_all/rss.log, 600000,/usr/bin/rss_rotate.sh

I do not understand the internals of the rsyslog architecture so I don't
know what causes the main loop to reap the child process as opposed to
being reaped in the event pipeline. However, the reaping message is not
very useful since it only tells me the pid of the process that just died. I
would like to know the process name (and any args) in addition to the pid.
In a real-world case, it might take a long time to pin down which
command/script is the source of any problem.

However, I would prefer that normally exiting processes (i.e. WIFEXITED
true, and WEXITSTATUS 0) did not log a "Child XXX has terminated" message.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/3281#issuecomment-438464201>,
or mute
the thread

**Comment by gjmilne** [comment]
I would prefer the default to be no logging and a config value that allows it to be enabled.

If we decide to go down the config route, I suggest we avoid a simple binary log/don't-log and opt for the following set of options:
1. do not log
1. log abnormal and/or non-zero exit codes (the default)
1. log all exits

**Comment by davidelang** [comment]
On Wed, 14 Nov 2018, Gordon Milne wrote:

> I would prefer the default to be no logging and a config value that allows it to be enabled.

what is the backwards compatible result? If this is a new thing that just 
started with a new version, we may have more flexibility than if it's something 
that has had consistant results over a long time.

> If we decide to go down the config route, I suggest we avoid a simple binary log/don't-log and opt for the following set of options:
> 1. do not log
> 1. log abnormal and/or non-zero exit codes (the default)
> 1. log all exits

With the possible exception of the default, this sounds like a good set of 
options to have.

David Lang

**Comment by gjmilne** [comment]
The backward compatible behaviour for previous releases is log everything

However, I was previously using 6.3.7 on an embedded product and the world has moved on since then. Our product is now on 8.37.0. Upgrading to 8.37.0 put one of these "child XXX has terminated" message into each file in our pool of (approx. 50) log files.

I am happy with leaving the default as whatever the 8.36.x release did. However, I would like the ability to disable all logging as well as disable logging of normal exits.

**Comment by davidelang** [comment]
On Wed, 14 Nov 2018, Gordon Milne wrote:

> The backward compatible behaviour for previous releases is log everything

then we probably need to do that (even though I agree that the nicest default 
would be only to log non-zero exit codes)

> However, I was previously using 6.3.7 on an embedded product and the world has moved on since then. Our product is now on 8.37.0. Upgrading to 8.37.0 put one of these "child XXX has terminated" message into each file in our pool of (approx. 50) log files.
>
> I am happy with leaving the default as whatever the 8.36.x release did. However, I would like the ability to disable all logging as well as disable logging of normal exits.

You can always setup a rule at the top of your config something like:

if $msg contains "child" and $msg contains "has terminated" then stop

and it will drop all these messages (personally, I would add them to a counter, 
per "artificial ignornace", the number of times that a non-interesting log 
happens can be interesting.

David Lang

**Comment by gjmilne** [comment]
Our product code has its own child process and it reports when they
terminate abnormally so II don't want to go down the "rule" approach since
it thne becomes yet-another-check we have to do at code review to make sure
all our messages get logged.

The 3-way config is, I feel, the best option going forward.

**Comment by davidelang** [comment]
On Wed, 14 Nov 2018, Gordon Milne wrote:

> The 3-way config is, I feel, the best option going forward.

no disagreement with that, just pointing out the other option.

David Lang

**Comment by jsiwrk** [comment]
Please see the referenced PR.
