### ISSUE TITLE
"action '(null)' resumed" messages with 7.6.0

### ISSUE THREAD

**Issue by schplat** [rsyslog/rsyslog#35]
I just recently updated to 7.6.0 from 7.4.9.

Every time I sudo a command, /var/log/messages gets the following added to it:

Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd0: action '(null)' resumed [try http://www.rsyslog.com/e/0 ]
Feb 15 01:03:13 cray rsyslogd-3003: action '(null)' suspended, next retry is Sat Feb 15 01:03:43 2014 [try http://www.rsyslog.com/e/3003 ]

**Comment by rippler** [comment]
Same problem with v8.4.2-1

```
Jun 22 06:15:01 raspberrypi rsyslogd-2007: action 'action 18' suspended, next retry is Mon Jun 22 06:16:31 2015 [try http://www.rsyslog.com/e/2007 ]
Jun 22 06:17:01 raspberrypi rsyslogd-2007: action 'action 18' suspended, next retry is Mon Jun 22 06:18:31 2015 [try http://www.rsyslog.com/e/2007 ]
```
Config file:
```
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/spool/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/syslog
daemon.*                        -/var/log/daemon.log
kern.*                          -/var/log/kern.log
lpr.*                           -/var/log/lpr.log
mail.*                          -/var/log/mail.log
user.*                          -/var/log/user.log
mail.info                       -/var/log/mail.info
mail.warn                       -/var/log/mail.warn
mail.err                        /var/log/mail.err
news.crit                       /var/log/news/news.crit
news.err                        /var/log/news/news.err
news.notice                     -/var/log/news/news.notice

*.=debug;\
        auth,authpriv.none;\
        news.none;mail.none     -/var/log/debug
*.=info;*.=notice;*.=warn;\
        auth,authpriv.none;\
        cron,daemon.none;\
        mail,news.none          -/var/log/messages
*.emerg                         :omusrmsg:*
daemon.*;mail.*;\
        news.err;\
        *.=debug;*.=info;\
        *.=notice;*.=warn       |/dev/xconsole
```

**Comment by Darkhand81** [comment]
Also getting this error in v8.4.2-1 on a default Debian Jessie install on an Odroid XU4.

```
Nov 23 14:05:58 odroid rsyslogd-2007: action 'action 17' suspended, next retry is Mon Nov 23 14:06:28 2015 [try http://www.rsyslog.com/e/2007 ]
Nov 23 14:06:28 odroid rsyslogd-2007: action 'action 17' suspended, next retry is Mon Nov 23 14:06:58 2015 [try http://www.rsyslog.com/e/2007 ]
Nov 23 14:07:35 odroid rsyslogd-2007: action 'action 17' suspended, next retry is Mon Nov 23 14:08:05 2015 [try http://www.rsyslog.com/e/2007 ]
```

Config: http://pastebin.com/idSi7337

**Comment by rgerhards** [comment]
either start xconsole or remove writing to the xconsole pipe in rsyslog. I think it's name is /dev/xconsole, search for it in rsyslog.conf and delete that line.

Note that rsyslog works correctly, as you tell it to write to some location and rsyslog tells you it can't.

**Comment by Darkhand81** [comment]
Thank you for the help :)  It's a configuration issue with the distro then, nothing wrong with rsyslog.  Commented out the offending lines with much success.  Thanks!

**Comment by vinceskahan** [comment]
raspbian 8.3.0 latest on a raspi3 still has this issue - fix works there too.

**Comment by DanTup** [comment]
Since sometime this morning, I'm seeing this on my Pi (Raspbian Lite, latest version):

[code]
Apr  2 01:23:51 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:24:21 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:29:41 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:30:11 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:31:35 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:32:05 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:35:52 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:36:22 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:39:06 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:40:06 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:44:39 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:45:39 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:53:08 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 01:54:08 2016 [try http://www.rsyslog.com/e/2007 ]
Apr  2 01:59:41 raspberrypi rsyslogd-2007: action 'action 17' suspended, next retry is Sat Apr  2 02:00:41 2016 [try http://www.rsyslog.com/e/2007 ]
[/code]

In the (default) config, it has this at the bottom:

[code]
# The named pipe /dev/xconsole is for the `xconsole' utility.  To use it,
# you must invoke `xconsole' with the `-file' option:
# 
#    $ xconsole -file /dev/xconsole [...]
#
# NOTE: adjust the list below, or you'll go crazy if you have a reasonably
#      busy site..
#
daemon.*;mail.*;\
    news.err;\
    *.=debug;*.=info;\
    *.=notice;*.=warn   |/dev/xconsole
[/code]

So I figure if I remove that chunk at the bottom this will stop, however I wanted to understand rather than just do! So could anyone explain:

1. Why the default install of Raspbian is doing something that seems to just fill syslog with junk? Is this something that should be changed in their default config?
2. Whether this means something has failed and removing this will just mean it "silently" fails? This doesn't seem to have been happening forever, it just started around midnight last night (as far as I can see); I set the Pi up a few days ago.

**Comment by XECDesign** [comment]
Does it go away if you install x11-apps?

**Comment by DanTup** [comment]
@rgerhards Any ideas about this?

RPi suggest they just have the same config as Debian, and Debian [suggest it's an rsyslog issue](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742113).

**Comment by rgerhards** [comment]
It's long fixed, there was a problem with old versions. Note that when you
write to a pipe where no one is listening, some error notifications will
still occur (simply because errors actually occur - it is pointless to
write to a pipe that nobody reads...).

Hth
Rainer

Sent from phone, thus brief.
Am 22.04.2016 20:59 schrieb "Danny Tuppeny" <notifications@github.com>:

**Comment by DanTup** [comment]
In https://github.com/RPi-Distro/repo/issues/28#issuecomment-213551334, @XECDesign said "xconsole is installed, and on all installs /dev/xconsole is present, so I am not sure what that would have to do with it"

Is there anything I can do to debug further?

**Comment by rgerhards** [comment]
Side note: that's also all in the Debian bug you quote ;)

**Comment by rgerhards** [comment]
I suggest to open a bug with Debian.

Sent from phone, thus brief.
Am 22.04.2016 21:06 schrieb "Danny Tuppeny" <notifications@github.com>:

**Comment by DanTup** [comment]
Ok, I'll give that a go (if I can find out where) and see where I get.

Thanks for the responses!

**Comment by DanTup** [comment]
Ugh, I gave up. I started reading about how to report a bug in Debian and it seems rather complicated, having to format emails in specific machine-parseable ways (and given I don't really understand what I'm reporting, I'm not sure I can comply!).

I even tried to install their bugreporting tool, which then wanted to bring a bunch of dependencies just so it could format an email, so I bailed...

![debian](https://cloud.githubusercontent.com/assets/1078012/14752694/b7c9d96e-08c8-11e6-8c38-215f9f40b98a.png)

I think I'll just go comment those lines out of the config instead! :-/

**Comment by davidelang** [comment]
the era of spitting logs out to a console and having someone see them is long over.

how many people ever open an xconsole window to see it? And if they did, would they really notice anything real among the noise there?

**Comment by mbiebl** [comment]
Fwiw:
https://anonscm.debian.org/cgit/collab-maint/rsyslog.git/commit/?id=67bc8e5326b0d3564c7e2153dede25f9690e6839

I'm not sure if Ubuntu has merged this change.
At least there is no point in filing a bug againt the Debian package, since there is nothing to fix, really.

**Comment by XECDesign** [comment]
@mbiebl Looks like you're right. The fix didn't quite make it into Jessie. Thanks.

**Comment by vinceskahan** [comment]
yes, ubuntu xenial64 for vagrant 'does' have the fix.
debian jessie does not currnetly.

just checked....
​

**Comment by DanTup** [comment]
Forgive my noobishness; does this mean it's already fixed in an upcoming version of Debian (and therefore, Raspbian)?

**Comment by XECDesign** [comment]
@DanTup Yes and no. Debian have already fixed it, but  not in the 'stable' release (currently Jessie). Debian doesn't poke the stable release unless there are security issues to be addressed. I'd recommend just taking the relevant lines out yourself, because it will probably be at least a year before we move from Jessie.

**Comment by DanTup** [comment]
@XECDesign I meant in Stretch rather than Jessie, but didn't know how far away it'd be. I'll remove them manually for now and add to my setup script.

Thanks all for helping get to the bottom of this; it's been bugging me! :D

**Comment by mbiebl** [comment]
In stretch the line is already gone.
