### ISSUE TITLE
how to automatically bind cpu core in rsyslog multiple threading

### ISSUE THREAD

**Issue by hxwang1024** [rsyslog/rsyslog#3523]
how to automatically bind cpu core in rsyslog multiple threading

**Comment by davidelang** [comment]
Rsyslog does not offer any config options to bind threads to cores, you should 
be very careful in configuring multiple threads in the config, it will actually 
slow down performance under lighter loads, and since rsyslog can handle very 
high loads, most organizations loads end up being 'light'

David Lang

**Comment by rgerhards** [comment]
> how to automatically bind cpu core in rsyslog multiple threading

if you really want to, you can do this via systemd `CPUAffinity`. See e.g. here: https://www.redhat.com/files/summit/session-assets/2017/S103870-Demystifying-systemd.pdf
