### ISSUE TITLE
imfile problem

### ISSUE THREAD

**Issue by ubellavance** [rsyslog/rsyslog#3912]
### Environment
- rsyslog version: 8.24.0-41.el7_7
- platform: RHEL 7.7
- for configuration questions/issues, include rsyslog.conf and included config files

We have nginx servers configured to send their logs to a dev server so that devs can access prod logs without having shell access to prod servers.  It has been working fine for over 2 years, but it recently started having problems.

Sample configuration:
```
$InputFileName /var/opt/rh/rh-nginx18/log/nginx/ssl-www.domain.com.access.log
$InputFileTag rp_domaincom_access
$InputFileStateFile state-www.domain.com_access
$InputFileSeverity notice
$InputFileFacility local6
$InputFilePollInterval 1
$InputFilePersistStateInterval 0
$InputRunFileMonitor
```
The first symptom that I saw is that logs weren't updating on the destination, for some files (we forward about 12 logs this way). Then I found that there was a problem even locally: Normally I can see the log entries from the nginx logs in /var/log/messages because of this imfile configuration, but since this problem started, it stops around the log rotation time (around 3AM) and it resumes in late PM (3-4 PM). So the problem doesn't seem to be that logs aren't sent or received, it's that they're not even generated from the input file.

rsyslog has been updated on the servers on Sep 19, but the problem started on Sept. 24.

I've opened a case with Red Hat, but they've been rather useless up to now so I thought I'd give it a try here.
Any help would be appreciated.
Thanks,

**Comment by ubellavance** [comment]
Red Hat has assigned a more senior engineer to my case and we worked quite a lot on this issue. We did an update of rsyslog that was made available recently (8.24.0-41.el7_7.2). It looks like the issue is not resolved even with that update. I submitted a lot information through sosreports, rsyslogd core dumps, etc. 

BTW, Red Hat is usually way better than that on support, it was an exception.

**Comment by davidelang** [comment]
unfortunately, the 8.24 codebase is almost 3 years old (with releases every 6 weeks since then)
The imfile module has been almost completely re-written since then (I think twice), and unless RedHat backported all that work, they aren't going to have it.

8.1910 is the current version (after ~8.40 we switched to date based version numbers as too many people weren't realizing how old the version they were running is)

The RedHat support model of "we stick with one version for the entire major release an only backport 'important' security fixes" has bitten me so many times over the years, that if an app is the main functionality of the machine, I run the upstream version, not the RedHat version that has a combination of patches unlike anything else.

**Comment by ubellavance** [comment]
Thanks for your input.  It looks like my symptoms are the same as pr #3521. I'll take care of the rest with Red Hat. Thanks.
