### ISSUE TITLE
imtcp with TLS tight cpu loop

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#4270]
rsyslog 8.2001 (will try to reproduce on later version, obs stall is interacting badly with company policy) on CentOS 6

I am running into a situation on a production server where the cpu utilization of the rs:imtcp thread will spike to at or near 100%, a strace shows a few futex calls but almost everything (~200x as much) is a read of a socket file discripter with an -EAGAIN error.

During this time, it no longer processes new TLS connections.

once in a while it will un-jam for a bit (cpu utiliztion drops to 40-60% for a few seconds) and process connections properly and then stall again on a different fd/socket

I am trying to generate a test case for this, but it is very intermittent. Sometimes it will freeze within seconds of starting, other times it will run for hours.

I will post more when I can narrow it down. Unfortunantly the system is a production server and overall very busy.

**Comment by davidelang** [comment]
looks like this may be similar to #4288 as it is gnutls sender, openssl receiver (both 8.2001)

**Comment by chrisad2** [comment]
I'm experiencing similar issues, though I am using gnutls and both sender and receiver.

Upon starting the rsyslog service on the receiver, CPU will:
1. Run hot for hours or days
2. Drop down to <1% eventually but not accept more TLS connections until restart
3. I'll restart the service
4. Repeat

Additionally this whole time, the queues are filling up on my senders and messages are getting dropped.

I'm not an rsyslog expert, but is there any specific info I can contribute to assist with this issue?  I've got days of impstats output in CEE format.

I'm running CentOS 7, 2 cores, 8GB RAM, rsyslog 8.2002.0 right now.

**Comment by alorbach** [comment]
Can you post your configurations? Perhaps with sample certificates if its related to them? 
We need top craft a testcase somehow in order to reproduce the problem.

**Comment by chrisad2** [comment]
Here are my configs.  I can't post certificates because they are a private internal CA.  But I can tell you the following about them:

- Signature algorithm is sha256WithRSAEncryption
- Extended Key Usage is TLS Web Server Authentication
- Public key is 2048 bit rsaEncryption

Notes on my configs:

- clients send to a single, regional "first forwarder" as denoted by the file names
- "first forwarders" each send to two "second forwarders" (named with A and B in the Target= lines of the configs)
- "second forwarders" are where I am seeing the problem right now, as all of the "first forwarders" send to the "second" over TLS
- "second forwarders" send to a final destination over UDP currently, but will soon be sending over TLS

Thanks in advance for any assistance!


[00_tls.conf.txt](https://github.com/rsyslog/rsyslog/files/4717258/00_tls.conf.txt)
[10_first_forwarder_input.conf.txt](https://github.com/rsyslog/rsyslog/files/4717259/10_first_forwarder_input.conf.txt)
[20_first_forwarder_output.conf.txt](https://github.com/rsyslog/rsyslog/files/4717260/20_first_forwarder_output.conf.txt)
[30_second_forwarder_input.conf.txt](https://github.com/rsyslog/rsyslog/files/4717261/30_second_forwarder_input.conf.txt)
[40_second_forwarder_output.conf.txt](https://github.com/rsyslog/rsyslog/files/4717262/40_second_forwarder_output.conf.txt)

**Comment by alorbach** [comment]
@chrisad2 : Do you have shell commands to generate CA / CERTS with your settings? 
This would help setting up a testcase for this issue.

**Comment by nikolas-hermanns** [comment]
I have the exact same problem. My sender is fluentd,

This is my config:
$ModLoad imtcp
$ModLoad omkafka

$DefaultNetstreamDriver gtls
#$DefaultNetstreamDriver ossl
$DefaultNetstreamDriverCAFile /etc/ssl/certs/ca-cert.pem
$DefaultNetstreamDriverCertFile /etc/ssl/certs/rsyslog-cert.pem
$DefaultNetstreamDriverKeyFile /etc/ssl/certs/rsyslog-key.pem


$InputTCPServerStreamDriverAuthMode x509/name
$InputTCPServerStreamDriverPermittedPeer fluentd
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode

$InputTCPServerRun 6514

$MaxMessageSize 32k

# Filter duplicated messages
$RepeatedMsgReduction on


#
# Set the default permissions for all log files.
#
#$FileOwner syslog
#$FileGroup adm
#$FileCreateMode 0640
#$DirCreateMode 0755
#$Umask 0022
#$PrivDropToUser syslog
#$PrivDropToGroup syslog
#$EscapeControlCharactersOnReceive off

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat


main_queue(
    queue.type="LinkedList"
    queue.filename="mainmsgqueue"
    queue.saveonshutdown="on"
    queue.dequeueslowdown="1000"
    queue.workerthreads="5"
    queue.timeoutworkerthreadshutdown="-1"
    queue.dequeuebatchsize="5000"
    queue.maxfilesize="10m"
    queue.maxdiskspace="1g"
    queue.size="2510000"
    queue.discardmark="2500000"
    queue.discardseverity="0"
    queue.highwatermark="2000000"
    queue.lowwatermark="1500000"
    ioBufferSize="64k"
    flushOnTXEnd="off"
    asyncWriting="on"
    net.enableDNS="off"
    )

#
# Where to place spool files
#
$WorkDirectory /var/spool/rsyslog


###for rsyslog's log

syslog.*                        /tmp/rsyslog.log #rsyslog error messages


template(name="rawmsg" type="list"){
    property(name="rawmsg")
}

action(type="omkafka" topic="cism"  broker=["kafka:9092"] template="rawmsg")

This is how I create the certificates:
sudo openssl genrsa 2048 > ${KEY}
    sudo openssl req -newkey rsa:2048 -days 1000 -nodes -keyout ${KEY} -subj "/CN=${cn}/C=AU/ST=Some-State/O=SOME" > ${store_location}/${component}-req.pem
    sudo openssl x509 -req -in ${store_location}/${component}-req.pem -days 1000 -CA ${CA} -CAkey ${CA_KEY} -set_serial 01 > ${CERT}


I can reproduce it 100%. First 600k messages are received/transmitted and then rsyslog does not transmit anything anymore.

**Comment by nikolas-hermanns** [comment]
I can confirm that it fixes the bug. Thanks!
