### ISSUE TITLE
CEF not being written to log file correctly

### ISSUE THREAD

**Issue by jasonmull** [rsyslog/rsyslog#4309]
### Expected behavior
CEF log should be in the format of www.website.com CEF:0
### Actual behavior
CEF is formatted as www.website.com CEF: 0 (Note the space between "CEF" and "0".  When I get logs with this space, the Elastic FileBeat CEF decoder does not properly detect this format.
### Steps to reproduce the behavior
Any logs coming in from this vendor have this issue.  Other vendors do not show this behaivor.  When running a packet capture with TCPDUMP, the raw packet data does not show the space and appears to be formatted correctly, so seems like a translation issue within rsyslog.

### Environment
- rsyslog version: 8.32.0
- platform: Ubuntu 18.04.1

**Comment by davidelang** [comment]
since you don't provide any sample messges, I have to guess what's happening.

I'm guessing that the messages that you are getting are not valid syslog 
messages, and so rsyslog is having to make it's best guess as to what is 
intended and populating the programname with CEF: and then adding a space for 
readability between the programname and the body of the message.

if you can show us the message on the wire, we can point out what's invalid 
about it. If you log the messages with the template RSYSLOG_DebugFormat you ill 
get all the details, including the rawmsg which shows exactly what came over the 
wire.

David Lang


  On Tue, 2 Jun 
2020, jasonmull wrote:

> Date: Tue, 02 Jun 2020 08:51:22 -0700
> From: jasonmull <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [rsyslog/rsyslog] CEF not being written to log file correctly (#4309)
> 
> ### Expected behavior
> CEF log should be in the format of www.website.com CEF:0
> ### Actual behavior
> CEF is formatted as www.website.com CEF: 0 (Note the space between "CEF" and "0".  When I get logs with this space, the Elastic FileBeat CEF decoder does not properly detect this format.
> ### Steps to reproduce the behavior
> Any logs coming in from this vendor have this issue.  Other vendors do not show this behaivor.  When running a packet capture with TCPDUMP, the raw packet data does not show the space and appears to be formatted correctly, so seems like a translation issue within rsyslog.
>
> ### Environment
> - rsyslog version: 8.32.0
> - platform: Ubuntu 18.04.1
>
>
>

**Comment by rgerhards** [comment]
As David says, the config is missing, so I, too, cannot dispense any advise. As a small rant, there is a reason why we ask for the config - it makes it unnecessarily hard for everyone if it is not provided.

**Comment by alexey-atiskov** [comment]
Seems like message that was sent to syslog had no APP_NAME, that's why "CEF" is treated as appName and space is added.
https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.5
