### ISSUE TITLE
rsyslog-openssl: TLS server does not send intermediate certificates, breaking verification

### ISSUE THREAD

**Issue by rlaager** [rsyslog/rsyslog#4360]
This is like #2762, but for OpenSSL instead of GnuTLS.

The hostname has been changed to "syslog.example.com" in the examples.

### Expected behavior
With GnuTLS, it works:
```
openssl s_client -CAfile /etc/ssl/certs/ca-certificates.crt -connect syslog.example.com:2514
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = syslog.example.com
verify return:1
---
Certificate chain
 0 s:CN = syslog.example.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

### Actual behavior
With OpenSSL, we only get the end certificate:
```
$ openssl s_client -CAfile /etc/ssl/certs/ca-certificates.crt -connect syslog.example.com:2514
CONNECTED(00000003)
depth=0 CN = syslog.example.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = syslog.example.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:CN = syslog.example.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
```

### Environment
- rsyslog version: 8.2001.0 (aka 2020.01)
- platform: Ubuntu 20.04
- for configuration questions/issues, include rsyslog.conf and included config files
```
module(load="imrelp" tls.tlslib="openssl")
input(
    type="imrelp" port="2514"
    tls="on"
    tls.myCert="/etc/rsyslog.tls/fullchain.pem"
    tls.myPrivKey="/etc/rsyslog.tls/privkey.pem"
)
```

**Comment by aggiechris** [comment]
This is odd... I experienced the exact opposite behavior - full chain with OpenSSL and only first cert with GnuTLS, however I was using imtcp (using 8.2002.0 on CentOS 7).

You're using imrelp here... do you experience the same issue with imtcp?

**Comment by rlaager** [comment]
imtcp is consistent with imrelp: GnuTLS serves the full chain but OpenSSL serves only the end certificate.

I configured this:

```
global(
    defaultNetstreamDriverCertFile="/etc/rsyslog.tls/fullchain.pem"
    defaultNetstreamDriverKeyFile="/etc/rsyslog.tls/privkey.pem"
)
module(
    load="imtcp"
    streamdriver.name="gtls" # use gtls netstream driver
    streamdriver.mode="1" # require TLS for the connection
    streamdriver.authmode="x509/name" # server is NOT authenticated
)
input(
    type="imtcp"
    port="1514"
)
```

I received this:
```
 0 s:CN = syslog.wiktel.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
```

If I change `gtls` to `ossl`, I get this:
```
 0 s:CN = syslog.wiktel.com
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
```

**Comment by aggiechris** [comment]
Looks like the issue is in 8.2001.0.

I think you can solve by either a) upgrading rsyslog or b) instead of using the full chain in your defaultNetstreamDriverCertFile, put the first cert in defaultNetstreamDriverCertFile and the rest of the chain in defaultNetstreamDriverCAFile.  I tested this on 8.2001.0 and it presents the full chain with OpenSSL.

These are my results from combinations of GnuTLS vs OpenSSL and using separate cert and chain files vs full cert chain on 8.2001.0 vs 8.2006.0:

On 8.2001.0
- gtls and cert/chain in separate files - TLS server presents only first cert in chain
- ossl and cert/chain in separate files - TLS server presents full chain
- gtls and cert/chain in single file - TLS server presents full chain
- ossl and cert/chain in single file - TLS server presents only first cert in chain

On 8.2006.0
- gtls and cert/chain in separate files - TLS server presents only first cert in chain
- ossl and cert/chain in separate files - TLS server presents full chain
- gtls and cert/chain in single file - TLS server presents full chain
- ossl and cert/chain in single file - TLS server presents full chain

**Comment by rlaager** [comment]
Thanks. That work-around seems to work.
