### ISSUE TITLE
odd effect of maxmessagesize

### ISSUE THREAD

**Issue by qzrrbz** [rsyslog/rsyslog#463]
repeat by ...
1) set max message size to something workably small(est)
global(maxmessagesize="128")

2) push a log line at the host with nominally random facility/priority string
/tmp/logger -i -p syslog.info -t logger -n localhost -P 1344 -T --rfc3164
11111111111111111 1111111111111111 111111111111111111 2222222222222222 222222222222222 222222222222222 22222222222 222222222222222 22222222222222222 22222222222222 more than 128

3) get interesting results
syslog.info <46>Jul 29 16:01:27 zenvm119 logger[16633]: 11111111111111111 1111111111111111 111111111111111111 2222222222222222 2222222222222
user.notice 22 222222222222222 22222222222 222222222222222 22222222222222222 22222222222222 more than 128

*the template here is "template(name="rawMsg" type="string" string="%pri-text% %rawmsg%\n")"

the "interesting" bit is the lack of inheritance of the facility/priority on subsequent chunks of the message.  this would seem to be a little surprising!

**Comment by alorbach** [comment]
Proberly related to the logger tool you are using? 
Mine default logger tool (Ubuntu 14) does not support options like -T or --rfc3164

**Comment by davidelang** [comment]
this isn't at all surprising.

when you hit the max message size, rsyslog does not continue the message into the next message (keeping things like facility/priority). What it does is it completely closes out the first message (delivering it, and forgetting about it) and then starts looking at the remainder of the data from scratch with no other context.

so whatever happens to be after the limit is now parsed as if that's the beginning of the message, and since rsyslog has heuristics to try and fix mildly broken sources, it gets 'something' from the bad data.

This is usually seen on network connections where the sender sends data larger than what the recipient allows.

So this is 'works as intended' I sometimes wish that rsyslog did something 'better' in cases like this, but then I had a situation where a sender send all it's messages with no linebreaks, so I ended up with several GB of data that would have been 'one message'

It would be interesting to consider a parser option that would do some sort of 'to be continued'  'continued' when it hits this sort of situation, but there are so many problems with trying to reassemble such messages later (including all the various corner cases and failure modes that can cause messages to arrive out of order or interlaced with other messages), that I'm not sure there is a sane thing to do

**Comment by qzrrbz** [comment]
so, bottom line -- if it hurts when you do that, don't do that... :-)

i'm not sure what "sanity" would look like here either

**Comment by davidelang** [comment]
more like "this is how it breaks when you do something you told it not to accept" :-)
