### ISSUE TITLE
Don't allow programs to fill up syslog disks

### ISSUE THREAD

**Issue by jidanni** [rsyslog/rsyslog#4677]
Please see https://github.com/systemd/systemd/issues/20660

**Comment by davidelang** [comment]
what are you using to rotate the files?

Typically people use logrotate for this, and it has the ability to specify the 
number of files that it keeps.

one problem with setting limits on this and having data auto-deleted is that it 
makes it easier for bad guys to cover their tracks, just by generating lot of 
log data.

David Lang

**Comment by jidanni** [comment]
As you saw with my ls -l output, rotation was working fine.
Then all the sudden https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/issues/36
started filling up the disks.
So it is not rotation that needs fixing.
It is "that one telephone (program) that is filling up the disk".
If it is making more than 500 messages at a time,
you know the hacker has hacked that program, and he can't cover his tracks...
as they lead to that program...

**Comment by cybersecuritypoet** [comment]
This is not a problem with rsyslog, this is a problem with your particular configuration.
Introducing such a default limit would break backwards compatibility. It also has other implications, which might not be apparent by looking at only one case. Additionally, you can set up such a limit yourself, by actually configuring rsyslog instead of relying on the distro-provided default config. There is a rate-limiting feature of sorts available in rsyslog.
Properly setting up logging subsystem of the OS is a crucial part of OS administration and I don't see why this responsibility is being pushed to the logging software.

**Comment by rgerhards** [comment]
As @cybersecuritypoet says, there is ample of rate-limiting capability in rsyslog. Make use of it. Other folks have high volume traffic where 500 msgs in a second is "nothing". One size doesn't fit all. One thing we could do (potential whishlist item) is that we stop writing files if they fill up more than x% disk. But you can also configure this via the OS.

**Comment by jidanni** [comment]
OK! But as you see in
[log.gz](https://github.com/rsyslog/rsyslog/files/7130224/log.gz)
the rouge program has managed to sail just below the default
https://www.rsyslog.com/changing-the-settings/
with its devious one burst per minute, etc.
So please give me a recipe to put a clamp on it.
Thanks!
