### ISSUE TITLE
omprog would fork many subprocess in a high load

### ISSUE THREAD

**Issue by chenryn** [rsyslog/rsyslog#473]
```
ruleset( name="ruleset_www" )
{
        action(
            type="omprog"
            binary="/usr/bin/python /usr/local/sinawap/bin/rsyslog2scribe.py --scribeHost=127.0.0.1 --scribePort=1463 --category=www --accessLog=/var/log/rsyslog2scribe-wb_www_access.log --msgNum=20000"
            template="wwwLogFormat"
            name="action_wb_www"
            queue.filename="action_wb_www"
            queue.size="200000"
            queue.dequeuebatchsize="20000"
            queue.highwatermark="150000"
            queue.lowwatermark="100000"
            queue.discardseverity="3"
            queue.discardmark="195000"
            queue.maxdiskspace="20G"
            queue.type="linkedlist"
            queue.maxfilesize="500M"
            queue.workerthreads="1"
        )
}
```

But there are so many subprocess and count increase!
```
# ps auxfww | grep rsyslog2scribe-wb_www |wc -l
84
```

impstat.log:

```
2015-08-10T20:16:37.091604+08:00 rsyslogf3.mweibo.yf.sinanode.com rsyslogd-pstats: {"name":"action_wb_www queue[DA]","origin":"core.queue","size":6,"enqueued":70671,"full":0,"discarded.full":0,"discarded.nf":0,"maxqsize":2294}
2015-08-10T20:16:37.091619+08:00 rsyslogf3.mweibo.yf.sinanode.com rsyslogd-pstats: {"name":"action_wb_www queue","origin":"core.queue","size":132400,"enqueued":772514,"full":0,"discarded.full":0,"discarded.nf":0,"maxqsize":172669}
2015-08-10T20:22:07.834642+08:00 rsyslogf3.mweibo.yf.sinanode.com rsyslogd-pstats: {"name":"action_wb_www queue[DA]","origin":"core.queue","size":0,"enqueued":100000,"full":0,"discarded.full":0,"discarded.nf":0,"maxqsize":3695}
2015-08-10T20:22:07.834649+08:00 rsyslogf3.mweibo.yf.sinanode.com rsyslogd-pstats: {"name":"action_wb_www queue","origin":"core.queue","size":74155,"enqueued":2294484,"full":0,"discarded.full":0,"discarded.nf":0,"maxqsize":172308}
```

just after I paste the log , `wc -l` show 181 now.

**Comment by chenryn** [comment]
I use rsyslog-8.11.0, there are no such situcation before I upgrade from 7.6.7

**Comment by alorbach** [comment]
Try adding this setting into your action: 
forceSingleInstance="on"

The settings needs to be added into the documentation. It will force omprog to only spawn the process once. Support for multiple instances was added in 2014, so older versions did only spawn one instance.

**Comment by jsiwrk** [comment]
(I'm reviewing the omprog documentation, and I'm trying to understand the purpose of the `forceSingleInstance` flag. Here is my analysis.)

Most probably, this (old) bug was in fact a duplicate of #1144: omprog was not closing the child process when a worker was unscheduled. It was fixed in v8.23.0 by PR #1155 ([commit](https://github.com/rsyslog/rsyslog/commit/ba22858037af402b9071881976a25ced72463b2d#diff-e3cb3014ecfd8b9782b9274c6a7fa343)).

Apparently, the `forceSingleInstance` flag was added as an attempt to solve this problem. But it didn't (as the reporter of #1144 said). When enabled, this flag causes the execution of `doAction` to be serialized between the worker instances (i.e. prevents them from concurrently executing `doAction`). At the time this flag was added, `doAction` started the child process if it was not started yet (this changed in later versions: the child process is now started in `createWrkrInstance`). But this didn't correct the bug, since the real problem was the child process not being closed in `freeWrkrInstance`.

My conclusion is that the `forceSingleInstance` flag is useless, and should be documented as deprecated. It does not correct the bug it was intended to correct. Besides, it does not prevent child processes from being executed concurrently, as the child processes are executed asynchronously with respect to `doAction` (because of the pipe buffering). This behaviour, if desired, can be achieved by simply setting the `queue.workerthreads` parameter to `1` (which is the default).

**Comment by rgerhards** [comment]
@jsiwrk The original intent of ```forceSingleInstance``` was (and is) to support program that cannot run in multiple instances. For example, SEC (IIRC), needs to have all data fed to a single instance, else it cannot correlate the data as expected.

So it looks like this is a bug, and a bug we should fix.

**Comment by jsiwrk** [comment]
@rgerhards I don't understand what would be the difference between setting `queue.workerthreads` to 1 and the intended behaviour of `forceSingleInstance`. With only one worker thread, only a single instance of the external program is executed. Why is a specific flag needed to achieve this behaviour?

Perhaps this flag could have made sense (if correctly implemented) in previous versions of rsyslog, when the child process was started in `doAction`. But now the child process is started in `createWrkrInstance`. Hence, it seems that this feature can be achieved by simply restricting the number of workers to 1.  (\?)

**Comment by jsiwrk** [comment]
@rgerhards I suppose you meant "other actions on the same queue". I have opened a separate issue for this: #2813. Continuing there.
