### ISSUE TITLE
Imfile: Logrotation causes duplicates when processing pipeline is long

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#4797]
### Expected behavior
No data gets duplicated

### Actual behavior
Events get duplicated, amount depends on load and pipeline length.

Snip from PoC container
```sh
Successfully built 0174257d958b
Successfully tagged rsyslog-logrotate-reread:latest
Starting curl spamming
Starting logrotates
Logrotate and httpd graceful reload, round 1
Logrotate and httpd graceful reload, round 2
Logrotate and httpd graceful reload, round 3
Logrotates done
Curling done, sleeping a bit to allow rsyslog to catch up
Amount of logs on disk: 10000
Amount of logs in spool.log: 5037
<snip>
Amount of logs in spool.log: 18001
Found total of 18001 events
And 8001 were duplicates! :(
Example of duplicate line: 
2022-02-07T13:08:38.059282+00:00 2a6dd7aab40f access_log 127.0.0.1 - - [07/Feb/2022:13:08:37 +0000] "GET /request-3003 HTTP/1.1" 404 210 "-" "curl/7.29.0" -- /logs/access_log -- 98294
2022-02-07T13:09:14.213275+00:00 2a6dd7aab40f access_log 127.0.0.1 - - [07/Feb/2022:13:08:37 +0000] "GET /request-3003 HTTP/1.1" 404 210 "-" "curl/7.29.0" -- /logs/access_log -- 0
Sleeping indefinitely
```

### Steps to reproduce the behavior
Have long and slow event processing pipeline, write a lot of logs and run logrotate. 

### Environment
Newest rsyslog from adiscon repos, host is Fedora 35 and container Centos 7

```sh
# rsyslogd -v
rsyslogd  8.2112.0 (aka 2021.12) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu

# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

```

### Ready to run container + configs

Attached are container where the behaviour can be observed. Configurations are intentionally crafted to emulate the heavily loaded machine and mileage might vary on faster/slower machines

[reread-issue.zip](https://github.com/rsyslog/rsyslog/files/8015480/reread-issue.zip)

**Comment by davidelang** [comment]
what is your logrotate config? It would probably help to see your rsyslog config 
as well.

David Lang

**Comment by StrongestNumber9** [comment]
All relevant configurations and ready to go Dockerfile are included in the reread-issue.zip attachment

**Comment by alorbach** [comment]
I believe the duplicates are caused by librelp, in order to reproduce this behavior, I have created a testcase based on your configurations, see here: https://github.com/alorbach/rsyslog-1/blob/pr-issue-4797/tests/sndrcv_relp_sessionbreak_root.sh

The testcase requires root because of the ss command which I am using simulate tcp session interruptions.

The duplicates are not caused by rsyslog itself, they are caused by unacked messages send in librelp windows (See WindowSize at https://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html#windowsize) when network connections are unexpectedly terminated . They are also expected and can be reduced by reducing WindowSize (lowest value possible is 2). But a value of 2 will have a negative impact on sending performance.

**Comment by rgerhards** [comment]
The issue seems to be valid and rooted in imfile.

The problem can be show by running the container mentioned by @StrongestNumber9 in the initial posting. The test case can be further simplified by just generating 1,000 messages (vs. 10,000). This will trigger one duplication round (at least in my workstation environment).

From what I see, it looks like there is a communication problem between the stream.c class and imfile. Stream seems to detect the inode change, but imfile for some reason continues to use the previous inode. Only at a later stage it detects the inode change and this will cause a re-send of the file in question.

I now need to modify the container environment so that we can build rsyslog inside it, because otherwise I cannot do any further instrumentation or analysis. Or try to generate a test case for it, which also seems quite complex. So this sounds a bit like it takes quite some time just to get a reproducible test case up and running in development mode.

I'll try to see if I can find out more without the test env. Any findings, now or later, I will report here.

**Comment by rgerhards** [comment]
I think I was able to create a sufficient similar test case: https://github.com/rsyslog/rsyslog/pull/4883 -- still needs more work, but wanted to make it public. Improving the test case and fixing will probably take some time.

**Comment by rgerhards** [comment]
The problem seems to be related to improper handling of `rotationCheck` variable in `stream.c`, `imfile.c`. Actually it looks like imfile  does not apply `STRM_ROTATION_DO_NOT_CHECK` in all relevant places (most importantly not when initially opening a file).

Side-Note: I have a rough PoC which very strongly points into that direction. It must be noted that it looks like when this is correctly done, there is some message loss with frequently writing writers of the monitored file. The reason is probably a race between

- rsyslog hitting EOF on the file
- logrotate moving and sending HUP
- the writer getting HUP a bit later, or at least acting slightly delayed on it

We need to review the situation more in-depth.

**Comment by rgerhards** [comment]
I have labelled this now as "bug", because there is sufficient evidence that it indeed is one.

**Comment by rgerhards** [comment]
The situation is pretty complex. It looks relatively easy to fix the duplicates. But I did not dig into details, as the PoC works sufficiently well and I wanted to sort this out fully before proceeding with a final solution. But then we get some message loss due to frequent HUP.

The issue here is when to consider a file as "done". Due to latency, logrotate may send SIGHUP just a little bit too late. What I can see is:

- rsyslog reads file
- logrotate runs, rotates away previous file
- rsyslog processed data, but sees file go away
- rsyslog does finally read "remaining" data
- rsyslog closes file and cleans up internal structures
- writer again writes to already-rotated file (still has it open)
- logrotate signals write (in this test via HUP)
- writer closes and reopens file
- rsyslog detects new file and begins to process it

However, depending on circumstances, some file lines are lost while rsyslog thought the file was done but logrotate did not yet signal the writer OR the writer did not yet act on the HUP.

Remember that both HUP and inotify are async, so there is some inherent race. Note that the HUP latency may also affect logrotate when doing compression (not yet checked, but seems likely).

My current idea is, to combat the situation, make rsyslog not immediately close the file, but apply a timeout,. at least 10 seconds or so. Any new data in that period should still read, even if we have interim EOF (which can happen when the writer stops writing, but continues before it receives/acts on HUP or whatever signal).

The bad thing about this approach is that it seems to require big changes to the code base. 

I am not yet 100% confident this is the actual cause of actions, but I took me the day to analyze it, and so I am at least pretty sure. I'll do some more analysis and also have a look together with @alorbach.

@davidelang any comments? Would be appreciated.
