### ISSUE TITLE
Provide ratelimit metrics for imudp and imtcp similar to imuxsock.

### ISSUE THREAD

**Issue by smetj** [rsyslog/rsyslog#48]
ratelimit.discarded and ratelimit.numratelimiters are not available for modules imudp and imtcp.
imuxsock has these metrics.

Rsyslog 7.6.0-1

**Comment by rgerhards** [comment]
@PascalWithopf could you please check if this has already done. I think so, but am not sure.

**Comment by PascalWithopf** [comment]
@rgerhards the parameter are not in the modules.

**Comment by rgerhards** [comment]
This is more complicated than it initially sounded, because the modules use some common code which does not provide the necessary statistic counters. So we would need to redesign the queue submission subsystem. Given that nobody has voted in favor of this feature request in almost 3 years, I am going to close this for now. If more users come up for a similar feature request, we can implement it.
