### ISSUE TITLE
imjournal: Add ability to filter on journal _TRANSPORT

### ISSUE THREAD

**Issue by opoplawski** [rsyslog/rsyslog#483]
See https://github.com/systemd/systemd/issues/959 for background.  We may be needing a way to filter out _TRANSPORT=audit messages from the journal.

**Comment by rgerhards** [comment]
I am not sure if this is the right thing to do. As you say in the issue referenced, I think journal would be the right place to fix this. I don't believe rsyslog should try to work-around all of the journal issues...

Any more comments anyone else?

**Comment by radu-gheorghe** [comment]
Just my 2 cents: Isn't this something that can be done in rsyslog.conf *after* the message is ingested? That sounds like the reasonable thing to do in rsyslog. If filtering needs to be done at the source, it sounds like journal would be a better place to do such filtering than imjournal - because one would presumably want logs not to touch rsyslog in the first place.

**Comment by davidelang** [comment]
we already have very extensive ability to filter logs, as long as the jounral_transport is one of the fields that we have available to filter on, we should be  able to filter it without adding new options.

I don't see there being much value in filtering it in the input module instead of in the main log processing loop. You would save a little load, but it really breaks the layering model we have.

If we don't get this info from the journal, then there is a problem.

If the journal is sending us the data and not passing this info along, then it's the journal's fault. The journal really should have an option to send the data to rsyslog in JSON so that all the metadata is preserved (but I wouldn't hold my breath on this, given their hostility towards interoperability). In this case we have no way to filter on this because we never see it.

If we are fetching from the journal and not extracting this field into our JSON data, it's our faulr. If we do extract it, existing filtering will work.
