### ISSUE TITLE
use compressed data with omelasticsearch postings

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#497]
from the forum  http://kb.monitorware.com/viewtopic.php?p=25841#p25841

It's not stated in the documentation, and I assume such feature does not exist.
We are sending lots of data to elasticsearch, and gzipping them would help a lot, because log data compresses well.
It seems that ES accepts gzipped POSTs (having Content-Encoding: gzip).

Could you add compression to rsyslog elasticsearch plugin, please?

**Comment by rgerhards** [comment]
can you provide details on what's required to do so?

**Comment by davidelang** [comment]
I think it's a matter of adding a http header to the post and running the 
content through compression

https://en.wikipedia.org/wiki/HTTP_compression

David Lang

**Comment by radu-gheorghe** [comment]
Also, for this to work, one has to enable HTTP compression in Elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html which is disabled by default.

I assume this would help in low-bandwidth situations - otherwise the load put on ES when sending lots of data would be way higher than whatever load the data transfer would generate (including compression for that matter).

**Comment by otisg** [comment]
Right, I would think this would end up using ES nodes' CPU on decompression instead of using it to index quickly (and handle queries).

**Comment by rgerhards** [comment]
given this is open for long and no further interest has been expressed - should we close this without doing any further implementation? It looks so to me...

**Comment by rgerhards** [comment]
ok, seems like no interest in this feature. Closing.
