### ISSUE TITLE
dockerfile sharing

### ISSUE THREAD

**Issue by woodz-** [rsyslog/rsyslog#5037]
### Expected behavior
Dockerfile available for each image provided on https://hub.docker.com/u/rsyslog

### Actual behavior
no Dockerfiles found

### Steps to reproduce the behavior
search on https://hub.docker.com/u/rsyslog

### Environment
- rsyslog version: 2022.10
- platform: Ubuntu 20.04

Would you mind to share Dockerfiles to your images? If you did already, could you provide a link to the resources?

I'd like to build images for arm64v8 arch.

**Comment by davidelang** [comment]
who posts the files to hub.docker.com? I suspect it's someone other than the 
rsyslog team.

David Lang

**Comment by woodz-** [comment]
Taking as a sample the [ubuntu tags](https://hub.docker.com/r/rsyslog/rsyslog_dev_base_ubuntu/tags). They're all coming from [rgerhards](https://hub.docker.com/u/rgerhards). He is the head of this rsyslog project, isn't he?

**Comment by rgerhards** [comment]
These are CI containers. The testbench uses them. I am not sure if Dockerhub removes images that have not been used for quite a while. That is surely the case for older platforms no longer used in CI.

Bottom line: these are not for production use and very heavy.

We made one attempt to provide a general use container: https://hub.docker.com/r/rsyslog/syslog_appliance_alpine/

Unfortunately, we never saw any questions and real usage, so I have not maintained it since quite a while. As far as I know, a good container basis is https://github.com/JPvRiel/docker-rsyslog
