### ISSUE TITLE
action.copymsg use too many memory.

### ISSUE THREAD

**Issue by chenryn** [rsyslog/rsyslog#508]
I had report a bug about async output in for loop before, and @janmejay add a `action.copymsg` option in https://github.com/rsyslog/rsyslog/commit/2808d4805ee470ecf6611a4dbc2e42c25bc58cac to fix this.

Now, I find that the rsyslog process use too much memory if I use `action.copymsg` in for loop. I think this may because action copy the whole msg every time in a loop, so, if there is an 100 items array stored in a 1MB line,the for loop would use 100 MB mem?

Is there any more clear implement for this use case?

**Comment by janmejay** [comment]
The alternative is to use a message level lock for variable manipulation,
but then config will become too complex (worrying about what is atomic and
what isn't). It will also be easy for ppl to make mistakes. So not a good
option.

Third option is to have a copy-on-write style implementation, but that will
require larger change (to how message and changes made to cee/local
variables are represented).

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
The current master has a couple of improvements which should remove the need for most cases of the ```action.copymsg``` cases. Note that it also requires some more memory simpyl because we need to ensure proper operation.

Other than that, I think there is not much more except what @janmejay said in the rsyslog code base. Note, though, that I also have improvements in json-c on my plate, which will probably also help to address memory need.

I am closing this issue, because it should be considered solved. If not, please reopen with more details on how current master (soon 8.15) behaves.
