### ISSUE TITLE
Duplicated, split log lines in rsyslog log server

### ISSUE THREAD

**Issue by mcpherrinm** [rsyslog/rsyslog#5126]
### Expected behavior
Lines appear intact in log files

### Actual behavior
We use rsyslog on central log servers to collect logs over the syslog protocol and store them in files on disk.

We have observed that rsyslog sometimes (a number of times per day; a very small fraction of log lines) writes out corrupted log files.  It only seems to happen when we’re under heavier CPU load as we get bursts of messages around peak times.  I see in our logs the problem always occurs between a `rsyslogd: main Q:Reg: high activity - starting 1 additional worker thread(s), currently 1 active worker threads.` and `main Q:Reg: worker thread 55656cb63010 terminated, now 1 active worker threads` so we suspect this is concurrency related.

The log corruption always looks the same:

A log message is split into two parts, and the prefix and suffix appear nearby each other in the log, with other log messages in the middle.  The original log message also appears intact, either before or after the split version.  We log our logs to two locations (see below configuration).  We’re only seeing corruption on the “TmplAudit” (filtered) logs, and not the “full” logs, so that implies rsyslog is successfully receiving the logs intact.

Here’s a typical example. Note that midway through the first line in this example, the message is cut off (after “inval”) and another message begins with another timestamp.  The rest of the log line is 6 lines later in the file.  After a further 6 lines, the entire log line appears intact.

```
2023-04-26T00:07:32.124068+00:00 xxxxxxxxxxx xxx 6 boulder-va[347917]: xxxxxxx [AUDIT] Validation result JSON={"ID":"nnnnnnnnnnnn","Requester":nnnnnnnnn,"Hostname":"www.xxxxxxxxxxx","Challenge":{"type":"http-01","status":"inval2023-04-26T00:07:32.087530+00:00 xxxxxxxxxxx xxx 6 boulder-va[347917]: xxxxxxx [AUDIT] Checked CAA records for xxxxxxxxxxxxxxxxxxxxxxxx, [Present: false, Account ID: nnnnnnnnn, Challenge: http-01, Valid for issuance: true] Response=""
< 6 lines removed>
id","error":{"type":"unauthorized","detail":"nnnnnnnnnnnnnnnnnnnnnnnnn: Invalid response from http://www.xxxxxxxxxxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 404","status":403},"token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","keyAuthorization":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","validationRecord":[{"url":"http://www.xxxxxxxxxxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","hostname":"www.xxxxxxxxxxx","port":"80","addressesResolved":["nnnnnnnnnnnnn","nnnnnnnnnnnnnn","nnnnnnnnnnnnnnnnnnnnnnnnn","nnnnnnnnnnnnnnnnnnnnnnnnn"],"addressUsed":"nnnnnnnnnnnnnnnnnnnnnnnnn"}]},"ValidationLatency":1.2,"Error":"unauthorized :: nnnnnnnnnnnnnnnnnnnnnnnnn: Invalid response from http://www.xxxxxxxxxxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 404"}
< 6 lines removed )
2023-04-26T00:07:32.124068+00:00 xxxxxxxxxxx xxx 6 boulder-va[347917]: xxxxxxx [AUDIT] Validation result JSON={"ID":"nnnnnnnnnnnn","Requester":nnnnnnnnn,"Hostname":"www.xxxxxxxxxxx","Challenge":{"type":"http-01","status":"invalid","error":{"type":"unauthorized","detail":"nnnnnnnnnnnnnnnnnnnnnnnnn: Invalid response from http://www.xxxxxxxxxxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 404","status":403},"token":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","keyAuthorization":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","validationRecord":[{"url":"http://www.xxxxxxxxxxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","hostname":"www.xxxxxxxxxxx","port":"80","addressesResolved":["nnnnnnnnnnnnn","nnnnnnnnnnnnnn","nnnnnnnnnnnnnnnnnnnnnnnnn","nnnnnnnnnnnnnnnnnnnnnnnnn"],"addressUsed":"nnnnnnnnnnnnnnnnnnnnnnnnn"}]},"ValidationLatency":1.2,"Error":"unauthorized :: nnnnnnnnnnnnnnnnnnnnnnnnn: Invalid response from http://www.xxxxxxxxxxx/.well-known/acme-challenge/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 404"}
```

To make it easier to understand, this is a shortened form.  Assume "123456" and "abcdef" are log lines:
```
123abcdef
... other logs ...
456
... other logs ...
123456
```
Or sometimes
```
123456
... other logs ...
1234abcdef
.... other logs ...
56
```

### Steps to reproduce the behavior
It seems load-related, unclear otherwise.

### Environment
We’ve observed this on both the rsyslog shipped with Ubuntu 20.04 (8.2001.0-1ubuntu1.3) as well as a recent release (8.2304.0-0adiscon1focal1) on those same hosts.

A slightly redacted rsyslogd configuration is here:

https://gist.github.com/mcpherrinm/5159d9c0bddb654255354c38d809a969

**Comment by mcpherrinm** [comment]
The full configuration is in the redacted syslog linked; the only redaction is the censoring of some of the message content rules.  

And you're right, we do have multiple actions writing like this:
```
if $msg contains "xxxx" or $msg contains "xxxxxx" then {
    action( type="omfile" dynaFile="TmplAudit" )
}

if $msg contains "xxxxxx" or $msg contains "xxxxxx" then {
    action( type="omfile" dynaFile="TmplAudit" )
}
```

I can definitely refactor that.  I'm a bit surprised that the failure mode here is data corruption.

**Comment by davidelang** [comment]
I had a problem, so I used threads to solve it
now two problems I have

:-)

unless you put a lock on the file, writing to one file from two places will 
cause exactly this sort of problem because writes to files are not atomic, you 
are writing to a buffer that gets flushed later. manipulating a lock on every 
write can be VERY expensive performance wise.

Rainer will need to weigh in on how the locking here should work.

David Lang

**Comment by mcpherrinm** [comment]
Well, I didn't use think I was using threads, until a log message told me after my data was corrupted.  The rsyslog documentation specifies the main queue has a maximum of a single worker by default: https://www.rsyslog.com/doc/master/rainerscript/queue_parameters.html#queue-workerthreads 

It's not clear to me from documentation other than the statement here that calling a single ruleset is any more safe than multiple actions with the same dynafile template.

**Comment by davidelang** [comment]
the worker parameter is the minimum number of threads, it will create more if 
the load is too heavy (at least that's how I understand it)

Rainer is in Germany, hopefully he will weigh in on this when he wakes up in 8 
hours or so.

David Lang

**Comment by rgerhards** [comment]
The multiple writes are indeed a problem. There is a long-standing project to unify file writes via a global cache, which would solve situations like that. But it's quite some work, especially if we want to keep performance at the current level (non-trivial). Talks to corporate sponsors so far told us that nobody thinks it is really worth investing much into this project. This, in addition with questions on this topic at most once a year make me (so far) think this is nothing to address as a pure community project.

So much to the background, now to the meat:

Each open file keeps it's write cache. Usually, the cache is written out after each transaction, so multiple actions on the same file usually work well. It can become complex if:

* very long messages, so multiple write buffers are needed
* very high concurrency in file writes
* async writing
* compressed write mode (this one is always fatal)

This list is probably not complete.

Doing multiple dynafile actions for the same output template, like you have, is also very performance intense. Each action has it's own dynafile cache, and each cache entry contains the full file object including all buffers. So you have a very high overhead in your config. Both memory-wise as well as runtime-wise. For example, cache evictions will probably often happen on multiple actions at once. **It is stongly recommended to use a single action if you write to the same dynafile target.**

You can refactor the config quite easily.

The easiest approach, though not most efficient, is to define a ruleset (without queue, so it is synchronous!) that contains the action and use `call <rulesetname>` where you right now do the `action()` directly.

Another way is to unify the logic leading to action execution.
Instead of 

```
if $msg contains "xxxxxxxxxxxxxxxxxxxxxx" or $msg contains "xxxxxxxxxxxxxxx" then {
    action( type="omfile" dynaFile="TmplAudit" )
}

if $msg contains "xxxxxxxxxxxx" then {
    action( type="omfile" dynaFile="TmplAudit" )
}

if $msg contains [ "xxxxxx", "xxxxxxx", "xxxxxxx", "xxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx" ] then {
    action( type="omfile" dynaFile="TmplAudit" )
}
```

do

```
if $msg contains [
        "xxxxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxx", /* if 1 */
        "xxxxxxxxxxxx", /* if 2 */
         "xxxxxx", "xxxxxxx", "xxxxxxx", "xxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx" ]  /* if 3 */
    then {
    action( type="omfile" dynaFile="TmplAudit" )
}
```

This will also reduce CPU utilization because the array-based contains is far more efficient than the individual ifs.

Looking at you full config, you probably need to combine both approachs if you want to streamline the ifs as well.

**Comment by mcpherrinm** [comment]
Thanks so much for your time.  I’ve already started the refactoring and it’s going well.  I think I’ll close this issue as it seems like we don’t need anything else from you or the project.
