### ISSUE TITLE
RFE: `ParseKernelTimestamp` or `KeepKernelTimestamp` in imkmsg

### ISSUE THREAD

**Issue by opty77** [rsyslog/rsyslog#5161]
Please add support for at least `ParseKernelTimestamp` configuration parameter or even `KeepKernelTimestamp` too in imkmsg.

(Template skipped due to RFE.)

**Comment by rgerhards** [comment]
Definitely sounds like a good idea. I've seen the other messages and have the whole situation on my focus. Feel free to ping me if you do not hear back by end of the month.

**Comment by opty77** [comment]
@rgerhards: Ping. :-)

**Comment by rgerhards** [comment]
@opty77 sry, it looks like I was severely distracted (complicated year...).

Can you brush me up on the related issues? I can find https://github.com/rsyslog/rsyslog/issues/5160, but it looks like there is more.

**Comment by rgerhards** [comment]
I finally found "the other one", at least I think. It is https://github.com/rsyslog/rsyslog/issues/4561

Based on that issue, I think we do not need options but the path is probably not to rely on the timestamp, except on boot. I'll look closer at the situation, any comments are welcome.

**Comment by opty77** [comment]
> @opty77 sry, it looks like I was severely distracted (complicated year...).
> 
> [...]

@rgerhards: No problem, similar here. :-)

**Comment by rgerhards** [comment]
@opty77 I have now looked into the imkmsg contributed module. It actually parses the timestamp returned from `/dev/kmsg` and times look correct to me even after hibernate. Could it be that the kmsg driver does some magic behind the scenes? In any case, I cannot confirm any bug in that regard.

Also, the integer timestamp is stored in json alongside the message. So with a proper template, you should be able to add it by configuration. I'll post a template somewhat later.

As #5160 talks about **`imklog`** I wonder if you are confusing the two here?

**Comment by opty77** [comment]
@rgerhards: How did you check? I haven't tried imkmsg yet due to #4561 but using imklog I can see the difference between `/var/log/syslog`:

```
2023-10-31T12:54:04.639584+01:00 kiwi kernel - - - [2498588.930168] [IP6TABLES DROP]: IN=venet0 OUT= MAC=<snip> SRC=<snip> DST=<snip> LEN=60 TC=0 HOPLIMIT=236 FLOWLBL=0 PROTO=TCP SPT=58774 DPT=8001 WINDOW=65535 RES=0x00 SYN URGP=0
```

and `dmesg --time-format iso`:

```
2023-10-31T12:52:55,930168+01:00 [IP6TABLES DROP]: IN=venet0 OUT= MAC=<snip> SRC=<snip> DST=<snip> LEN=60 TC=0 HOPLIMIT=236 FLOWLBL=0 PROTO=TCP SPT=58774 DPT=8001 WINDOW=65535 RES=0x00 SYN URGP=0
```
after some uptime. Maybe you use precise RTC?

I considered #5160 unrelated but you know the code better so I haven't objected. :-)

**Comment by rgerhards** [comment]
> Maybe you use precise RTC?

Maybe. Just looks like I cannot do good testing. Would you be up for it if a patch is available? In any case, I guess I can still test the code paths as such,

What I understood is that you want a `parseKernelTimestamp` option, so that you can turn off applying the kernel timestamp - just like in #5160. That would also be a solution for #4561, I guess. In that case, however, we would need to change default behaviour, which we usually do not do lighthearted. But that's another discussion. Now let me look at the option. If you have any concerns, pls let me know.

**Comment by opty77** [comment]
With only one rsyslog instance still at just 8.2102.0 on Debian Bullseye I don't feel like good candidate for testing but maybe @wizeman might?

I'd expect imkmsg defaulting to `ParseKernelTimestamp="off"` (if that option existed) like imklog.

BTW, [documentation](https://github.com/rsyslog/rsyslog-doc/blob/v8.2310.0/source/configuration/modules/imklog.rst#parsekerneltimestamp) says something about time difference.

**Comment by rgerhards** [comment]
@opty77 I have created draft PR https://github.com/rsyslog/rsyslog/pull/5264. It has some rough edges which I will continue to work on soon. As you can see, there are new options. I have refrained from supporting `KeepKernelTimestamp` as it is available via JSON (and probably not needed in the original form anyways).

The patch should basically work. If you can provide feedback, I would be all ears.

**Comment by rgerhards** [comment]
> I'd expect imkmsg defaulting to `ParseKernelTimestamp="off"` (if that option existed) like imklog.

that's the tricky part that needs discussion. Because it would change default behavior. @davidelang do you have a quick  opinion on it?

**Comment by someplaceguy** [comment]
> I'd expect imkmsg defaulting to ParseKernelTimestamp="off" (if that option existed) like imklog.

Wouldn't `FixKernelTimestamp=on` be better, if it works as advertised? i.e. It would work like `ParseKernelTimestamp=on` while booting, i.e. when first processing `/dev/kmsg`, but would then switch to `ParseKernelTimestamp=off` after the initial processing.

I'm saying this because if you keep both `ParseKernelTimestamp=off` and `FixKernelTimestamp=off` by default, then it will have one major downside: the initial boot messages will all appear in the log with almost the same timestamp, which is the problem I have now, e.g.:

```
2023-10-29T17:22:27.664098+00:00 wizylap daemon.info systemd-tty-ask-password-agent[220]: Password query on /dev/tty1 finished successfully.
2023-10-29T17:22:27.664102+00:00 wizylap daemon.info systemd-tty-ask-password-agent[220]: Starting password query on /dev/tty1.
2023-10-29T17:22:27.664108+00:00 wizylap daemon.info systemd-cryptsetup[218]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/<snipped>.
2023-10-29T17:22:27.664112+00:00 wizylap daemon.info systemd-cryptsetup[217]: Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/disk/by-uuid/<snipped>.
2023-10-29T17:22:27.664127+00:00 wizylap daemon.info systemd[1]: Finished Cryptography Setup for root1.
2023-10-29T17:22:27.664131+00:00 wizylap daemon.info systemd[1]: Finished Cryptography Setup for root0.
```

The timestamp of these messages are very similar because they were processed by rsyslog within a short timespan, but in reality they were generated with a few seconds of delay between them (i.e. the time it took for me to enter the password when booting my laptop). The `FixKernelTimestamp=on` should fix this issue if it works well (and I will try it and report back as soon as I can).

**Comment by opty77** [comment]
#5264 looks promising and `FixKernelTimestamp="on"` indeed seems like better default.

**Comment by opty77** [comment]
Thank you very much indeed!

**Comment by rgerhards** [comment]
FYI, there is a closely related PR at https://github.com/rsyslog/rsyslog/pull/5278
