### ISSUE TITLE
Built-in Support for Sequential Identifiers in Log Messages

### ISSUE THREAD

**Issue by CasparQuast** [rsyslog/rsyslog#5183]
Hello,

I'm using rsyslog and have a requirement to generate a unique, sequential identifier for each log message.

As of now, rsyslog doesn't seem to have built-in support for generating such identifiers. I think this would be a valuable feature, allowing users to easily track log messages without external scripts or tools.

Here's an example of how this could be used in a template:

```bash
template(name="SequentialIDTemplate" type="string"
         string="%TIMESTAMP% %HOSTNAME% %syslogtag% %sequential_id% %msg%\n")
```

In this example, %sequential_id% would be replaced by the sequential identifier of each message.

I'd appreciate it if you could consider this feature for a future version of rsyslog. If there's a better way to achieve this with the current capabilities of rsyslog, I'd be glad to know.

Best regards,
Caspar

**Comment by davidelang** [comment]
This is a rather difficult/expensive thing to do in rsyslog due to it's 
multi-threaded nature.

That said, I think you can use the global variables to do this, but there will 
be a fairly substantial performance hit due to the locking needed.

I'm not finding it in a quick google search, but I remember that there were 
atomic inc functions defined.

David Lang

**Comment by maipbui** [comment]
@davidelang can you please share the atomic inc function you referenced above?

**Comment by davidelang** [comment]
you would have to use global variables (which seriously hurt your throughput, 
just use $/foo and incriment it every message.

David Lang
