### ISSUE TITLE
unexpected GnuTLS error -24 in nsd_gtls.c:632: Decryption has failed

### ISSUE THREAD

**Issue by joepointon123** [rsyslog/rsyslog#5266]
Im getting the below error when trying to use TLS for syslog

Nov 02 15:59:23 rsyslogd[799247]: unexpected GnuTLS error -24 in nsd_gtls.c:632: Decryption has failed.  [v8.2008.0.9d70869d4ea5 try https://www.rsyslog.com/e/2078 ]
Nov 02 15:59:23 rsyslogd[799247]: error adding our certificate. GnuTLS error -24, message: 'Decryption has failed.', key: '/etc/rsyslog.d/key.key', cert: '/etc/rsyslog.d/cert.crt' [v8.2008.0.9d70869d4ea5 try https://www>
Nov 02 15:59:23 rsyslogd[799247]: Could not create tcp listener, ignoring port 6514 bind-address (null). [v8.2008.0.9d70869d4ea5 try https://www.rsyslog.com/e/2078 ]

rsyslog.conf below:
**to avoid confusion, I've added the / for the purpose of the github to stop the creation of headers. In the actual config file they aren't there. 

> /#  /etc/rsyslog.conf    Configuration file for rsyslog.
> 
> /#For more information see
> /#/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
> 
> /#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf
> 
> 
> #################
> /#### MODULES ####
> #################
> 
> $ModLoad imuxsock
> $ModLoad imtcp
> 
> /# make gtls driver the default
> $DefaultNetstreamDriver gtls
> 
> /# certificate files
> $DefaultNetstreamDriverCAFile /etc/rsyslog.d/cacert.crt
> $DefaultNetstreamDriverCertFile /etc/rsyslog.d/cert.crt
> $DefaultNetstreamDriverKeyFile /etc/rsyslog.d/key.key
> 
> /# Authentication Mode and Permitted Peers
> $InputTCPServerStreamDriverAuthMode x509/name
> $InputTCPServerStreamDriverPermittedPeer *.com
> $InputTCPServerStreamDriverMode 1
> $InputTCPServerRun 6514
> 
> 
> ###########################
> /#### GLOBAL DIRECTIVES ####
> ###########################
> 
> 
> /# Use traditional timestamp format.
> /# To enable high precision timestamps, comment out the following line.
> /#
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
> 
> /# Filter duplicated messages
> $RepeatedMsgReduction on
> 
> 
> /# Set the default permissions for all log files.
> 
> 
> /#$FileOwner syslog
> /#$FileGroup adm
> /#$FileCreateMode 0640
> /#$DirCreateMode 0755
> /#$Umask 0022
> /#$PrivDropToUser syslog
> /#$PrivDropToGroup syslog
>  
> 
> 
> /# Where to place spool files
> 
> $WorkDirectory /var/spool/rsyslog
> 
> /#Include all config files in /etc/rsyslog.d/

Ive also checked the key and cert output using openssl and the checksums match.

Can anyone shed any light on why this may be happening?

**Comment by rgerhards** [comment]
Well, the GnuTLS library does us not tell much when it has problems...  "Decryption failed" is actually not bad, given what we see otherwise. I guess it has some problems with the encryption of the cert files. Hint: they must not be password protected.

Please note that we implemented the `ossl` driver which uses OpenSSL instead of GnuTLS for the purpose of better error messages. It also seems to be much more forgiving in such cases. You can just replace `gtls` with ´ossl´ to make it work.

**BUT:** the openssl driver often needs to be installed first. It usually is in a package named ´rsyslog-ossl` or likewise.

> I've added the / for the purpose of the github to stop the creation of headers. In the actual config file they aren't there.

use three backticks before and after the config - that's how you flag things as preformatted, code-like. Just FYI.

**Comment by davidelang** [comment]
you are using 8.2008 (august of 2020 release date), There has been a lot of work 
on improving error messages related to TLS since then (although the gnutls 
library makes it hard as Rainer said in his reply). you may want to try a more 
current release and/or try switching from gnutls to ossl (openssl) which tends 
to give better error messages)

all I can say is gnytls is unahappy trying to access the cert.crt file using the 
provided key.key file

David Lang

**Comment by rgerhards** [comment]
Great to hear!
