### ISSUE TITLE
implement an option to permit regular rsyslog runs be terminated by CTL-C

### ISSUE THREAD

**Issue by sebest** [rsyslog/rsyslog#533]
Hello,

I'm using rsyslog in docker so i use the "-n" option but rsyslog never exits on Ctrl+C

If i start it with -dn, it will exits cleanly.

I use an empty /etc/rsyslog.conf to test

I can reproduce the exact same behaviour without docker

step to reproduce:
- docker run -ti ubuntu:15.10 bash
- apt-get update && apt-get install rsyslog
- echo > /etc/rsyslog.conf
- rsyslog -dn
- ctrl+c -> works
- rsyslog -n
- ctrl+c -> hangs forever

**Comment by rgerhards** [comment]
That is intended. Ctl c is for debug. Shutdown is sigterm.

**Comment by sebest** [comment]
What would be the drawback of supporting sigint?

**Comment by rgerhards** [comment]
Why is it important? I think the risk is that rsyslog could potentially abort in situation where this is totally unexpected. Remember, it is ignoring sigint for 30 years now! And, again, I don't see any problem with sending it sigterm, is there?

**Comment by radu-gheorghe** [comment]
Just my 2 cents:

I find it a bit annoying that when I start it with -n I have to open another terminal to kill it. I'm used to other apps that when I open them in foreground I can do CTRL+C.

Is it really possible to send sigint by accident so you'd unexpectedly kill it? Also, is it possible to only support sigint while starting with -n? Because I suppose that's when people expect it to stop on CTRL+C.

Anyway, I don't think it's an important change, but I'd surely welcome it. Though I can't speak for the rest, of course.

**Comment by rgerhards** [comment]
-n is used by systemd, so that's the usual way of calling it. I really can't say which scripts may eventually exist that may send ctl-c to rsyslog. I just wonder if it is a good idea, just for a convenience, to take this risk.

Let me phrase it that way: If someone adds a global option (or command line switch) that enables ctl-c, does a PR and properly documents it, I am not opposed as merging such a PR. But I won't do it, simply because I have much more pressing things. And, yes, I agree it's inconvenient, for me as well :-)

**Comment by sebest** [comment]
It was looking like a bug to me, i did not encounter (m)any daemon with this behaviour when running in foreground, and i could not find any mention of this behaviour in the documentation. (also the fact that there is no --help was surprising and i could not find the list of valid command line options on http://www.rsyslog.com/doc/v8-stable/).

**Comment by radu-gheorghe** [comment]
I would vote for keeping this issue open, just so we have a reminder for fixing (not necessarily you, @rgerhards ;)) in the long run.

**Comment by timbunce** [comment]
I just hit this as well (using rsyslogd 8.9.0).

I'd like rsylogd to die on sigint, which _is what it's documented to do_ per the rsyslogd man page:
```
    SIGNALS
        ...
        TERM ,  INT ,  QUIT
              Rsyslogd will die.
```

**Comment by mostolog** [comment]
Hi @rgerhards @radu-gheorghe 

Running rsyslog in a docker container with "-n" option allows logging to stdout (hence, redirecting to syslog using docker options).

I find **CTRL+C** very useful for **gracefully shutting down** process. Also I won't need to open another terminal to kill rsyslog, like mentioned below.

Doesn't _sigterm_ just "kill" the rsyslogd process without letting him save messages on queues and all that nice-stuff?

**Comment by radu-gheorghe** [comment]
I *think* sigterm will kill rsyslog nicely. As far as I remember, if you do "service rsyslog restart" it gets sigterm and saves queue files to disk if it's configured to do so. A test (or Rainer :p) will confirm 100%

Otherwise, it would be a very nasty bug - meaning one can only stop rsyslog nicely if it's started in debug mode.

**Comment by mostolog** [comment]
**Confirmed**. kill -15 does a clean exit, which is same as _docker stop_

```
4891.150626632:main thread    : DoDie called.
4891.150661981:main thread    : exiting on signal 15
4891.150671061:main thread    : Terminating input threads...
...
4891.167504260:main thread    : destructing strgen 'RSYSLOG_FileFormat'
4891.167519537:main thread    : destructing strgen 'RSYSLOG_TraditionalFileFormat'
4891.167530814:main thread    : destructing strgen 'RSYSLOG_ForwardFormat'
4891.167541931:main thread    : destructing strgen 'RSYSLOG_TraditionalForwardFormat'
4891.167554591:main thread    : rsyslog runtime de-initialized, current users 0
4891.167564853:main thread    : Clean shutdown completed, bye
```

Then, the only reasons left to enable CTRL+C is "not needing to open another terminal to signal" and comply with https://linux.die.net/man/8/rsyslogd
