### ISSUE TITLE
The uploaded logs to cloud are disorder

### ISSUE THREAD

**Issue by melix-sun** [rsyslog/rsyslog#5407]
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, the related configurations are as below:
[9:59] HUANG Hongping
#$WorkDirectory /diagUpdate/onlineSyslog # where to place spool files
-----------
$ActionQueueType LinkedList   # run asynchronously

$ActionQueueFileName uniqName # unique name prefix for spool files

$ActionQueueSize 20000

$ActionQueueDequeueBatchSize 1000

$ActionQueueHighWaterMark 18000

$ActionQueueLowWaterMark 14000

$ActionQueueMaxFileSize 10m

$ActionQueueMaxDiskSpace 200m   # 200m space limit (use as much as possible)

$ActionQueueDequeueSlowDown 10000000

$ActionQueueSaveOnShutdown on # save messages to disk on shutdown

$ActionResumeRetryCount -1    # infinite retries if host is down

$ActionQueueTimeoutEnqueue 0
 
----------

**Comment by davidelang** [comment]
if you mean that the logs appear in the cloud out of order once you have spooled 
to disk and are sending in parallel from both the in-memory queue and the disk 
queues, that is performing as expected.

The disk queues are very slow compared to the memory queues, so once you are out 
of memory and have sent things to disk, not sending the stuff in memory (so that 
things stay in order) would require that you write it to disk, only to read it 
again later, would be likely to cause more problems due to the slow process of 
delivering the logs from disk.

Syslog log delivery is not guaranteed to be in-order, it's possible for USP 
packets to 'pass' each other on a complex enough network, add in relays and 
multi-threading and trying to preserve order cripples performance and will still 
fail in some conditions.

David Lang

**Comment by melix-sun** [comment]
Thanks David for answering my issue, this is really helpful .
