### ISSUE TITLE
GNUTls vs OpenSSL - Check of certificate purpose - BUG or not

### ISSUE THREAD

**Issue by shinigami35** [rsyslog/rsyslog#5478]
Hello team,

In my case, I use TLS for my logs.
Since a long time, I used GNUTLS driver for this but since few weeks I decided to use OpenSSL driver because I add some problems with GNUTls.

During this modification, I detected a "behaviour" between OpenSSL and GnuTls implementation on Rsyslog.
I explain it :

When you generate a certificate you must set some purpose to specify the use of this certificate. In our case, we need a certificate that can be use as TLS Server and TLS Client. 
But my company changed rules and now we have to separate certificate : 
- One for TLS Server
- One for TLS Client

I decided to do a test with OpenSSL driver and GnuTLS driver on "x509/name" mode.
I generated a certificat with only the TLS Server purpose activated and I use this certificat with the "input" and "output" modules (IMTCP and OMFWD)
During this test I applied the same configuration for both.

I tested like that
| Sending server (Driver)|      Log reception server (Driver) | Status of reception |
|:----------:|:-------------:|:-------------:|
| GNUTLS |  GNUTLS | Allow |
| GNUTLS |  OSSL | Not allow (error 26) |
| OSSL |  GNUTLS | Allow |
| OSSL |  OSSL | Not allow (error 26) |

**### Conclusion**
The GNUTLS driver can use a certificate with the purpose "TLS Server" to receive and to forward logs to another Rsyslog. And this is not normal because normaly, this certificate can only be used as a TLS server (receiving logs)
The OpenSSL driver check if this is a TLS Server or a TLS Client when you use the certificat and does not allow to use this certificat to forward logs. (OpenSSL error 26)

**So my question is :** Why GNUTLS does not care of certificat Purpose and only Openssl Driver check it ? 

_This could be a problem a security because we can use with GNUTLS driver any TLS certificat purposes to receive and forward logs._
 

### Steps to reproduce the behavior
**### FWD Server**
```
module(load="impstats" format="legacy"  interval="60" resetCounters="on")
module(load="imtcp" MaxSessions="4000") 

$DefaultNetstreamDriverCAFile /etc/rsyslog-certificates/CA.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog-certificates/machine.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog-certificates/machine.key



input(type="imtcp" port="514" ruleset="main" DiscardTruncatedMsg="on")

ruleset(name="fwdtest"){
        action(type="omfwd"
                name="fwd_test"
                action.resumeRetryCount="-1"
                action.resumeInterval="1"
                queue.type="linkedlist"
                queue.saveOnShutdown="on"
                target="X.X.X.X"
                protocol="tcp"
                port="6514"
		StreamDriver="gtls" # replace here for test
                StreamDriverMode="1"
                StreamDriverAuthMode="x509/name"
                StreamDriverPermittedPeers="test2.test.com"
               )
}

ruleset(name="main"){
       call fwdtest
	   stop
}
```

**### Receiving Server**
```module(load="imuxsock")
module(load="impstats" format="legacy"  interval="60" resetCounters="on")
module(load="imtcp" MaxSessions="4000") 


$DefaultNetstreamDriverCAFile /etc/rsyslog-certificates/CA.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog-certificates/machine2.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog-certificates/machine2.key



input(type="imtcp" port="514" ruleset="main" DiscardTruncatedMsg="on")

input(type="imtcp" port="6514" ruleset="main" address="X.X.X.X"
       StreamDriver.Name="ossl" # GTLS or OSSL : replace here for test
       StreamDriver.Mode="1"
       StreamDriver.Authmode="x509/name"
       PermittedPeer=["test1.test.com"] # List of CN allowed on this server
      )
}

ruleset(name="fwdtest"){
	    action(type="omfile" file="/var/log/test_tls.log")
}

ruleset(name="main"){
       call fwdtest
	   stop
}
```

### Environment
```
rsyslogd  8.2408.0 (aka 2024.08) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64
```

**Comment by davidelang** [comment]
from a technical point of view, there is no difference between a client cert and 
a server cert other than some text comments (and there is no standardization on 
what text means what)

Just like there is no difference between your private key and the public key. 
you could switch them and everything would work. (anything encrypted with the 
public key can be decrypted with the private key, anything encrypted with the 
private key can be dectypted by the public key). But to avoid accidently sending 
the wrong key out, instead of just calling them 'key1' and 'key2' they are 
called 'private' and 'public' as a bit of social engineering and mnemonic to get 
you to use them consistantly.

So Rsyslog doesn't do any checking on any comment text in the keys, it's up to 
the libraries to do that if you want to.

You can tell rsyslog what keys to accept, you don't have to use public CAs and 
trust any certs that they sign. In fact, you shouldn't. The number of entities 
that can sign certs is very large.

David Lang

**Comment by shinigami35** [comment]
Hello David,

I understand what you said and I agree with that. 
I did not check on the Rsyslog code the "use" of those both libraries before opening this issue. and now I know that Rsyslog is more like a middleware between the data and the library.
So this difference of implementation of TLS are not related to Rsyslog.

In my point of view, there is a difference when you set up a Client cert or a Server cert. Those both purposes exist to add a little layer of security when you use certificat.
But in many of cases, people always set up a certificat with those both purposes activated and it is not normal. This is not a " good way " for security.

Best regards,
Shini

**Comment by davidelang** [comment]
shinigami35 wrote:

> In my point of view, there is a difference when you set up a Client cert or a Server cert. Those both purposes exist to add a little layer of security when you use certificat.
> But in many of cases, people always set up a certificat with those both purposes activated and it is not normal. This is not a " good way " for security.

There is a difference in how you use the cert, but from a technical point of 
view, there is not. The math underlying the cert is the same.

David Lang

**Comment by shinigami35** [comment]
Hello,

I will close this issue and open a new one to GNUTLS to ask them why this beahaviour appeared.

Best regards
Shini

**Comment by saper** [comment]
@shinigami35 do you file something with gnutls? I have found the following somewhat related issues https://gitlab.com/gnutls/gnutls/-/issues/808 and also for the command line usage https://gitlab.com/gnutls/gnutls/-/issues/1027 https://gitlab.com/gnutls/gnutls/-/issues/1028

it seems that the matter is in the hands of the GNUTLS user and it seems that rsyslog does lots of low-level stuff here.

https://github.com/rsyslog/rsyslog/blob/f9a05a25809b3368097306d1d5d64be7578f3a3c/runtime/nsd_gtls.c#L1277-L1289

This piece of the code could be doing what is reported here - can you check if you have those checks enabled at the build time via `EXTENDED_CERT_CHECK_AVAILABLE` ([enabled when building for GNUTLS 3.4 or newer](https://github.com/rsyslog/rsyslog/blob/f9a05a25809b3368097306d1d5d64be7578f3a3c/runtime/nsd_gtls.h#L120))?

> just like there is no difference between your private key and the public key.
you could switch them and everything would work. (anything encrypted with the
public key can be decrypted with the private key, anything encrypted with the
private key can be decrypted by the public key). 

This is only (kind of) true for the pure RSA algorithm. You can think of the two keys as "my key" and "their key". Sure technically you can swap $`{m^{e}}^{d}`$ as you wish, but do want your private key to become public?

Elliptic curve keys do not have this property. 

> you don't have to use public CAs and trust any certs that they sign

This is true. Fortunately we can refuse to join the X.509 game and just use private and public keys. 

However, if you do want to - or have to - use X.509, key usage and purpose may play important role. It can prohibit for example that your server key could be used to sign additional certificates and become a wild certificate authority itself. 

Or, just because someone has permission to install the private key and the certificate on the rsyslog client, they should not be able to use the same key to connect to the VPN for example.
