### ISSUE TITLE
omkafka need a maxoutqueuesize counter

### ISSUE THREAD

**Issue by chenryn** [rsyslog/rsyslog#572]
the omkafka now only record a 'Queue Full' error, I think it's better to record a librdkafka outqueue max size counter, just like rsyslog maxqsize.

**Comment by garyelephant** [comment]
+1

**Comment by rgerhards** [comment]
+1, but I have no idea of how to do that. So a PR would be appreciated.

**Comment by chenryn** [comment]
I create https://github.com/rsyslog/rsyslog/pull/574

**Comment by garyelephant** [comment]
It turns out that it's useless to tune `queue.X` in omkafka action, because omkafka will put messages into `librdkafka's buffer queue` imediately.When buffer queue in librdkafka is full, newer messages will be dropped(Pity that librdkafka hasn't have a persistence of it's buffer queue).The problem is omkafka doesn't know whether librdkafka's buffer queue is full or not, so it will never keep redundant messages in omkafka's own queue.
