### ISSUE TITLE
Re-enable disabled tests

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#711]
In the past the following tests were disabled and probably forgotten:

* imtcp_conndrop_tls.sh by 9293a1eb07235a852afe5322612fe8e37a2b96b8
* sndrcv_tls_anon.sh by 0509f1404170c5aff7c9a154fbe882f4d067b1e4
* sndrcv_tls_anon_rebind.sh by 0509f1404170c5aff7c9a154fbe882f4d067b1e4
* imtcp-tls-basic.sh by 0509f1404170c5aff7c9a154fbe882f4d067b1e4
* random.sh by a568626d4a627d226f203eb83f41b731e0f00ac9

Finally we have the following tests not used at the moment:

* pmlastmsg.sh
* queue-persist-drvr.sh
* msgvar-concurrency-array.sh (seems to be forgotten to add by 003ba7f003314557cdded842fd2267a9ef479d78)

This list was created manually so it is maybe incomplete.

**Comment by rgerhards** [comment]
Good point!

I think some of these tests are deliberately disabled, because they are too racy (even more than the occasional failures we have with some enabled tests). IIRC, this is the case for the *_tls_* tests, @alorbach can you confirm?

Not sure on pmlastmsg, will check. queue-persists-drvr.sh is actually used, it is a driver called by other tests. and you are most probably right with msgvar-concurrency-...

**Comment by rgerhards** [comment]
Ah, hold on: I added msgvar-concurrency-... yesterday, it's just not yet merged:

https://github.com/rgerhards/rsyslog/commit/bd5c00c635a882bbb7f917a3c34f6df060c092a7

The merge may need some time if we need to upgrade some of the testbench machines to libfastjson. If so, that will be noted in the PR: https://github.com/rsyslog/rsyslog/pull/708
