### ISSUE TITLE
impstat field names with dots don't go well with Elasticsearch 2.0

### ISSUE THREAD

**Issue by volter** [rsyslog/rsyslog#713]
Some impstats output fields use periods as separators:

 - ratelimit.discarded
 - ratelimit.numratelimiters
 - suspended.duration
 - failed.http
 - failed.httprequests
 - ...

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

According to the above, no periods should be used as separators in field names. This is hard or impossible when using a template like:

property(name="$!all-json" position.from="2")

**Comment by rgerhards** [comment]
Well, it was an Elasticsearch decision to break JSON compatibility... Anyhow, I'll add this as feature request to add an option which permits to use different hierarchy delimiters.

**Comment by portante** [comment]
@rgerhards, would you consider doing it as a hierarchical json object switch instead so that the emitted JSON would look like:

```
{
    "ratelimit": {
        "discarded": 10,
        "numratelimiters": 12
    },
    "suspended": {
        "duration": 10
    },
    "failed": {
        "http": 0,
        "httprequests": 1000
    }
}
```

**Comment by rgerhards** [comment]
@portante this sounds good

**Comment by davidelang** [comment]
we don't want to change the structure of the pstats output multiple times (or have too many different varients to select), so doing a scrub module first is a good idea

when we go to restructure the pstats, a good first cut would be just to look at what the structure is if you change the . to be a level indicator. that probably gets us close.

**Comment by portante** [comment]
On Tue, Dec 22, 2015 at 1:21 PM, davidelang <notifications@github.com>
wrote:

> we don't want to change the structure of the pstats output multiple times
> (or have too many different varients to select), so doing a scrub module
> first is a good idea
>

So adding a scrub module to change variable names independent of what
pstats emits?  That would work, but why add more processing overhead in the
message pipeline if we can get the source to emit the names properly?

Can you suggest a concrete example of what you mean?

Thanks, -peter

**Comment by rgerhards** [comment]
Just for the records: we emit proper json, ES does not understand proper
json. We are taking about a workaround for an ES standards violation.

Sent from phone, thus brief.
Am 22.12.2015 22:44 schrieb "Peter Portante" <notifications@github.com>:

**Comment by davidelang** [comment]
The thing is that problem names can come from many sources, including stuff that 
is sent to rsyslog as JSON from other sources.

So a scrub module that lets us 'clean up' names to deal with problematic 
characters (where 'problematic' can be caused by many different software 
packages) gives the admin the ability to work around problems.

changing the structure of the pstats output could also work around the 
ElasticSearch 'feature', but it wouldn't solve the other issues.

David Lang

**Comment by portante** [comment]
On Tue, Dec 22, 2015 at 5:10 PM, davidelang <notifications@github.com>
wrote:

> The thing is that problem names can come from many sources, including
> stuff that
> is sent to rsyslog as JSON from other sources.
>
> So a scrub module that lets us 'clean up' names to deal with problematic
> characters (where 'problematic' can be caused by many different software
> packages) gives the admin the ability to work around problems.
>
> changing the structure of the pstats output could also work around the
> ElasticSearch 'feature', but it wouldn't solve the other issues.
>

I agree with you. We need a scrub module for data sources beyond rsyslog's
control, but I would like to see us avoid using that for cases like this
where the source of the names that need adjusting are within rsyslog's
control.

-peter

**Comment by davidelang** [comment]
On Tue, 22 Dec 2015, Peter Portante wrote:

> I agree with you. We need a scrub module for data sources beyond rsyslog's
> control, but I would like to see us avoid using that for cases like this
> where the source of the names that need adjusting are within rsyslog's
> control.

Two things.

first, even if we are going to change things (and I think we probably should) we 
should take the time to make sure we are doing it right and not rush

secondly, When the problem is that popular tools decide to take things that used 
to work and are valid per the spec and make them invalid (and in the process 
ignore agreements made with and between others in the same field when faced with 
the same problem, in this case the project lumberjack folks who ddecided to use 
! to flatten out JSON structures), it's not possible to avoid problems down the 
road. I'll point out that rsyslog has been using the . in the fieldnames since 
before elasticsearch decided to reserve it (and has been using ! in names to 
indicate hierarchy), so even if we change things today, it's no guarantee that a 
future release of ES won't break it. And even less guarantee that other tools 
won't break it in the future.

now, I think it makes a lot of sense for us to offer a 2d structure for the 
pstats data, but I agree that we don't want to rush the changes to pstats.

so a varnamescrub module lets us address this and other issues, so it's a good 
first cut at the problem.

David Lang

**Comment by rgerhards** [comment]
While I basically agree on the "no rush" policy and all said, I still have crafted a workaround. Two reasons for this:
*  I know I won't be able to work on a varnamescrub before mid-feb or even mid-march
* the fix now done took 15 minutes, which I had left anyhow
So I hope this is useful in the interim and that doesn't mean I won't go for a varnamescrub module.

**Comment by taotetek** [comment]
@rgerhards we filed a bug against ES concerning this issue ( https://github.com/elastic/elasticsearch/issues/15404 ) but gained no traction.  This ended up causing us quite a bit of pain ( on the ES side, not the rsyslog side - this is not rsyslog's fault )

**Comment by davidelang** [comment]
I went over there and made the following post:

During the Project Lumberjack discussions, we were talking about ways to 
'flatten' references to multi-tier JSON structure elements and during that 
discussion we picked ! as the level delimiter, because it's a reserved character 
in so many languages, people are very unlikely to use it in a name. As this 
discussion demonstrates, using a period as the delimiter is problematic as it's 
a common character to use in variable names.

Perhapse the easiest path forward is to tweak Elasticsearch so that the 
delimiter character is configurable. For ES2.0, leave the default as '.' (as 
currently defined and documented), and consider migrating to '!' going forward.

Rsyslog uses ! as the delimiter, and it is the default on linux distros right 
now.
syslog-ng uses . as the delimiter, so it would have the same problem that ES 
currently has.
logstash accesses multi tier data as [level1][level2]
nxlog doesn't implement any support for multi-level variables
sumologic uses . as the delimiter, so it would have the same problem

so in spite of people discussing he issue and the problems using dot as the 
separator and agreeing on a 'standard', it seems that the different logging 
systems have gone in different directions (the nice thing about standards is 
that there are so many to choose from )-:

David Lang

**Comment by volter** [comment]
Thank you for your efforts!

**Comment by volter** [comment]
Guess what! https://www.elastic.co/blog/elasticsearch-5-0-0-released

> Finally, dots-in-fieldnames are back, but properly supported this time

You've got to love their continuity.

**Comment by rgerhards** [comment]
looks like we need to switch default for dot replacement ;-)
