### ISSUE TITLE
Duplicated logging with ' imjournal'

### ISSUE THREAD

**Issue by 78722689** [rsyslog/rsyslog#750]
Environment:
rsyslogd 7.4.7
sysemd 219
Linux host-192-168-0-39 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Problem: every log print twice in /var/log/messages
Test Step:
1. Add "$ModLoad imjourna" in /etc/rsyslog.conf
2. Write a bash file "app.sh" with only context 
while true
do
    echo "$(date '+%Y-%m-%d-%H:%M:%S')  my message"
    sleep 1s
done

3. Write a systemd service file "app.service" for this script:
[Unit]
Description=Application as an Example for systemd
[Service]
ExecStart=/home/cam/app.sh
[Install]
WantedBy=multi-user.target

4. systemctl start app

5. Find the print in /var/log/message, every message with timestamp printed twice????????

**Comment by rgerhards** [comment]
This sounds strongly like a config issue. I suggest contacting the mailing list for faster help. My guess is that journal forwarding to the log socket is still active, thus messages are duplicated. But the ML will probably provide more concrete advise. I am closing this issue tracker, please feel free to re-open if it turns out to be a bug.
