### ISSUE TITLE
testbench: add tests for omkafka

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#900]
if possible. see also #898.

**Comment by janmejay** [comment]
Cool, let us aim for linux-only setup.

Because distros will build this on different flavours of Linux distro provided package will make it complicated. I am thinking of distro provided binaries. 

Even if we harden it and get it working perfectly, building from source is not really going to be very good user experience.

Distro provided binaries sounds good?

**Comment by janmejay** [comment]
Also, this will require JVM. We'll expect user to install JVM using distro provided mechanism. That itself has a bunch of complexity depending on which distro of java the user chooses. On travis we can't escape this one, so we'll pick openjdk (distro provided binary) unless its too old to run kafka 0.8.x.

**Comment by rgerhards** [comment]
I think the key aim is to get things running on travis.

Sent from phone, thus brief.
Am 22.03.2016 13:28 schrieb "Janmejay Singh" <notifications@github.com>:

**Comment by rgerhards** [comment]
Just some extra thoughts now that I have a better keyboard ;)

I do not fully understand distro-provided packages vs. binaries. Do you really want not to use the packaging system, but rather extract the binaries and use them? That sounds much more complicated to me.

If you have not already done so, have a look at the .travis.yml and the script under ./tests/travis. I setup all that I can so that at least the compile can happen (and thus the static analyzer run) and, if possible, dynamic testing is also possible. I think we don't need to be 100% aligned with what the actual user does, but at least be able to run the test. That's a really big plus.

**Comment by janmejay** [comment]
Sorry, let me clarify the terms:
- distro provided packages: dependencies we install using
package-manager(apt) in travis (or stuff users install using their own
package manager while building from source)
- project provided binaries: archives containing binaries that projects
release (make available for download alongside versioned source-archives).

In java-world, its a fairly common thing for projects to make releases that
provide both (usually separate) source and binary archives (tar.gz, zip
etc), because almost no java-based-projects have architecture-specific
binaries (the binaries in this case are JVM opcode, not machine opcode),
this works for everyone(across architectures, as long as they have JVM).

For instance, someone looking to use Kafka can fetch kafka-binary-archive
(say from a link such as this:
https://www.apache.org/dyn/closer.cgi?path=/kafka/0.8.2.2/kafka_2.11-0.8.2.2.tgz),
unarchive it, setup appropriate config files and fire-up the startup script.

So when I say distro-provided-binary vs. project-provided-binary, I don't
mean re-packaging distro-provided package, I mean pulling it down from
project-release-server.

So I am thinking about it as:
- We get openjdk using their package-manager (get it using apt on travis)
- configure with --enable-kafka-tests, which enables the tests that need
kafka and zookeeper.
- When we run those tests, kafka and zookeeper project-provided binaries
are downloaded(and cached in tmpdir) and setup & teardown is managed at
test level

What do you think?

On Tue, Mar 22, 2016 at 7:14 PM, Rainer Gerhards <notifications@github.com>
wrote:

> Just some extra thoughts now that I have a better keyboard ;)
>
> I do not fully understand distro-provided packages vs. binaries. Do you
> really want not to use the packaging system, but rather extract the
> binaries and use them? That sounds much more complicated to me.
>
> If you have not already done so, have a look at the .travis.yml and the
> script under ./tests/travis. I setup all that I can so that at least the
> compile can happen (and thus the static analyzer run) and, if possible,
> dynamic testing is also possible. I think we don't need to be 100% aligned
> with what the actual user does, but at least be able to run the test.
> That's a really big plus.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/900#issuecomment-199822078>
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
ah, OK "**project**-provided packages" makes a lot of sense. We just need to have a stable location from where we can always download them. It the project doesn't offer that, we could mirror the packages. As I said, we do this already occasionally. 

Note that we cannot cache anything on Travis, because the Travis environment is always a fresh VM so everything needs to be redone (except when using contains, which we cannot due to missing dependencies and unability to use sudo).

On the actual integration: I would suggest that the testbench simply assumes the subsystem in question (e.g. kafka) is present and running in a default configuration. This is what the current tests do. For Travis, we can add steps before the actual testbench call to make the system ready. For the buildbot machines, we can actually configure them to match thar prequisite. These are not always rebuild from scratch, so we do not need to install each and everything for any test run.

It would of course be best if we could share setup scripts (for things like kafka) between Travis and the buildbot environment. I will soon work on that in the mysql case (which, btw, is a good example on how we currently do it on Travis).

**Comment by janmejay** [comment]
Makes sense.

The only problem I see is, it will make the build too complex.

A new user won't really "be done" with ./configure, make and make check
anymore, which discourages ppl from running tests, eventually diminishing
the value of tests.

What you are saying makes perfect sense for MySQL, because distros provide
a package with some basic (impractically done, but working) config.
Expecting user to have it "running" before triggering the build is a
reasonable expectation (it pretty much takes one to fire up apt-get install
mysql-server to have a working server).

For non-distro-provided projects such as Kafka or Elasticsearch or HDFS, we
can't assume the same thing. Even if we provide setup / teardown scripts,
user will have to know when it needs to be run and it pushes this
non-standard (unexpected) step in otherwise easy to use autotools build.

My proposal is to have kafka-based-tests pull down both Zookeeper and
Kafka, cache the binaries (so that next test won't need to fetch it again),
setup both zk and kafka, run the test and tear down both of them before
terminating.

The next test can then use the cached binaries (doesn't need to fetch
again) and repeat setup -> use -> teardown cycle.

I wasn't talking about caching across travis builds (it was about caching
for other tests in the make check invocation, in the same travis-build, to
benefit from).

What do you think?

On Tue, Mar 22, 2016 at 8:00 PM, Rainer Gerhards <notifications@github.com>
wrote:

> ah, OK "*project*-provided packages" makes a lot of sense. We just need
> to have a stable location from where we can always download them. It the
> project doesn't offer that, we could mirror the packages. As I said, we do
> this already occasionally.
>
> Note that we cannot cache anything on Travis, because the Travis
> environment is always a fresh VM so everything needs to be redone (except
> when using contains, which we cannot due to missing dependencies and
> unability to use sudo).
>
> On the actual integration: I would suggest that the testbench simply
> assumes the subsystem in question (e.g. kafka) is present and running in a
> default configuration. This is what the current tests do. For Travis, we
> can add steps before the actual testbench call to make the system ready.
> For the buildbot machines, we can actually configure them to match thar
> prequisite. These are not always rebuild from scratch, so we do not need to
> install each and everything for any test run.
>
> It would of course be best if we could share setup scripts (for things
> like kafka) between Travis and the buildbot environment. I will soon work
> on that in the mysql case (which, btw, is a good example on how we
> currently do it on Travis).
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/900#issuecomment-199839746>
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
I think we are talking about two different things.

For a user who just wants to do "make check", I don't think he needs to run e.g. kafaka tests (except, of course, if he changes omkafka, in which case I guess he has the necessary components).

What I am talking about is the CI environment. All test requiring special environment need a --enable-test configure option and should be disabled by default. The paradigm we should use, I think, is

for CI run:
   * setup environment
   * run make / make check
  
This is actually the case for Travis. For Buildbot, we take the "setup environment" step out of the CI run, as we can permanently install the components on the buildbot slaves.

For a test, the paradigm should be:

* clean up environment (e.g. delete tables, reset anything that needs to be reset)
* run to be tested functionality
* check outcome
* if all OK cleanup environment again (more or less a convenience here)

I may not understand kafka, but what is the benefit of starting the whole subsystem just for a single test and shutting it down thereafter? I mean compared to starting it up once and then running all tests against the instance. We do the later for elasticsearch. It needs to be present, and if it is then ES-tests use it (well, actually not in the moment due to some recent regression which is also on the todo list... - but nevertheless this is how it works and worked well). I don't object starting and stopping complete subsystems just for a single test, I just want to understand why this is a benefit.

Rainer

**Comment by janmejay** [comment]
Only 2 benefits:
- tests are all self contained and side-effect free as far as possible. The
kind of issues like when test X and Y are run together Y fails, but when
each one is run separately, they both pass.
- its simpler (because there is one less step to worry about for someone
working with it)

Both kafka and elasticserach have problems that lead to operations being
partly complete (eg. say teardown requires deletion of a topic in kafka, in
some cases the topic lives in "marked for delete" state, but trying to
create topic by the same name won't succeed, which will affect run of next
test that needs the topic, with Elasticsearch, you'll have indexes
resurrecting after delete). Test level setup/teardown allows us to do purge
of working-directory, which allows us to start with a clean-slate
regardless of what happened in previous tests.

The downside of doing it is clearly performance (it'll be slower to
setup/teardown for every such test), which can be partly amortized by
increasing scope of integration tests). Eg. I am thinking of only one(or
two) kafka-integration-test(s) which actually post messages and verifies
the content is available with kafka. It can verify both static and dynamic
topic support in one run (config will have an action for dyn-topics and
another one for static topic etc).

Thoughts?


On Wed, Mar 23, 2016 at 5:47 PM, Rainer Gerhards <notifications@github.com>
wrote:

> I think we are talking about two different things.
>
> For a user who just wants to do "make check", I don't think he needs to
> run e.g. kafaka tests (except, of course, if he changes omkafka, in which
> case I guess he has the necessary components).
>
> What I am talking about is the CI environment. All test requiring special
> environment need a --enable-test configure option and should be disabled by
> default. The paradigm we should use, I think, is
>
> for CI run:
>
>    - setup environment
>    - run make / make check
>
> This is actually the case for Travis. For Buildbot, we take the "setup
> environment" step out of the CI run, as we can permanently install the
> components on the buildbot slaves.
>
> For a test, the paradigm should be:
>
>    - clean up environment (e.g. delete tables, reset anything that needs
>    to be reset)
>    - run to be tested functionality
>    - check outcome
>    - if all OK cleanup environment again (more or less a convenience here)
>
> I may not understand kafka, but what is the benefit of starting the whole
> subsystem just for a single test and shutting it down thereafter? I mean
> compared to starting it up once and then running all tests against the
> instance. We do the later for elasticsearch. It needs to be present, and if
> it is then ES-tests use it (well, actually not in the moment due to some
> recent regression which is also on the todo list... - but nevertheless this
> is how it works and worked well). I don't object starting and stopping
> complete subsystems just for a single test, I just want to understand why
> this is a benefit.
>
> Rainer
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/900#issuecomment-200325775>
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
ok, that makes sense. I am unused to "partly complete opertions" after a commit ;) Just to make sure you are actually aware of it: under buildbot slaves, we do not have root permissions. So you cannot install anything on the machine that requires a real install.

I'd say it would be great if you could boil up something for Travis, so I also see how exactly this is supposed to work. We'll then need to see if we can mirror it to at least some of the buildbot environments. But even if it only works under travis, that's a big win.

**Comment by janmejay** [comment]
Of-course, we'll have nothing that requires sudo/su etc. Its a bad idea to
do privileged stuff in a test run anyway. It'll confuse users really bad.
If we ever encounter a situation where we need to do sudo stuff, we won't
follow this model for those cases.

Zookeeper and Kafka (in kafka-integration-test) will just involve
project-provided-binary download, force-clean unarchive location,
force-shutdown stray kafka and zookeeper processes, unarchive afresh,
configure, start and stop+force-clean after test ends. No installing in
privileged locations (this will all be in a specific directory "tmp" in
<project-root>/test or <project-root>. This dir will be git-ignored.

On Wed, Mar 23, 2016 at 8:03 PM, Rainer Gerhards <notifications@github.com>
wrote:

> ok, that makes sense. I am unused to "partly complete opertions" after a
> commit ;) Just to make sure you are actually aware of it: under buildbot
> slaves, we do not have root permissions. So you cannot install anything on
> the machine that requires a real install.
>
> I'd say it would be great if you could boil up something for Travis, so I
> also see how exactly this is supposed to work. We'll then need to see if we
> can mirror it to at least some of the buildbot environments. But even if it
> only works under travis, that's a big win.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/900#issuecomment-200369855>
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
2016-03-23 15:46 GMT+01:00 Janmejay Singh <notifications@github.com>:

> Of-course, we'll have nothing that requires sudo/su etc. Its a bad idea to
> do privileged stuff in a test run anyway. It'll confuse users really bad.
> If we ever encounter a situation where we need to do sudo stuff, we won't
> follow this model for those cases.
>

That situation is actually pretty common, e.g. if you try to install MySQL,
PGSQL, etc, etc. But it's good to know you do not need to actually install
something onto the system, that of courses relaxes things quite a bit :-)

As I said, the testbench never does sudo, thus it expects the system is
setup properly. In Travis, we do install packages, but that's outside of
the testbench (and there is no other way to do it).

Rainer

**Comment by janmejay** [comment]
Makes sense, we'll not have any privileged actions at all. Even MySQL(at
least Maria and Percona branches) can be installed to non privileged
location. Not sure about postgres.

So we have a plan, I'll do this coming week.

**Comment by rgerhards** [comment]
2016-03-23 18:23 GMT+01:00 Janmejay Singh <notifications@github.com>:

> Makes sense, we'll not have any privileged actions at all. Even MySQL(at
> least Maria and Percona branches) can be installed to non privileged
> location. Not sure about postgres.
>
>
side-note: that may very well be, but finding out all the details is much
to time-consuming for me (having otherwise no interest in these softwares).
So if there is a package, I'll use it ;)


So we have a plan, I'll do this coming week.


Sounds great. I'll anyhow merge the open PR, because there rellay is no
dependency.

Thanks for all the help,
Rainer

**Comment by janmejay** [comment]
Sorry for the confusion, I didn't mean we should not use distro provided
packages. Things like MySQL have good default configuration in distro
provided packages, so if a user adds --enable-mysql-integration-tests, and
if we print the environment expectations at the end of configure (say we
tell user that we expect a "root" user with all-privileges in MySQL with
no-passowrd, we need server to be up, and we will destroy and recreate
tables/databases, we should be fine.

All of what I'm proposing applies only when we are dealing with
not-so-common package which most distros don't provide.

**Comment by janmejay** [comment]
https://github.com/rsyslog/rsyslog/pull/967

**Comment by rgerhards** [comment]
done via #967
