### ISSUE TITLE
rsyslog dropping messages on half-duplex close

### ISSUE THREAD

**Issue by horsehay** [rsyslog/rsyslog#939]
Running version 1.6.4 and having issues with rsyslog losing messages. I have rsyslog pointed to haproxy which then connects to an elasticsearch pool. I'm using omfwd over TCP. The haproxy is closing the connection using what is referred to as a half-duplex close (see Connection Termination at https://en.wikipedia.org/wiki/Transmission_Control_Protocol).

It seems that rsyslog isn't honoring it and the connection between rsyslog and haproxy goes to close-wait state. When rsyslog sends the next message, haproxy sends a reset and the connection is closed, but rsyslog doesn't try resending the message (even with resend options enabled). 

I've also tried enabling keepalive options on omfwd, but that seems to be completely broken.

**Comment by davidelang** [comment]
This is a fundamental problem with TCP. When rsyslog sends the data to the OS TCP stack, it gets back a 'success' error code, later on the OS sends the data to the remote machine and gets an error back. At that point the OS has no way to tell rsyslog what data didn't get sent.

This is why RELP was created

for a more detailed writeup see http://blog.gerhards.net/2008/04/on-unreliability-of-plain-tcp-syslog.html

**Comment by quixoten** [comment]
I think this should be re-opened. I was digging into this more with @horsehay and rsyslog is definitely throwing away messages it shouldn't be. Here's the flow of packets captured by tcpdump (we sent one log, waited for haproxy to timeout the connection, then sent another log):

```
# sending the first log creates the connection and sends the log
rsyslog (CLOSED)     => SYN     => haproxy (CLOSED)
haproxy (SYN-RCVD)   => SYN-ACK => rsyslog (SYN-SENT)
rsyslog (SYN-SENT)   => ACK     => haproxy (SYN-RCVD)
rsyslog (ESTAB)      => PSH-ACK => haproxy (ESTAB)
haproxy (ESTAB)      => ACK     => rsyslog (ESTAB)

# haproxy times-out the connection after inactivity
haproxy (ESTAB)      => FIN-ACK => rsyslog (ESTAB)
rsyslog (CLOSE-WAIT) => ACK     => haproxy (FIN-WAIT-1)

# now we try to ship another log, but rsyslog never tries
# to send it. instead, it just finishes closing the socket,
# throws the log away, and opens a new connection
rsyslog (CLOSE-WAIT) => FIN-ACK => haproxy (CLOSED)
haproxy (CLOSED)     => RST     => rsyslog (CLOSED)
rsyslog (CLOSED)     => SYN     => haproxy (CLOSED)
haproxy (SYN-RCVD)   => SYN-ACK => rsyslog (SYN-SENT)
rsyslog (SYN-SENT)   => ACK     => haproxy (SYN-RCVD)
```

We created a one-off ruby script to see how it handles the same scenario. Everything is equivalent until we try to send the second log after timeout. Ruby doesn't close the connection. It attempts to send the data, and when it does an error is raised `Broken pipe (Errno::EPIPE)`:

```
ruby    (CLOSE-WAIT) => PSH-ACK => haproxy (CLOSED)
haproxy (CLOSED)     => RST     => ruby    (CLOSE-WAIT)
```

This establishes two pieces of evidence that suggests that this is a detectable state that rsyslog should be able to recover from without losing the message:

1. rsyslog behaves differently when its socket is in a CLOSE-WAIT state. It sends a FIN-ACK rather than attempting to send the message.
1. a ruby script raises an error under the same conditions that rsyslog is sending a FIN-ACK.
