### ISSUE TITLE
mmjsonparse: add option to make @cee cookie optional

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#940]
I think this was also suggested by @davidelang some time ago. While we can do this with mmnormalize, direct support in mmjsonparse seems natural and should be easy to implement.

The milestone of 8.18 is not a hard one, but we may get it into that version.

**Comment by davidelang** [comment]
On Thu, 7 Apr 2016, Rainer Gerhards wrote:

> I think this was also suggested by @davidelang some time ago. While we can do 
> this with mmnormalize, direct support in mmjsonparse seems natural and should 
> be easy to implement.

There are a number of other features of mmnormalize that it would be good to get 
into mmjsonparse as well.

The ability to parse something other than $msg ($rawmsg is a common need, but 
being able to parse any variable would be good)

The ability to put the result someplace other than $!

From the point of view of eliminating code duplication, would it make sense to 
essentially eliminate mmjsonparse and make it be a special case of mmnormalize 
that has a small, predefined ruleset? What would the performance impact be?

something along the lines of:

%.:cee%
%.:json%
%-:whitespace%%.:cee%
%-:whitespace%%.:json%
%msg:rest%
%-:whitespace%%msg:rest%

possibly with some allowance for whitespace variation? (I've managed to see a 
space betwen the cookie and the json for example, I don't remember exactly what 
the cause was)

David Lang

**Comment by rgerhards** [comment]
Let's go for the simple bait, first. I am not sure it really is a good idea to force-use liblognorm here. It's pretty small code to implement...

**Comment by rgerhards** [comment]
I have not yet tested this, but I think you can already use the ```cookie=""``` action parameter and it will not require the CEE cookie or any other cookie at all. I'll verify, but thought I let you know ASAP.

**Comment by rgerhards** [comment]
I have verified that setting ```cookie=""``` makes mmjsonparse process all kinds of JSON messages. Spaces in front of the json are permitted, but note that nothing after the JSON is permitted. For those cases, you need mmnormalize. I don't intend to change this.
