### ISSUE TITLE
add ability to format unix date

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#971]
Please add the ability to turn numeric values into timestamps

i.e. if you have $!foo = "1454527741.918"

be able to treat it as a timestamp and extract month, day, year, convert it to rfc3164 date, rfc3339 date, etc

either a rainerscript function to convert it or make the template date formatting code work on unix timestamps.

It would probably also be useful to have something like an isdate() function that will return true if the variable can be treated as a timestamp.

**Comment by mrworkman** [comment]
@rgerhards, I was reviewing this and some other RainerScript "enhancement" issues, and I'd like to implement it/them (if that's ok).

For this particular one, I thought it'd be best if I got your input since I imagine you already have some idea of how you'd like to see it implemented.

I see it as something like this (returning a string):

* `to_timestamp(unix_time, dformat);`

e.g.
* `to_timestamp(unix_time, 'rfc3164')`; or
* `to_timestamp(unix_time, 'rfc3339')`; or
* `to_timestamp(unix_time, '%Y-%m-%d %H:%M:%S')`.

Or would you prefer some kind of conversion function to convert from any 'timestamp' to another, such as: `convert_timestamp(stimestamp, sformat, dformat)`?

**Comment by davidelang** [comment]
I think it's best to run everything explicitly through unix timestamp (possibly 
a modified unix timestamp to allow for subsecond resolution)

instead of to_timestamp(), how about format_time()?

and then there could be a function

parse_time(format,dformat)

I'm not sure if the source should be a format or a variable. I expect that most 
of the time this is needed (especially with the liblognorm support to put the 
result in unix format) is when the parts of the timestamp end up in different 
variables and need to be combined and then parsed. The parseformat would be the 
normal date standards

**Comment by mrworkman** [comment]
`format_time()` sounds reasonable. 
<br/>

RE: `parse_time()`
> I'm not sure if the source should be a format or a variable.

Wouldn't a variable be required, regardless?

**Comment by davidelang** [comment]
On Tue, 3 Oct 2017, Stephen Workman wrote:

> RE: `parse_time()`
>> I'm not sure if the source should be a format or a variable.
>
> Wouldn't a variable be required, regardless?

the thing is that it may be many variables. If date is in one place and time in 
another place, to get a timestamp, you will need to combine them.

So you would need to have a template and then do

set $.x = exec_template(template)
followed by
parse_time($.x,dformat)

I think this is going to be more common than having a timestamp in a single 
variable that you are converting (which would be a trivial template to define)

**Comment by mrworkman** [comment]
Gotcha.

**Comment by rgerhards** [comment]
> the thing is that it may be many variables. If date is in one place and time in
> another place, to get a timestamp, you will need to combine them.
> 
> So you would need to have a template and then do
> 
> set $.x = exec_template(template)
> followed by
> parse_time($.x,dformat)
> 
> I think this is going to be more common than having a timestamp in a single
> variable that you are converting (which would be a trivial template to define)

The exec_template() function is relatively expensive and I personally think it should only be used if there is no other way around. If you have a variable ```$!date``` and ```$!time```, you could simply use
```
parse_time($!date & " " & $!time)
```
to obtain a string combining them.

Other than that, I fully agree with what David said. Two functions make a lot of sense and permit to be kept flexible. For example, if $timereported is RFC3164, for a type of conversion, you can simply do
```
format_time(parse_time($timereported), "rfc3339")
```
One may just think about an optional second parameter to ```parse_time()``` which can be used to force the timestamp detection to a specific format. This can be used to remove ambiguity that otherwise may exist.

@mrworkman I definitely appreciate any contribution in this regard (as I appreciate all contributions!). In order to be able to merge quickly, I would suggest to do smaller steps, which I can also easily verify. I would start with the ```format_time()``` function, which means we could also discuss all issues based on it. But that's just an suggestion, it obviously is up to you how you would like to proceed.

**Comment by davidelang** [comment]
On Tue, 3 Oct 2017, Rainer Gerhards wrote:

> The exec_template() function is relatively expensive and I personally think it should only be used if there is no other way around. If you have a variable ```$!date``` and ```$!time```, you could simply use

agreed

> ```
> parse_time($!date & " " & $!time)
> ```
> to obtain a string combining them.

I did not know you could do that.

> Other than that, I fully agree with what David said. Two functions make a lot of sense and permit to be kept flexible. For example, if $timereported is RFC3164, for a type of conversion, you can simply do
> ```
> format_time(parse_time($timereported), "rfc3339")
> ```
> One may just think about an optional second parameter to ```parse_time()``` which can be used to force the timestamp detection to a specific format. This can be used to remove ambiguity that otherwise may exist.
>
> @mrworkman I definitely appreciate any contribution in this regard (as I 
> appreciate all contributions!). In order to be able to merge quickly, I would 
> suggest to do smaller steps, which I can also easily verify. I would start 
> with the ```format_time()``` function, which means we could also discuss all 
> issues based on it. But that's just an suggestion, it obviously is up to you 
> how you would like to proceed.

Yes!!!! start with the simple stuff and work from there.

a simple format_time() function will be incredibly useful.

with the changes to liblognorm we have one way to get 'normal' timestamps into 
unix time (@rgerhards, does that allow for fractional seconds??), and there are 
other things that generate output in Unix time. So format_time() is useful even 
without a parse_time() function.

**Comment by rgerhards** [comment]
I have added the "ElasticSearch unix timestamp with ms" as a format. While this does not give a very precise timestamp, I think ms should usually be good enough. That said, we probably need two ```format_time()``` functions, one for each internal timestamp format.

**Comment by mrworkman** [comment]
> If you have a variable `$!date` and `$!time`, you could simply use

    parse_time($!date & " " & $!time)`

> to obtain a string combining them.

>> I did not know you could do that.

I was thinking it could just be done that way too - otherwise the internals of `format_time()` would get significantly more complex.

> I would start with the ```format_time()```

We're on the same page there. This is exactly what I was intending to do, otherwise it'd be a pain to merge.

What is the format of an "ElasticSearch unix timestamp with ms"? Is it as in the original example "1454527741.918"? If so, we could probably accommodate that without a second `format_time()` function.

<br />
For the future, given this example:

    format_time(parse_time($timereported), "rfc3339")

`parse_time()`'s return value could only be a UNIX timestamp, correct? (just clarifying intent). I think an optional second parameter to "force the timestamp detection to a specific format" is a must.

**Comment by mrworkman** [comment]
Was thinking about `parse_time()`. What should it do when it fails? It can't return -1, because that's a valid UNIX timestamp. It could return the original value as I've set up `format_time()` to do, but nesting like```format_time(parse_time($timereported, "date-rfc3164"), "date-rfc3339")``` would essentially become a noop. Thoughts? 

As far as I know, RainerScript has no other way of reporting function failure, does it?

**Comment by rgerhards** [comment]
I probably would make it return 0 and live with the date that if the date
is really begin of epoch (very, very, very unlikely, isn't it?) A nested
invocation would return an Invalidi Date. Even then that would be
detectable.

Does that make sense? IMO anything else would require considerate
refactoring.

**Comment by rgerhards** [comment]
@mrworkman can we consider this as implemented/closed?

**Comment by mrworkman** [comment]
Yes, I think it can be closed.

**Comment by rgerhards** [comment]
thx. I we missed something, we can always open a new one ;-)
