### ISSUE TITLE
action 18 but not /dev/xconsole in config

### ISSUE THREAD

**Issue by gungazoo** [rsyslog/rsyslog#972]
I have rsyslog ingesting remote logs and sending them to a file and to a named pipe.  Tenshi reads from the named pipe and emails.

Everything seems to be working just fine but I get *a lot* of these messages:

rsyslogd-2007 warning rsyslogd-2007: action 'action 18' suspended,

and then the resumed.  

Is this simply a bug or something I can ignore or is my pipe filling up to be emptied by tenshi and am I losing messages before the retry?

Thanks,

Peter

**Comment by davidelang** [comment]
On Wed, 20 Apr 2016, gungazoo wrote:

> I have rsyslog ingesting remote logs and sending them to a file and to a named pipe.  Tenshi reads from the named pipe and emails.
>
> Everything seems to be working just fine but I get *a lot* of these messages:
>
> rsyslogd-2007 warning rsyslogd-2007: action 'action 18' suspended,
>
> and then the resumed.
>
> Is this simply a bug or something I can ignore or is my pipe filling up to be 
> emptied by tenshi and am I losing messages before the retry?

The pipe is being emptied and delivery is stopping. I think that all log 
processing is stopping as opposed to loosing messages.

David Lang

**Comment by gungazoo** [comment]
Thanks for the reply

Let me see if I understand.  While reading (emptying) is going on delivery is stopped?  It checks back and resumes.  So everything is fine and I can ignore these messages?

**Comment by davidelang** [comment]
Yes, if the pipe is not being read fast enough by tenshi, all log processing on that queue in rsyslog stops, and then will resume when a retry detects that it can deliver messages again.

We are investigating a possible bug that could cause messages to be lost when this happens, and in any case, this will horribly slow down all log processing (not just to the rate that tenshi can handle it, but slower than that due to the pauses between retries)

I would look at bumping up the size of the pipe buffer (I know it can be done, but I don't remember how), and looking to see if you can speed up tenshi, or run multiple copies (multiple worker threads).

This sort of error is an indication of a real problem, but if it's rare you may not care. If it's frequent it can then cause other grief. I would suggest enabling the impstats module so that you can get good stats about what's happening inside rsyslog, see if you are falling behind, etc.
