### ISSUE TITLE
Duplicate & loss of messages with RELP whenever rsyslog-server is restarted

### ISSUE THREAD

**Issue by dud225** [rsyslog/rsyslog#979]
Hello

I'm noticing severe message duplication and loss whenever the rsyslog server is restarted when using RELP.

Here are the step to reproduce :
- setup rsyslog with RELP and send 2 messages A and B from rsyslog-client to ensure everything is OK
- restart rsyslog server
- send message C, rsyslog-client doesn't send anything because of TLS connexion breakage
- send message D, this time the connexion is re-established and rsyslog-server writes messages A and B again plus C
- send message E, rsyslog-server writes E normally, message D is lost
- restart rsyslog-server again
- send message F, rsyslog-client doesn't send anything because of TLS connexion breakage again
- send message G, rsyslog-server writes message A, B, C and E **again** plus message F. Message G is lost as well as D.
- etc...

Here is my setup :
- OS : Debian testing
- rsyslog v8.16.0-1+b1 & librelp v1.2.10-1

Confiiguration details :
- [client.txt](https://github.com/rsyslog/rsyslog/files/232099/client.txt)
- [server.txt](https://github.com/rsyslog/rsyslog/files/232102/server.txt)

Regards,
dud

**Comment by dud225** [comment]
There are actually 2 issues here :
- message duplication
- message loss

After diving into this issue again, I noticed that the message loss behaviour has been fixed. After some research [this commit](https://github.com/rsyslog/rsyslog/commit/5ee6e4f8e9abbd7eb9fb116ca48545c1ca8a6bfa#diff-c245bc2e6f98365bca144d6c877de320) seems to be the successful one. Thanks Rainer.
Regarding the other issue, as far as I understand it is more related to librepl, thus opening new issue [https://github.com/rsyslog/librelp/issues/47](there).

dud

**Comment by davidelang** [comment]
with relp, messages that have been sent, but that the ack has not arrived at the 
sender yet will be re-sent when a reconnection is make.

the alternative is to not re-send them, all you know is that you think you sent 
them, but the recipient didn't ack them.

so the choice is between risking duplication (if the message did arrive and the 
ack was lost), or loss (if the message got lost, not the ack)

relp exists for the purpose of avoiding message loss, so it falls on the side of 
re-sending the messages.


any message loss you are getting is probably due to messages sitting in a memory 
queue when something reboots and not getting written to disk on restart. the fun 
is going to be in tracking down exactly where the issue is.

David Lang
