### ISSUE TITLE
use AX_COMPILER_FLAGS in rsyslog

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#985]
@mbiebl has added this to libfastjson, and it worked out very well. It ensures consistent warning messages. We should add this to rsyslog as well. Probably, this means we also need to do some cleanup (albeit we still have enabled many warnings).

**Comment by rgerhards** [comment]
done, but we needed to exclude a very limited set of options.

**Comment by rgerhards** [comment]
The macro should default to Warning only, IIRC. @mbiebl suggested it
exactly for this reason.

Sent from phone, thus brief.

Am 11.07.2016 22:40 schrieb "Thomas Deutschmann" <notifications@github.com>:

**Comment by Whissi** [comment]
Mh, see https://www.gnu.org/software/autoconf-archive/ax_compiler_flags.html:

> Check for the presence of an –enable-compile-warnings option to configure, **defaulting to "error" in normal operation,** or "yes" if IS-RELEASE is equal to "yes". Return the value in the variable $ax_enable_compile_warnings.

[...]

> –enable-compile-warnings can take the values:
> 
>  * no:      Base compiler warnings only; not even -Wall.
>  * yes:     The above, plus a broad range of useful warnings.
>  * error:   The above, plus -Werror so that all warnings are fatal.
>             Use --disable-Werror to override this and disable fatal
>             warnings.

If you set IS-RELEASE in the release tarball I have nothing to do :)

PS: You should enable verbose build so you see which flags will be set.

**Comment by Whissi** [comment]
*AX_IS_RELEASE* requires *>=autoconf-archive-20150224* (wily+).

But this shouldn't be a problem. Like I outlined in 2015 while doing 5f5eca03a09671b5df609f9ee6f885d63bbedaca we should depend on our special ".tarball-version" file for detection (i.e. move the detection to the beginning so we can use the variable not only for detecting the need of *flex*...). This will help people (I think Debian is doing that) who are storing releases in git so they don't create special development builds because they don't notice... At least this was my intention for the "hack".

I'll prepare a PR over the weekend.

**Comment by rgerhards** [comment]
Some info: looks like I need to include the macros anyhow as i have seen
e.g. centos 6 did not provide autoconf-archive at all. That seems also to
account for some other errors...

Sent from phone, thus brief.

Am 14.07.2016 18:18 schrieb "Thomas Deutschmann" <notifications@github.com>:

**Comment by mbiebl** [comment]
Would it be a problem if downstreams/distros explicitly set this via the configure switch in their build scripts, i.e. --enable-compile-warnings=yes (or no) ?

**Comment by mbiebl** [comment]
That said, the addition of AX_IS_RELEASE [1] is certainly not a bad idea.
As @Whissi said, in Debian I use Git to manage the package. So even for release builds I will have a .git directory. But that's not a huge problem, because:
a/ I usually don't build directly from the git directory but use an export first (via git-buildpackage)
b/ I could just set --enable-compile-warnings=yes in debian/rules, should I ever decide to directly build from a git directory without an export step.

[1] https://www.gnu.org/software/autoconf-archive/ax_is_release.html

**Comment by rgerhards** [comment]
A patch was merged yesterday and will now work across all platforms.
